# Fictional assessed transfer scenarios. No patient or institutional records.
ASSIGNMENTS={
12:dict(step='TRACE',title='Trace the hazard to a control',minutes='35–45',artifact='Hazard → requirement → verification',
 warm='A barrier controller follows every programmed command correctly. Does that establish that it cannot strike a pedestrian?',warmanswer='No. The requirements or sensing assumptions may be unsafe. Identify the hazardous situation, an appropriate control and the evidence needed to verify it.',
 scenario='A fictional campus is evaluating an automatic loading-bay barrier. The proposed safety requirement is: the barrier must not close while the monitored zone is occupied. A prototype has passed the recorded daylight tests with an unobstructed camera. The test report does not include low light, rain or a covered lens. A separate stop button exists, but no drill report shows how quickly an operator can recognize a hazard and use it. Deployment is proposed for both day and night. You advise the service owner: release, restrict the pilot, or hold.',
 fit='Identify one concrete hazard, the possible accident and who could be harmed. Distinguish these from an ordinary software failure.',
 measure='Write one trace: hazard → safety requirement → design control → verification activity. Label each element already supported by the supplied evidence and each that is only proposed. Do not invent a numerical risk rating.',
 bound='State the operating conditions supported by the evidence and a condition that would require a new safety decision.',
 act='Choose release, restricted pilot or hold. Name one responsible role and the evidence that must support the chosen boundary.',
 measurecrit='A coherent hazard-to-requirement-to-control-to-verification trace, with existing and proposed evidence clearly separated.',
 stress='After Part A is committed, a daylight replay shows that the controller treats a missing camera frame as an empty zone. The stop button shares the controller power supply. No accident is reported in this teaching scenario. Explain how this changes your original hazard argument and which evidence is now needed.',
 refit='State which link in the original hazard trace is weakened or broken, then defend RETAIN, REVISE or REPLACE.',
 source='X03, X05, X06, D12 and B01; original slides 15–32 and 44–58.'),
13:dict(step='TEST',title='Turn a misuse case into a test',minutes='35–45',artifact='Threat → control → negative test',
 warm='A student can download their own file. Does that test show they cannot download another student’s file?',warmanswer='No. It tests allowed behavior. Test a distinct user’s request for a protected object and verify server-side authorization, including any export path.',
 scenario='A fictional university portal has student and staff roles. Students should access only their own project files; staff should access only the groups assigned to them. The interface hides other students’ files. A developer reports that every ordinary upload/download test passed. The API receives a project identifier in the request, but the brief contains no cross-user authorization test. Log retention is configured, but nobody has reviewed a sample for sensitive content. You recommend release, restricted access, or hold.',
 fit='Identify one asset, one threat and one plausible vulnerability from the brief. Keep a suspected weakness distinct from a demonstrated exploit.',
 measure='Write two test cases: one allowed request and one forbidden request. State the actor, input/object, expected result and evidence to inspect. The tests are proposed, not executed.',
 bound='State which roles, objects and access paths the recommendation covers. Name an untested path and a reopening trigger.',
 act='Choose a bounded release action. Link a concrete server-side control to the tests and identify the reviewer.',
 measurecrit='One positive and one negative authorization test, each with actor, input, observable expected result and evidence; no invented execution result.',
 stress='A reviewer now provides a trace showing that the preview endpoint rejects a cross-user request, but the bulk export endpoint checks only whether the requester is logged in. The trace uses synthetic student accounts. Explain the implication for the scope of the original security claim.',
 refit='Name the control or coverage assumption contradicted by the new trace and specify the final action and retest scope.',
 source='X02, X05, X06, R09 and R18; original slides 29–43 and 59–70.'),
14:dict(step='RECOVER',title='Keep one critical service running',minutes='40–50',artifact='Critical service → degraded mode → recovery check',
 warm='A backup server starts successfully. Is the essential service necessarily recovered?',warmanswer='No. Check data freshness, dependencies, user access and the ability to deliver the required service. Process uptime alone is not a service-level recovery result.',
 scenario='A fictional campus transport desk must retain access to the day’s pickup list when its central scheduling server is unavailable. A local copy is refreshed at 06:00. Authorized staff can read it on a desk device. Changes after 06:00 normally remain on the central server until the next refresh. The brief includes a successful restart log for a backup server, but no full service rehearsal. Staff can record changes on a controlled paper form during an outage. You recommend whether this fallback is ready for a limited trial.',
 fit='Name the essential service and distinguish it from full normal functionality. Identify the users and dependencies that matter during failure.',
 measure='Describe recognition, resistance, recovery and reinstatement for one outage. Include how staff check data freshness and reconcile paper changes. Mark untested steps as proposed.',
 bound='State the allowed operating scope and the staleness or confidentiality condition that makes the fallback unacceptable. Any new threshold must be labelled proposed.',
 act='Choose trial, restricted trial or hold. Give the immediate action, owner and one rehearsal that would test the service rather than only the server.',
 measurecrit='A coherent response across the four resilience activities, including usable degraded service, reconciliation and a testable recovery check.',
 stress='The outage rehearsal reveals that the desk device and backup server both require the same central sign-in service, which is also unavailable. The local pickup list is present but authorized staff cannot open it. No bypass is authorized. Revisit the shared dependency and the claimed fallback.',
 refit='Explain what the shared dependency does to your proposed recovery path. Defend the revised boundary and the evidence needed before another trial.',
 source='X02, X04, D14, X06 and B01; original slides 6–17 and 28–61.'),
15:dict(step='COMPARE',title='Choose a reuse strategy with evidence',minutes='40–50',artifact='Options → constraints → justified choice',
 warm='A purchased system costs less to acquire than a custom build. Is it necessarily the cheaper option over its useful life?',warmanswer='No. Integration, configuration, support, upgrades, migration and exit constraints affect the lifecycle comparison. Do not invent missing costs.',
 scenario='A fictional faculty needs a room-booking service for a three-year pilot. Option A is a configurable commercial product with the required booking functions and an export API; its support commitment ends after two years. Option B is an existing university application with an owned codebase, but it lacks recurring bookings and has no measured peak-load results. The team knows the university codebase. No reliable total-cost estimates have been supplied. The target is a pilot next term, not a complete enterprise replacement. Recommend an option, a restricted evaluation or a hold.',
 fit='Classify the two reuse approaches and identify the required functions and non-functional constraints.',
 measure='Compare the options against four relevant reuse-planning factors. Mark each entry supported, unknown or dependent on a condition. Do not invent scores, prices or performance.',
 bound='Identify a lifecycle assumption that must hold and a specific change that would reverse the recommendation.',
 act='Make a bounded selection or evaluation decision. Identify the owner and the evidence needed to settle one consequential unknown.',
 measurecrit='A comparison using relevant planning factors, traceable facts and visible unknowns, leading to a defensible conditional choice.',
 stress='The vendor clarifies that Option A’s export API provides booking records but excludes recurring-booking rules and approval history. The university application owner confirms that the team may extend Option B, but still supplies no capacity measurements. Explain how these facts change your comparison.',
 refit='Update only the affected assumptions and explain why the final choice is retained, revised or replaced.',
 source='X02, D15, X03, X06 and R09; original slides 5–15 and 41–56.'),
16:dict(step='CONTRACT',title='Validate a component contract',minutes='40–50',artifact='Interface → semantics → adapter and tests',
 warm='A method signature accepts a number named duration. Does the signature establish whether the value means minutes or seconds?',warmanswer='No. Units are part of interface semantics. The caller and component must share a documented contract, including limits and error behavior.',
 scenario='A fictional lab-booking application reuses a component with reserve(roomId, duration). The caller supplies duration in minutes. The component documentation defines duration in seconds, requires 1 ≤ duration ≤ 7200, and says an accepted call returns a reservation identifier. A thin adapter currently forwards both arguments unchanged. A sample call using duration = 30 returns an identifier. No test has checked the stored end time or invalid-input behavior. Recommend whether to use, adapt or replace the component for a limited pilot.',
 fit='Separate the syntactic match from the semantic mismatch. Name the provides service and one caller obligation.',
 measure='Write a precondition and postcondition in clear notation or OCL-style form. Specify the adapter conversion and give one boundary/invalid-input test with an expected observable result.',
 bound='State the input range and documented behavior your recommendation relies on. Name the unanswered error-handling question.',
 act='Choose use, adapt, replace or hold. Name the integration owner and evidence required to check the contract after composition.',
 measurecrit='A coherent pre/post contract, justified unit conversion, valid range and a discriminating boundary or invalid-input test.',
 stress='A new trace shows that, if a room is already reserved, the component returns the existing reservation identifier without indicating a conflict. The brief did not document this behavior. No second reservation was created. Explain the effect on your postcondition and on what a successful return means.',
 refit='Identify the invalidated semantic assumption. State the final contract, action and evidence needed without guessing a new exception type.',
 source='X03, B01, R09, D16 and D16B; original slides 14–22 and 40–59.'),
17:dict(step='FAILURE',title='Reason about a lost remote response',minutes='40–50',artifact='Architecture → failure sequence → recovery evidence',
 warm='A remote payment call times out. Can the caller safely assume the payment did not happen?',warmanswer='No. The server may have executed the request before the response was lost. Retrying needs a defined identity, deduplication or reconciliation mechanism.',
 scenario='A fictional event-registration system uses a browser, an application service and a booking database. The browser sends a reservation request through the service. When the request times out, the browser automatically retries with a new request identifier. The database creates one reservation per new identifier. The brief confirms that normal requests succeed, but contains no test where the response is lost after a database commit. You recommend a pilot architecture and retry policy.',
 fit='Map the logical responsibilities to deployment tiers. Identify the remote boundary and distinguish failure to receive a response from failure to execute.',
 measure='Write a short event sequence for the lost-response case. Propose a retry/reconciliation rule and a test that would reveal duplicate reservations. State what remains an assumption.',
 bound='State the failure modes and consistency requirement your recommendation covers. Identify the limit of the supplied tests.',
 act='Recommend a bounded pilot action and an owner. Explain the mechanism and the evidence required before accepting automatic retries.',
 measurecrit='A causally correct failure sequence, justified retry or reconciliation rule, and a test that distinguishes one committed action from duplicate actions.',
 stress='A failover drill shows that the deduplication record is stored only in the application service’s memory. After the service restarts, a retry can create another database reservation even when the same request identifier is reused. Revise the scope of your earlier mechanism.',
 refit='Explain why stable request identity alone may be insufficient and what durable evidence or recovery rule your final decision requires.',
 source='X02A, X03, X05, R09 and X09; original slides 14–28 and 53–64. Retry-specific reasoning is a labelled course application.'),
20:dict(step='INTEGRATE',title='Make an integration decision across owners',minutes='45–55',artifact='Governance → interfaces → staged acceptance',
 warm='All participating systems pass their local tests. Does that establish a working system of systems?',warmanswer='No. Cross-system interfaces, independent changes and emergent behavior still need acceptance evidence at the level of the shared service.',
 scenario='A fictional university plans a shared incident dashboard using campus security, transport and facilities systems. Each system remains operational on its own and has a different owner and release schedule. Security supplies incident identifiers; transport supplies vehicle locations with timestamps; facilities supplies building-access status. The owners agree to a limited daytime pilot, but no agreement defines a common freshness limit or how to display an unavailable feed. Local API tests passed. No cross-system failure rehearsal has been performed.',
 fit='Classify the SoS and identify managerial and operational independence. Name one shared service that creates value for the pilot.',
 measure='Propose an interface/governance record for two constituents and a staged acceptance test across them. Include ownership, version/freshness assumptions and useful behavior when one feed is absent.',
 bound='Separate what the pilot owner can control from what requires agreement. State a trigger for suspending or narrowing the shared claim.',
 act='Recommend pilot, restricted pilot or hold. Name the responsible coordination role, participating owners and evidence needed for the next stage.',
 measurecrit='A feasible cross-owner agreement and staged acceptance test that handles incomplete participation and makes assumptions and authority explicit.',
 stress='The transport owner changes its update interval from every minute to every 20 minutes, without changing the API shape. Security still reports current incidents. The pilot owner cannot require transport to revert. Explain how the shared dashboard should change its claims and acceptance decision.',
 refit='Show how independent evolution affects the shared service. Defend the final deployment boundary, visible uncertainty and negotiated next step.',
 source='X02A, X03, X04, X05, X06 and X08; original slides 15–41 and 48–60.')
}
