/* Stable core route, explicit source review, and optional iSCARB toolkit. */
(function(){
'use strict';
var ch=LECTURE.path.chapter,core=U.filter(function(u){return u.route==='core'}),originalGo=go;
function byKey(k){return U.findIndex(function(u){return u.k===k})}
function routeOf(i){return U[i]&&U[i].route||'toolkit'}
function target(dir){var route=routeOf(cur),j=cur+dir;while(j>=0&&j<U.length){if(routeOf(j)===route&&!U[j].showIf)return j;j+=dir}return-1}
function jump(k){var i=byKey(k);if(i>=0)go(i,true)}
fitSlide=function(){var el=deck.querySelector('.slide.on .fit');if(el)el.style.transform='none'};
fit=function(){var stage=document.getElementById('stage');stage.style.transform='none';stage.style.setProperty('--reader-zoom',ZOOM);fitSlide()};
routeCounts=function(){var a=core.filter(function(u){return u.k!=='TITLE'&&u.k!=='END'});return{total:a.length,seen:a.filter(function(u){return S.seen&&S.seen[u.k]}).length}};
visibleInDirection=function(dir){return target(dir)>=0};
updateLectureControls=function(){document.getElementById('prevBtn').disabled=target(-1)<0;document.getElementById('nextBtn').disabled=target(1)<0};
go=function(i,force){if(!force){var dir=i>cur?1:-1;i=target(dir)}if(i<0||i>=U.length)return;originalGo(i,true);deck.scrollTop=0;var u=U[i];try{history.replaceState(null,'','#'+u.k);localStorage.setItem(KEY+'-last-unit-v20260921',u.k)}catch(e){}document.querySelectorAll('[data-route-tab]').forEach(function(b){var on=b.dataset.routeTab===u.route;b.classList.toggle('current',on);b.setAttribute('aria-pressed',String(on))});updateLectureControls();};
fillOver=function(){var h='';[['core','Classroom route','Follow this sequence with the instructor. Three short interaction stops.'],['study','Required source review','Start with the named required pages and five-objective check. Use the full ledger for clarification.'],['toolkit','iSCARB toolkit and enrichment','Decision tools, extra practice, H-Stack, AI verification and deeper cases. Open when useful.']].forEach(function(group){h+='<div class="lp-group">'+group[1]+'<small>'+group[2]+'</small></div>';U.forEach(function(u,i){if(u.route!==group[0])return;h+='<button class="oc'+(i===cur?' cur':'')+'" data-go="'+i+'"><span class="u">'+(u.sourceRange?'SLIDES '+u.sourceRange:(u.k==='TITLE'?'START':u.k==='END'?'FINISH':u.k))+'</span><span class="t">'+T(u.title||LECTURE.title)+'</span></button>'})});var g=document.getElementById('oG');g.innerHTML=h;g.onclick=function(e){var b=e.target.closest('[data-go]');if(b){go(+b.dataset.go,true);closeOv('over')}};document.getElementById('oSub').textContent=core.length+' classroom units · source coverage stays visible · no topic becomes optional merely because it is studied after class.';};
var top=document.createElement('nav');top.className='lp-top';top.setAttribute('aria-label','Chapter learning paths');top.innerHTML='<a class="lp-brand" href="../../iscarb.html">iSCARB / CPIT-455 <span style="font-weight:400">/ CH '+ch+'</span></a><div class="lp-topnav"><button data-route-tab="core">Classroom</button><button data-route-tab="study">Required self-study</button><button data-route-tab="toolkit">iSCARB toolkit</button><a href="../../fbr-submission.html?chapter='+ch+'">Assignment '+LECTURE.path.assignment+'</a></div>';document.getElementById('stage').prepend(top);
top.addEventListener('click',function(e){var b=e.target.closest('[data-route-tab]');if(!b)return;var k=b.dataset.routeTab;if(k==='core')jump('START');else if(k==='study')jump('READING');else jump('R07')});
var zoom=document.createElement('div');zoom.className='lp-zoom';zoom.innerHTML='<button type="button" aria-label="Decrease text size">A−</button><button type="button" aria-label="Increase text size">A+</button>';document.getElementById('lectureControls').appendChild(zoom);zoom.children[0].onclick=function(){setZoom(Math.max(1,ZOOM-.1))};zoom.children[1].onclick=function(){setZoom(Math.min(1.5,ZOOM+.1))};
U.forEach(function(u,i){var slide=deck.querySelector('[data-i="'+i+'"]');var ribbon=document.createElement('div');ribbon.className='lp-ribbon '+u.route;ribbon.innerHTML='<strong>'+(u.route==='core'?'CLASSROOM':u.route==='study'?'SOURCE REVIEW · REQUIRED':'ISCARB TOOLKIT')+'</strong><span>'+(u.sourceRange?'Supplied source slides '+u.sourceRange: (u.route==='toolkit'?'Course practice / extension':u.k==='TITLE'?'Original chapter + applied reasoning':'Course learning activity'))+'</span>';slide.querySelector('.fit').prepend(ribbon);var c=slide.querySelector('.count');if(c)c.textContent=u.route==='core'?(core.indexOf(u)+1)+' / '+core.length:u.route==='study'?'Source review':'Toolkit';});
var end=deck.querySelector('[data-i="'+byKey('END')+'"] .area');end.innerHTML='<h2 style="font:700 34px/1.3 system-ui">Before the assignment</h2><p style="font:18px/1.6 system-ui">Explain each item without looking. These checks record your judgment on this device; they do not certify mastery or submit work.</p><div class="lp-readiness">'+LECTURE.path.exit.map(function(t,i){return'<label><input type="checkbox" data-selfcheck="'+i+'">'+t+'</label>'}).join('')+'</div><div class="lp-actions"><button class="lp-btn" data-jump="READING">Required reading</button><button class="lp-btn" data-jump="PREP">Check all five objectives</button><button class="lp-btn" data-jump="C01">Review source coverage</button><button class="lp-btn" data-jump="J02">Practice questions</button><a class="lp-btn" href="../../fbr-submission.html?chapter='+ch+'">Open Assignment '+LECTURE.path.assignment+'</a></div><p style="font:17px/1.6 system-ui">Save or export your decision card. Submit assessed work through the LMS.</p>';
document.querySelectorAll('[data-selfcheck]').forEach(function(el){var key=KEY+'-selfcheck-'+el.dataset.selfcheck;try{el.checked=localStorage.getItem(key)==='1'}catch(e){}el.addEventListener('change',function(){try{localStorage.setItem(key,el.checked?'1':'0')}catch(e){note('Self-check could not be saved.')}})});
document.addEventListener('click',function(e){var b=e.target.closest('[data-jump]');if(b){e.preventDefault();jump(b.dataset.jump)}});
var titleSlide=deck.querySelector('[data-i="0"] .area'),start=document.createElement('div');start.className='lp-actions';start.innerHTML='<button class="lp-btn" data-jump="START">Start the learning path</button><button class="lp-btn" id="lpResume">Resume last unit</button>';titleSlide.appendChild(start);document.getElementById('lpResume').onclick=function(){try{jump(localStorage.getItem(KEY+'-resume-at-open')||'START')}catch(e){jump('START')}};
// Preserve the pre-open location before first navigation writes the current unit.
var requested=location.hash.slice(1),last='';try{last=localStorage.getItem(KEY+'-last-unit-v20260921')||'';localStorage.setItem(KEY+'-resume-at-open',last)}catch(e){}
var ri=byKey(requested);go(ri>=0?ri:0,true);fit();renderProgress();
// Source provenance never equates citation counts with learning or verification.
renderCoverage=function(){};
document.getElementById('readyChip').title='Readiness self-check';
})();
