from __future__ import annotations

from pathlib import Path

from pptx.dml.color import RGBColor

from .models import Blueprint
from . import visual_engine as ve

# High-contrast, ZTM-inspired energy applied to ISCARB's own visual grammar.
# This is an original ISCARB theme: no ZTM logos, assets, CSS or proprietary artwork.
INK = RGBColor(23, 21, 31)
MUTED = RGBColor(105, 100, 116)
PAPER = RGBColor(252, 252, 254)
WHITE = RGBColor(255, 255, 255)
LINE = RGBColor(232, 230, 238)
PINK = RGBColor(239, 23, 103)
PURPLE = RGBColor(110, 73, 255)
MINT = RGBColor(56, 226, 163)
BLUE = RGBColor(61, 125, 255)
AMBER = RGBColor(245, 165, 36)
RED = RGBColor(217, 74, 89)
SOFT_PINK = RGBColor(255, 232, 241)
SOFT_PURPLE = RGBColor(242, 238, 255)
SOFT_MINT = RGBColor(232, 255, 246)
SOFT_BLUE = RGBColor(236, 243, 255)
SOFT_AMBER = RGBColor(255, 247, 226)
SOFT_RED = RGBColor(255, 238, 241)


def _apply_theme() -> None:
    ve.INK = INK
    ve.MUTED = MUTED
    ve.PAPER = PAPER
    ve.WHITE = WHITE
    ve.LINE = LINE
    ve.BLUE = PURPLE
    ve.GREEN = MINT
    ve.AMBER = AMBER
    ve.VIOLET = PINK
    ve.RED = RED
    ve.SOFT_BLUE = SOFT_PURPLE
    ve.SOFT_GREEN = SOFT_MINT
    ve.SOFT_AMBER = SOFT_AMBER
    ve.SOFT_VIOLET = SOFT_PINK
    ve.SOFT_RED = SOFT_RED
    ve.PHASE_COLOR = {
        "IFHAM": PURPLE,
        "MARIS": MINT,
        "ATQAN": BLUE,
        "MAYYIZ": PINK,
    }
    ve.PHASE_SOFT = {
        "IFHAM": SOFT_PURPLE,
        "MARIS": SOFT_MINT,
        "ATQAN": SOFT_BLUE,
        "MAYYIZ": SOFT_PINK,
    }


def export_faculty_presenter_pptx(blueprint: Blueprint, path: Path) -> Path:
    _apply_theme()
    return ve.export_presenter_pptx(blueprint, Path(path))


def render_faculty_presenter_preview(blueprint: Blueprint, release_state: str = "BLOCKED") -> str:
    _apply_theme()
    html = ve.render_presenter_preview(blueprint, release_state)
    # The preview renderer contains its own local CSS. Re-theme only presentation
    # chrome and colors; structure/content remain generated by Visual Grammar.
    replacements = {
        "#0d141d": "#17182d",
        "#111b26": "#ffffff",
        "#273444": "#e8e6ee",
        "#9fb0c0": "#6f6b78",
        "#172330": "#f7f5fb",
        "#cdd7e0": "#17151f",
        "#263647": "#e3dfee",
        "#6f8ff7": "#ef1767",
        "#1c2d45": "#fff0f6",
        "#90a3b5": "#7b7584",
        "#f7f9fb": "#fcfcfe",
        "#3568e8": "#6e49ff",
        "#16856b": "#38e2a3",
        "#b77b1d": "#f5a524",
        "#7955dc": "#ef1767",
        "#b64040": "#d94a59",
    }
    for old, new in replacements.items():
        html = html.replace(old, new)
    return html
