from __future__ import annotations

"""v7.3.0 - ZTM is a skin, never a lecture re-author.

Pipeline invariant:
    Golden lecture -> render complete physical slides -> apply ZTM skin only.

No title, paragraph, figure, source expansion, timebox, micro-case, or slide order
is regenerated by the ZTM layer. Large bright source/chart panels are detected
and protected as intact rectangles before recolouring the surrounding Golden UI.
PDF, PPTX and HTML preview all consume the same skinned slide snapshots.
"""

import base64
import html
import importlib.util
import io
import math
import re
import sys
import tempfile
from functools import lru_cache
from pathlib import Path

import fitz
from PIL import Image
from pptx import Presentation
from pptx.util import Inches

from . import start_v440 as base
from . import start_v670_prod as prod
from . import v670_contract as contract

BG_BASE = "#FFFFFF"
BG_SURFACE = "#F8FAFC"
TEXT_HEADING = "#0F172A"
TEXT_BODY = "#475569"
ACCENT_PRIMARY = "#4F46E5"
ACCENT_CYAN = "#06B6D4"
ALERT_URGENT = "#F43F5E"
BORDER = "#E2E8F0"
ACCENT_GOLD = "#D97706"
ACCENT_GREEN = "#059669"
ACCENT_BLUE = "#2563EB"

_PATCHED = False
_GOLDEN = None


def _rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


WHITE = _rgb(BG_BASE)
HEADING = _rgb(TEXT_HEADING)
PRIMARY = _rgb(ACCENT_PRIMARY)
CYAN = _rgb(ACCENT_CYAN)
ROSE = _rgb(ALERT_URGENT)
GOLD = _rgb(ACCENT_GOLD)
GREEN = _rgb(ACCENT_GREEN)
BLUE = _rgb(ACCENT_BLUE)
FRAME = _rgb(BORDER)


class ZTMSkinTokens:
    bg = BG_BASE
    panel = BG_SURFACE
    panel_soft = BG_SURFACE
    text = TEXT_HEADING
    muted = TEXT_BODY
    cyan = ACCENT_CYAN
    magenta = ACCENT_PRIMARY
    gold = ACCENT_GOLD
    green = ACCENT_GREEN
    blue = ACCENT_BLUE
    danger = ALERT_URGENT
    footer_bg = BG_SURFACE
    primary = ACCENT_PRIMARY
    secondary = ACCENT_CYAN
    heritage = ACCENT_GOLD

    def model_dump(self):
        return {
            "bg": self.bg, "panel": self.panel, "panel_soft": self.panel_soft,
            "text": self.text, "muted": self.muted, "cyan": self.cyan,
            "magenta": self.magenta, "gold": self.gold, "green": self.green,
            "blue": self.blue, "danger": self.danger, "footer_bg": self.footer_bg,
            "primary": self.primary, "secondary": self.secondary, "heritage": self.heritage,
        }

    def css_variables(self):
        out = {
            "--bg-base": BG_BASE,
            "--bg-surface": BG_SURFACE,
            "--text-heading": TEXT_HEADING,
            "--text-body": TEXT_BODY,
            "--accent-primary": ACCENT_PRIMARY,
            "--accent-cyan": ACCENT_CYAN,
            "--alert-urgent": ALERT_URGENT,
        }
        out.update({f"--iscarb-{k.replace('_','-')}": v for k, v in self.model_dump().items()})
        return out

    @staticmethod
    def _lum(h):
        vals = []
        for i in (1, 3, 5):
            c = int(h[i:i+2], 16) / 255
            vals.append(c/12.92 if c <= .04045 else ((c+.055)/1.055)**2.4)
        return .2126*vals[0] + .7152*vals[1] + .0722*vals[2]

    @classmethod
    def _ratio(cls, a, b):
        x, y = cls._lum(a), cls._lum(b)
        return (max(x, y)+.05)/(min(x, y)+.05)

    def contrast_checks(self):
        return {
            "heading_on_base": self._ratio(TEXT_HEADING, BG_BASE) >= 4.5,
            "body_on_base": self._ratio(TEXT_BODY, BG_BASE) >= 4.5,
            "primary_large_on_base": self._ratio(ACCENT_PRIMARY, BG_BASE) >= 3.0,
            "urgent_large_on_base": self._ratio(ALERT_URGENT, BG_BASE) >= 3.0,
        }


def chapter_design_tokens(*_args, **_kwargs):
    return ZTMSkinTokens()


def _load_golden_renderer():
    """Load an untouched copy of presenter_v67_prod after Golden pedagogical patches.

    The active presenter module may have been monkey-patched by older visual
    experiments. Loading the same source under a fresh package-qualified module
    name gives this skin stage the original Golden renderer while still seeing
    the currently patched contract / blueprint content.
    """
    global _GOLDEN
    if _GOLDEN is not None:
        return _GOLDEN
    path = Path(__file__).with_name("presenter_v67_prod.py")
    name = "app._presenter_v67_golden_skin_source"
    if name in sys.modules:
        _GOLDEN = sys.modules[name]
        return _GOLDEN
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Could not load Golden presenter source")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    _GOLDEN = mod
    return mod


def _cell_brightness(px) -> int:
    r, g, b = px
    return int(.2126*r + .7152*g + .0722*b)


def _protected_bright_rects(img: Image.Image):
    """Find large bright chart/source panels; return full-res rectangles.

    Detection runs on a 96x54 thumbnail. We protect the full bounding rectangle,
    not just white pixels, so labels, axes and dark lines inside a source figure
    are never recoloured or destroyed.
    """
    w, h = img.size
    sw, sh = 96, 54
    small = img.resize((sw, sh), Image.Resampling.BILINEAR).convert("RGB")
    data = list(small.getdata())
    bright = [False] * (sw*sh)
    for i, px in enumerate(data):
        mx, mn = max(px), min(px)
        sat = 0 if mx == 0 else (mx-mn)/mx
        bright[i] = _cell_brightness(px) > 215 and sat < .23
    seen = [False] * len(bright)
    rects = []
    for start, on in enumerate(bright):
        if not on or seen[start]:
            continue
        stack = [start]; seen[start] = True; cells = []
        while stack:
            j = stack.pop(); cells.append(j); y, x = divmod(j, sw)
            for nx, ny in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
                if 0 <= nx < sw and 0 <= ny < sh:
                    k = ny*sw+nx
                    if bright[k] and not seen[k]:
                        seen[k] = True; stack.append(k)
        if len(cells) < int(.025*sw*sh):
            continue
        xs = [c % sw for c in cells]; ys = [c // sw for c in cells]
        x0, x1, y0, y1 = min(xs), max(xs)+1, min(ys), max(ys)+1
        if (x1-x0) < .18*sw or (y1-y0) < .18*sh:
            continue
        if x0 <= 0 or y0 <= 0 or x1 >= sw or y1 >= sh:
            continue
        # Reject white-text-on-dark blocks: true figure panels are bright overall.
        total = 0; count = 0
        for yy in range(y0, y1):
            for xx in range(x0, x1):
                total += _cell_brightness(data[yy*sw+xx]); count += 1
        if count and total/count < 175:
            continue
        pad = 5
        fx0 = max(0, math.floor(x0*w/sw)-pad)
        fy0 = max(0, math.floor(y0*h/sh)-pad)
        fx1 = min(w, math.ceil(x1*w/sw)+pad)
        fy1 = min(h, math.ceil(y1*h/sh)+pad)
        rects.append((fx0, fy0, fx1, fy1))
    return rects


def _hue_target(r, g, b, urgent=False):
    mx, mn = max(r,g,b), min(r,g,b)
    if mx == mn:
        return PRIMARY
    d = mx-mn
    if mx == r:
        h = (60*((g-b)/d)+360) % 360
    elif mx == g:
        h = 60*((b-r)/d+2)
    else:
        h = 60*((r-g)/d+4)
    if h < 24 or h >= 290:
        return ROSE if urgent else PRIMARY
    if h < 76:
        return GOLD
    if h < 156:
        return GREEN
    if h < 210:
        return CYAN
    if h < 290:
        return BLUE
    return PRIMARY


@lru_cache(maxsize=32768)
def _map_pixel_normal(px):
    r, g, b = px
    mx, mn = max(px), min(px)
    v = mx/255 if mx else 0
    s = 0 if mx == 0 else (mx-mn)/mx
    if s < .18:
        t = min(1, max(0, (v-.02)/.98))
        return tuple(round((1-t)*WHITE[i] + t*HEADING[i]) for i in range(3))
    if v < .18:
        return WHITE
    target = _hue_target(r,g,b,False)
    strength = min(1, max(0, .20 + .80*s*v))
    return tuple(round((1-strength)*WHITE[i] + strength*target[i]) for i in range(3))


@lru_cache(maxsize=32768)
def _map_pixel_urgent(px):
    r, g, b = px
    mx, mn = max(px), min(px)
    v = mx/255 if mx else 0
    s = 0 if mx == 0 else (mx-mn)/mx
    if s < .18:
        t = min(1, max(0, (v-.02)/.98))
        return tuple(round((1-t)*WHITE[i] + t*HEADING[i]) for i in range(3))
    if v < .18:
        return WHITE
    target = _hue_target(r,g,b,True)
    strength = min(1, max(0, .20 + .80*s*v))
    return tuple(round((1-strength)*WHITE[i] + strength*target[i]) for i in range(3))


def _map_crop(crop: Image.Image, urgent=False):
    fn = _map_pixel_urgent if urgent else _map_pixel_normal
    out = Image.new("RGB", crop.size)
    out.putdata([fn(px) for px in crop.convert("RGB").getdata()])
    return out


def _skin_image(img: Image.Image, page_number: int):
    img = img.convert("RGB")
    w, h = img.size
    rects = _protected_bright_rects(img)
    cut = int(.82*h)
    if page_number == 2:
        skinned = _map_crop(img, urgent=True)
    else:
        skinned = Image.new("RGB", (w,h), WHITE)
        skinned.paste(_map_crop(img.crop((0,0,w,cut)), urgent=False), (0,0))
        skinned.paste(_map_crop(img.crop((0,cut,w,h)), urgent=True), (0,cut))
    for box in rects:
        skinned.paste(img.crop(box), box[:2])
    # Quiet ZTM frame; geometry/content remain untouched.
    p = skinned.load()
    for x in range(w):
        p[x,0] = FRAME; p[x,h-1] = FRAME
    for y in range(h):
        p[0,y] = FRAME; p[w-1,y] = FRAME
    return skinned


def _golden_pdf(bp, source_root=None, release_state="REVIEW"):
    golden = _load_golden_renderer()
    temp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    temp.close()
    path = Path(temp.name)
    golden.export_presenter_pdf(bp, path, source_root=source_root, release_state=release_state)
    return path


def _skin_pages(bp, source_root=None, release_state="REVIEW", scale=1.25):
    src = _golden_pdf(bp, source_root, release_state)
    images = []
    try:
        doc = fitz.open(src)
        try:
            for i, page in enumerate(doc, 1):
                pix = page.get_pixmap(matrix=fitz.Matrix(scale, scale), alpha=False)
                img = Image.open(io.BytesIO(pix.tobytes("png"))).convert("RGB")
                images.append(_skin_image(img, i))
        finally:
            doc.close()
    finally:
        src.unlink(missing_ok=True)
    return images


def export_presenter_pdf_skin(bp, out: Path, source_root=None, release_state="REVIEW"):
    pages = _skin_pages(bp, source_root, release_state)
    doc = fitz.open()
    try:
        for img in pages:
            buf = io.BytesIO(); img.save(buf, format="PNG", optimize=True)
            page = doc.new_page(width=960, height=540)
            page.insert_image(page.rect, stream=buf.getvalue(), keep_proportion=False)
        doc.set_metadata({
            "title": f"{getattr(bp,'lecture_title','ISCARB')} - Golden + ZTM skin only",
            "subject": "Content-preserving ZTM post-render skin; source figures retained intact",
            "author": "ISCARB",
        })
        doc.save(out, deflate=True, garbage=4)
    finally:
        doc.close()
    return out


def export_presenter_pptx_skin(bp, out: Path, source_root=None, release_state="REVIEW"):
    pages = _skin_pages(bp, source_root, release_state)
    prs = Presentation()
    prs.slide_width = Inches(13.333333)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]
    for img in pages:
        buf = io.BytesIO(); img.save(buf, format="PNG", optimize=True); buf.seek(0)
        slide = prs.slides.add_slide(blank)
        slide.shapes.add_picture(buf, 0, 0, width=prs.slide_width, height=prs.slide_height)
    prs.core_properties.title = f"{getattr(bp,'lecture_title','ISCARB')} - Golden + ZTM skin only"
    prs.core_properties.subject = "Style-only transformation; content and source figures preserved"
    prs.save(out)
    return out


def render_presenter_preview_skin(bp, release_state="REVIEW", source_root=None):
    pages = _skin_pages(bp, source_root, release_state, scale=1.0)
    sections = []
    for i, img in enumerate(pages, 1):
        buf = io.BytesIO(); img.save(buf, format="JPEG", quality=88, optimize=True)
        data = base64.b64encode(buf.getvalue()).decode("ascii")
        sections.append(
            f"<section class='slide'><img alt='slide {i}' src='data:image/jpeg;base64,{data}'></section>"
        )
    title = html.escape(getattr(bp, "lecture_title", "ISCARB"))
    return f"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>{title}</title><style>
body{{margin:0;background:#E2E8F0;font-family:Inter,Arial,sans-serif}}main{{padding:20px}}
.slide{{width:min(1280px,96vw);aspect-ratio:16/9;margin:0 auto 24px;background:#fff;border-radius:14px;overflow:hidden;box-shadow:0 14px 32px rgba(15,23,42,.10)}}
.slide img{{display:block;width:100%;height:100%;object-fit:contain}}
@media print{{body{{background:white}}main{{padding:0}}.slide{{margin:0;border-radius:0;box-shadow:none;break-after:page}}@page{{size:16in 9in;margin:0}}}}
</style></head><body><main>{''.join(sections)}</main></body></html>"""


def apply_v730_ztm_skin_only_patch(app):
    global _PATCHED
    if _PATCHED:
        return
    _PATCHED = True

    # Force-load now so deployment fails early if the Golden renderer cannot be
    # isolated. This is a release gate, not a runtime surprise.
    _load_golden_renderer()

    contract.chapter_design_tokens = chapter_design_tokens
    prod.chapter_design_tokens = chapter_design_tokens

    # The existing FastAPI route resolves these globals at request time.
    base.export_presenter_pdf = export_presenter_pdf_skin
    base.export_presenter_pptx = export_presenter_pptx_skin
    base.render_presenter_preview = render_presenter_preview_skin

    previous_health = base._health_v440
    def health():
        data = dict(previous_health())
        data.update({
            "version": "7.3.0",
            "ztm_theme_version": "v7.3.0-skin-only",
            "ztm_pipeline": "Golden lecture first -> ZTM post-render skin second",
            "ztm_content_rewrite": False,
            "ztm_slide_reflow": False,
            "source_figure_policy": "Large bright source/chart panels are protected as intact rectangles; ZTM never redraws or replaces them.",
            "source_figure_gate": "A ZTM skin may recolour surrounding UI but must preserve protected figure rectangles pixel-for-pixel.",
            "pptx_mode": "Portable snapshot deck: every complete Golden physical slide is preserved as a skinned full-slide image.",
            "html_mode": "Complete skinned Golden slide snapshots; no semantic re-authoring or progressive disclosure reflow.",
            "ztm_tokens": {
                "bg_base": BG_BASE, "bg_surface": BG_SURFACE,
                "text_heading": TEXT_HEADING, "text_body": TEXT_BODY,
                "accent_primary": ACCENT_PRIMARY, "accent_cyan": ACCENT_CYAN,
                "alert_urgent": ALERT_URGENT,
            },
        })
        return data
    base._health_v440 = health
    base.engine.health = health
