from __future__ import annotations

"""ISCARB v8.1 prompt policy for licensed public visuals.

The LLM supplies the semantic brief through fields that already exist in the
Blueprint schema: visual_plan.visual_type, visual_plan.focal_elements,
visual_plan.teaching_purpose and visual_suggestion. Runtime search converts that
brief into 3-5 provider queries and performs licensing/quality/diversity gates.
"""

PUBLIC_VISUAL_PROMPT_ADDENDUM = r"""

15. LICENSED PUBLIC VISUAL INTELLIGENCE — HARD
P1 remains the first visual authority. External/public imagery is allowed ONLY when no suitable P1 figure/table/diagram/photo exists for the Unit and the image performs a genuine cognitive job.

For EVERY Unit, make visual_plan explicit enough for runtime search:
- visual_plan.visual_type: when an external visual would be useful, use exactly one of metaphorical / technical / real-world / conceptual. When P1 already provides the needed visual, keep the source-native visual type instead.
- visual_plan.focal_elements: 3-8 concise semantic search keywords/objects/relations. These are search concepts, not invented technical claims.
- visual_plan.teaching_purpose: say what the learner must OBSERVE / LOCATE / COMPARE / ANNOTATE in the image and how that changes the engineering decision.
- visual_suggestion: one concise visual search brief that names the scene/structure needed without naming a copyrighted work unless that exact work is supplied in P1.

PUBLIC IMAGE RULES
- Never choose a public image merely because a Unit is text-heavy. It must support interpretation, transfer, comparison, or decision evidence.
- Never present a stock/public image as P1 evidence. Label it External licensed visual / contextual enrichment.
- Never invent a license. Runtime provider metadata is authoritative for attribution.
- Do not claim Unsplash, Pexels or Pixabay content is CC0 unless provider metadata explicitly says CC0. Their platform licenses are distinct.
- Do not imply endorsement by a photographed person, brand, institution, or product.
- Prefer imagery without visible logos, watermarks, or identifiable people when the pedagogical point does not require them.
- Public imagery may contextualize a source-backed claim; it may not create a new technical fact.
- If no sufficiently relevant and reusable image clears the runtime gate, accept an explicit no-image/icon fallback rather than inserting a weak or legally ambiguous image.
- If an AI-generated visual is used by a configured downstream provider, label it Generated by AI for educational purposes and never attribute it to P1.

QUERY INTENT EXAMPLES
- quotation / abstract tension -> metaphorical
- architecture / mechanism / interface / AI-security workflow -> technical
- hospital / control room / field deployment / operations -> real-world
- abstract relationship / trust / uncertainty / accountability -> conceptual
"""


def apply_v810_visual_prompt_patch() -> None:
    from . import prompts
    from . import gemini_service
    if PUBLIC_VISUAL_PROMPT_ADDENDUM.strip() not in prompts.MASTER_PROMPT:
        prompts.MASTER_PROMPT = prompts.MASTER_PROMPT.rstrip() + PUBLIC_VISUAL_PROMPT_ADDENDUM
    if PUBLIC_VISUAL_PROMPT_ADDENDUM.strip() not in gemini_service.MASTER_PROMPT:
        gemini_service.MASTER_PROMPT = gemini_service.MASTER_PROMPT.rstrip() + PUBLIC_VISUAL_PROMPT_ADDENDUM
