PAPER_URL = "https://zenodo.org/records/22964248"
PAPER_TITLE = "From Answer Production to Defensible Engineering Judgment in AI-Containing Systems: The iSCARB Framework and a Nine-Chapter Software Engineering Implementation"
VERSION = "ai-only-v3"
DATA = {
10: dict(
 assignment=1, max_points=4, title="AI Dependability: decide what the assistant may control",
 artifact="AI dependability claim + bounded operating decision",
 warm="An AI operations assistant always returns an answer. Is that enough to call the service dependable?",
 warmanswer="No. Availability of an answer is not correctness, integrity or safe decision support. A dependable claim needs the relevant property, operating conditions and evidence.",
 scenario="A fictional university uses a generative-AI operations assistant during course registration. It recommends CONTINUE, FAILOVER or HOLD. Two application servers are redundant, but both call the same model, prompt template and retrieval service. A quiet-period server failover test passed; no peak-load test covers AI outage, contradictory recommendations or a wrong recommendation. Operators can ignore the assistant, but the current procedure does not require an independent check before acting. Decide whether the assistant may control the action, remain advisory-only, or be disabled for the peak window.",
 fit="Identify the dependability property or properties that govern the AI-assisted decision and explain the shared/common-cause dependency.",
 artifact_prompt="Explain one AI-specific failure mechanism and one engineering control that does not rely on the model being correct.",
 bound="State the model/version, operating profile and human-check conditions under which your claim holds, plus one trigger that reopens the decision.",
 act="Choose CONTROL, ADVISORY-ONLY or DISABLE. Name the accountable owner and the inspectable evidence required before widening the boundary.",
 stress="After Part A is committed, two identical incident summaries sent to the same model version produce opposite failover recommendations. Both application servers would consume the same assistant path. No transaction loss has been confirmed. Reassess the shared dependency and the permitted role of the assistant.",
 refit="Explain what the contradictory AI output does to the original boundary, then defend RETAIN, REVISE or REPLACE.",
 example_weak="Use a backup model and test more.",
 example_strong="Keep the assistant advisory-only. Two servers do not remove the shared model/prompt dependency. Before any control authority, run versioned repeatability and AI-unavailable tests under peak-like load, require an independent rule/human check, and record the owner and rollback trigger."
),
11: dict(
 assignment=2, max_points=5, title="AI Reliability: compute before you trust",
 artifact="Metric + denominator + operating-profile decision",
 warm="A classifier reports 97% accuracy. Does that establish reliable phishing protection?",
 warmanswer="No. Accuracy can hide the failure mode that matters. For protection, compute missed-phishing probability per phishing demand and state the exposure and profile.",
 scenario="A fictional email gateway pilots an AI phishing classifier on 1,000 messages: 50 are phishing. It catches 40 phishing messages, misses 10, flags 19 legitimate messages as phishing and correctly passes 931 legitimate messages. The vendor advertises 98% accuracy. The pilot traffic is 10% external and the deployed model version is fixed for the trial. Decide whether the evidence supports a protection claim and what operating decision is justified.",
 fit="State which reliability measure supports the protection claim and why overall accuracy is insufficient by itself.",
 artifact_prompt="Compute accuracy, phishing POFOD and false-alarm rate. Show numerator, denominator and exposure; do not hide uncertainty behind a single percentage.",
 bound="State the model version, traffic profile and exposure for which your estimate applies and a trigger for re-estimation.",
 act="Choose LIMITED PILOT, ADVISORY-ONLY or HOLD. Name the owner and the next representative evidence needed.",
 stress="After Part A is committed, the security team says external traffic will rise from 10% to 60% next week, but no new labeled sample has been collected. The model is unchanged. Reassess whether the pilot estimate supports the new operating profile.",
 refit="Explain how the profile shift affects the original estimate and defend RETAIN, REVISE or REPLACE.",
 example_weak="Accuracy is 97.1%, so the model is reliable.",
 example_strong="Accuracy is 971/1000 = 97.1%, but phishing POFOD is 10/50 = 0.20 and false-alarm rate is 19/950 = 0.02. A protection claim must use the phishing-demand denominator and state that it is based on only 50 phishing demands in this pilot profile."
),12: dict(
 assignment=3, max_points=5, title="AI Safety: write the missing control",
 artifact="Hazard → safety requirement → independent checker → verification",
 warm="Every AI-proposed command is individually within its allowed limit. Does that establish safe cumulative behavior?",
 warmanswer="No. A sequence of individually acceptable actions can violate a cumulative safety constraint. The safety property must be enforced outside the model.",
 scenario="A fictional laboratory uses an AI optimiser to propose actuator commands. The controller rejects any single command above 10 units. During a trial the AI proposes six 10-unit commands within one minute; every command passes the current check, but the modeled cumulative safe limit for that minute is 50 units. The current requirements contain no cumulative-window rule. Decide whether the AI path can remain enabled and what safety control is required.",
 fit="Name the hazard, possible accident and affected party. Distinguish the unsafe requirement gap from an ordinary model-quality problem.",
 artifact_prompt="Write the missing safety requirement, place an independent checker, and specify one verification sequence that would expose the cumulative hazard.",
 bound="State the sensing, window and enforcement assumptions required for the checker to be trusted, plus a condition that forces a safe state.",
 act="Choose ENABLE WITH CONTROL, RESTRICT or HOLD. Name the safety owner/reviewer and the evidence required before operation.",
 stress="After Part A is committed, a log shows the cumulative checker receives zero when the position sensor drops out for two seconds, so the next AI command can pass using an incorrect total. No accident occurred in this teaching case. Reassess the fail-safe requirement.",
 refit="Identify the broken safety assumption and defend the final control, degraded state and verification evidence.",
 example_weak="Tell the AI not to exceed the safe limit.",
 example_strong="Enforce the cumulative limit in an independent controller: reject any command that would take the one-minute total above 50 units, regardless of source. On lost sensing, enter a defined safe state. Verify sequences of many small commands and sensor-loss cases; record the tested version and reviewer."
),
13: dict(
 assignment=4, max_points=5, title="AI Security: permission-aware RAG, not prompt promises",
 artifact="Threat → server-side control → negative test",
 warm="A system prompt says 'never reveal another student's file.' Is that an access-control boundary?",
 warmanswer="No. A prompt is an instruction to a model, not deterministic authorization. Enforce permissions before retrieval and test forbidden requests.",
 scenario="A fictional university RAG assistant answers questions over student project files. The model prompt says it must reveal only files the requester is allowed to see. Retrieval currently uses one broad service account that can read every project. The UI hides other students' file links, and ordinary same-user questions work. No cross-user retrieval test exists. Decide whether the assistant may be released, restricted, or held.",
 fit="Identify the protected asset, actor/threat and the AI-specific vulnerability. Keep prompt injection distinct from authorization failure.",
 artifact_prompt="Write one allowed and one forbidden retrieval test with actor, object, expected server result and evidence to inspect.",
 bound="State which actors, document stores and retrieval paths the claim covers, plus one untested path that reopens the decision.",
 act="Choose RELEASE, RESTRICT or HOLD. Name the server-side authorization control, reviewer and evidence needed.",
 stress="After Part A is committed, refusal tests still look good, but a synthetic cross-user request sent directly to the retrieval endpoint returns another student's document before the model sees it. Reassess the security claim.",
 refit="Explain why model refusal evidence cannot repair the retrieval breach and defend the final control and retest scope.",
 example_weak="Improve the system prompt and add more refusal examples.",
 example_strong="Enforce permission-aware retrieval before documents reach the model. Test Student A requesting A's file (allow) and Student A requesting B's file through both preview and export paths (deny). Model refusals remain a secondary defense, not the authorization boundary."
),14: dict(
 assignment=5, max_points=5, title="AI Resilience: recover when the assistant is gone",
 artifact="Essential service → AI-independent degraded mode → recovery rehearsal",
 warm="A recovery assistant works during normal operation. Does that prove the service is resilient to losing the assistant?",
 warmanswer="No. The fallback must remain usable when the AI and its dependencies are unavailable.",
 scenario="A fictional campus operations desk uses an AI recovery assistant to guide staff during major service outages. The assistant retrieves the current runbook from the network and proposes the next recovery step. A printed one-page fallback exists, but it covers only the first two steps and assumes staff can sign in to the central identity service. No rehearsal has been run with the AI unavailable. Decide whether the AI-assisted recovery path is ready for a limited trial.",
 fit="Name the essential service and the critical dependencies introduced by the AI assistant. Separate normal convenience from recovery necessity.",
 artifact_prompt="Describe recognition, degraded operation, recovery and reinstatement with the AI unavailable. Include a rehearsal that proves the fallback works.",
 bound="State the maximum dependency/staleness assumptions that keep the fallback usable and one condition that makes it unacceptable.",
 act="Choose TRIAL, RESTRICTED TRIAL or HOLD. Name the recovery owner and the evidence that must exist before widening use.",
 stress="After Part A is committed, a rehearsal shows the central identity service is unavailable in the same outage, so staff cannot open the protected fallback file or the AI assistant. Reassess the common dependency.",
 refit="Explain how the shared dependency changes the recovery path and defend the final degraded mode and rehearsal evidence.",
 example_weak="Keep a backup AI model.",
 example_strong="Keep the AI off the critical recovery path. Maintain a versioned offline runbook, bounded emergency authority, a second trained person and a rehearsed degraded mode. Test the exact case where both AI and central identity are unavailable, then reconcile actions after recovery."
),
15: dict(
 assignment=6, max_points=5, title="AI Reuse: hosted model or local model?",
 artifact="Reuse options → lifecycle/data constraints → evidence-based choice",
 warm="A hosted model is faster to integrate. Does that make it the better reuse choice for the system lifetime?",
 warmanswer="No. Version retirement, data terms, operations expertise and exit cost can dominate the initial schedule advantage.",
 scenario="A fictional faculty is building an AI room-booking assistant for a three-year pilot. Option A is a hosted model API that can be integrated in days; prompts and booking text leave the university boundary, and the supplier may retire model versions. Option B is a locally hosted open model; deployment takes longer and needs model-operations expertise, but data and versions remain under university control. Both options passed the same ten-request demonstration. No representative evaluation set or total lifecycle cost is available. Recommend an option, a bounded evaluation, or a hold.",
 fit="Classify the reuse choices and identify the functional, data, lifetime and expertise constraints that matter.",
 artifact_prompt="Compare hosted and local options across at least four relevant factors. Mark each fact SUPPORTED, UNKNOWN or CONDITION-DEPENDENT; do not invent scores.",
 bound="State one lifecycle or data assumption that must hold and one change that would reverse the recommendation.",
 act="Choose HOSTED, LOCAL, BOUNDED EVALUATION or HOLD. Name the owner and the evidence needed to settle the most consequential unknown.",
 stress="After Part A is committed, the hosted provider announces that the tested model version will be retired in 60 days. A replacement version is available, but no regression result exists for the booking workflow. Reassess reuse risk and evidence.",
 refit="Update only the affected assumptions and defend the final choice, migration/exit plan and evaluation evidence.",
 example_weak="Use the hosted model because it is easier.",
 example_strong="Hosted wins on schedule, but the three-year lifetime and data boundary are material. Treat version retirement as an interface change: require a workflow evaluation set, version pinning where possible, an exit path and regression evidence before each model migration."
),16: dict(
 assignment=7, max_points=5, title="AI Component Contract: say what every call must mean",
 artifact="AI interface → pre/postconditions → versioned quality evidence",
 warm="An AI service accepts a numeric temperature and returns a forecast. Does the method signature establish the unit or the approved model version?",
 warmanswer="No. Units, valid ranges, model-version obligations and error behavior belong in the contract; quality over many calls needs separate evaluation evidence.",
 scenario="A fictional scheduling component calls an AI forecast service with temperature values. The caller sends Celsius. The provider accepts any number and returns a forecast plus a modelVersion field. The approved integration requires -40 ≤ temperatureC ≤ 60 and modelVersion = 'approved-v7'. A sample call at 30 returns a plausible forecast, but no adapter currently checks units, range or version. Forecast quality is specified separately as a maximum mean error on held-out data. Decide whether to use, adapt or hold the component.",
 fit="Separate syntactic compatibility from semantic and model-version obligations. Name one caller obligation and one provider obligation.",
 artifact_prompt="Write a precondition, postcondition and adapter check for unit/range/version. Also state which quality requirement cannot be proven by one call and how it should be evaluated.",
 bound="State the input range, approved version and evaluation conditions on which the contract depends, plus one trigger for re-validation.",
 act="Choose USE, ADAPT or HOLD. Name the integration owner/reviewer and the evidence required after composition.",
 stress="After Part A is committed, the provider silently routes the same API endpoint to modelVersion 'v8'. The response schema is unchanged and the sample call still looks plausible. No v8 held-out evaluation exists. Reassess the contract.",
 refit="Identify the invalidated postcondition/evidence and defend the final adapter, version policy and re-evaluation step.",
 example_weak="Check that the API returns a forecast.",
 example_strong="Pre: unit='Celsius' and -40≤t≤60. Post: result.unit='Celsius' and result.modelVersion='approved-v7'. The adapter rejects missing or different versions. Mean forecast error is not a per-call postcondition; verify it on a held-out set and repeat after model-version or input-distribution changes."
),
17: dict(
 assignment=8, max_points=5, title="AI Distributed Service: retry without duplicate effects",
 artifact="Failure sequence → idempotency boundary → durable evidence",
 warm="An AI call times out. Does retrying prove the first request had no external effect?",
 warmanswer="No. The first call may have committed an effect before its response was lost. A retry can generate a different AI output and duplicate the effect.",
 scenario="A fictional event service asks an AI model to draft an attendee notification, then sends the message through a delivery service. The application times out after the send request and does not know whether the message was delivered. It retries by calling the AI again and sending the new draft with a new request identifier. Normal tests pass; no lost-response test exists. Decide whether automatic retry is acceptable and what mechanism is required.",
 fit="Map the remote boundaries and distinguish 'no response received' from 'no effect occurred'. Explain why model non-determinism matters.",
 artifact_prompt="Write the lost-response event sequence. Specify an idempotency/reconciliation rule and one test that distinguishes one committed send from duplicate sends.",
 bound="State which failure modes, key lifetime and durable storage assumptions your claim covers, plus one condition that reopens it.",
 act="Choose ENABLE RETRY, RESTRICT or HOLD. Name the owner and the evidence required before automatic retry.",
 stress="After Part A is committed, a failover drill shows the idempotency record is stored only in application memory. After restart, the same key is forgotten and a retry can send another message. Reassess the mechanism.",
 refit="Explain why stable request identity is insufficient without durable state and defend the final retry/reconciliation design.",
 example_weak="Retry the AI call if it times out.",
 example_strong="Assign one idempotency key before generation, persist the committed effect and chosen output durably, and return that stored result on retry. Test a lost response after commit and a service restart; verify exactly one external send. Calling the model again is a new request, not evidence about the first effect."
),20: dict(
 assignment=9, max_points=5, title="AI Systems-of-Systems: govern changing model-produced feeds",
 artifact="Independent owners → AI feed contract → staged acceptance",
 warm="Every participating system passes its local AI test. Does that establish a trustworthy shared dashboard?",
 warmanswer="No. Independent owners can change models, semantics and update rates while interfaces still look valid. The shared service needs cross-owner assumptions and acceptance evidence.",
 scenario="A fictional university incident dashboard combines three independently owned feeds. Campus security supplies incident severity from an AI classifier, transport supplies vehicle status from its own model, and facilities supplies building-access status. Each owner controls its own release schedule. The dashboard displays the fields without recording model version or confidence. Local API tests pass, but there is no cross-system agreement for model changes, freshness or unavailable feeds. Decide whether a daytime pilot is justified and what governance record is required.",
 fit="Classify the system-of-systems relationship and identify operational/managerial independence plus one emergent shared-service risk from AI-produced semantics.",
 artifact_prompt="Propose a cross-owner interface/governance record and a staged acceptance test. Include source, timestamp, model version, freshness, unavailable-feed behavior and change notification.",
 bound="Separate what the dashboard owner can enforce locally from what requires agreement with constituent owners; state a suspension/narrowing trigger.",
 act="Choose PILOT, RESTRICTED PILOT or HOLD. Name the coordination owner, participating owners and evidence required for the next stage.",
 stress="After Part A is committed, the security owner deploys a new classifier without changing the API schema. The share of 'high severity' incidents doubles overnight, and the dashboard owner cannot inspect or roll back the model. Reassess the shared claim.",
 refit="Explain how independent AI evolution affects the dashboard promise and defend the final boundary, visible uncertainty and negotiated next step.",
 example_weak="Ask every owner to keep the same API.",
 example_strong="Treat model/semantic changes as interface changes even when JSON shape is unchanged. Display source, timestamp and declared model version; monitor distribution shifts; label affected data unverified; and require change notification plus staged acceptance before restoring the broader shared claim."
)
}
