const ROOT='https://hwuintdzmozamnmgtfly.supabase.co/functions/v1';
const LOGIN=ROOT+'/wealth-access-login';
const API=ROOT+'/wealth-api';
const EXTRA=ROOT+'/wealth-extra-api';
let token=localStorage.getItem('wealth_session')||'';
let data=null,incomeData={rows:[],summary:{}},investmentData={rows:[],summary:{},by_class:[],by_platform:[]};
const $=id=>document.getElementById(id);
const money=n=>'SAR '+new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
const numfmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
const pct=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(Number(n||0)*100)+'%';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLowerCase();
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
const catAr={Groceries:'بقالة',Fuel:'وقود',Personal:'شخصي','Dining/Coffee':'مطاعم وقهوة',Bills:'فواتير',School:'مدرسة',Car:'سيارة',Medical:'صحة',Investment:'استثمار',Other:'أخرى','Property payment':'دفعة عقار','Property other':'التزام عقاري','Debt payoff':'سداد دين','Special income':'دخل إضافي'};
const classAr={'Global Equity':'أسهم عالمية','Bitcoin':'بيتكوين','Gold':'ذهب','Saudi Equity':'أسهم سعودية','Sukuk':'صكوك','Private/Debt':'استثمار خاص/دين','Crowdfunding':'تمويل جماعي','Alternative':'بديل','Family':'مخصصات عائلية','Other':'أخرى'};
const riskAr={'Very high':'مرتفع جدًا','High':'مرتفع','High/Medium':'مرتفع/متوسط','Medium':'متوسط','Low/Medium':'منخفض/متوسط','Low':'منخفض','None':'بدون'};
const liquidityAr={'High':'عالية','Medium':'متوسطة','Low':'منخفضة','Locked':'مقيدة'};
const descMap=[['Projected next Visa statement','كشف الفيزا المتوقع التالي'],['Makkah installment','قسط مكة'],['School payment','قسط المدرسة'],['Jeddah house payment','دفعة استثمار جدة'],['Roshn installment','قسط روشن'],['Research','دخل أبحاث'],['Summer teaching','تدريس صيفي'],['Honda','هوندا'],['Baraa','براء'],['collection','تحصيل'],['month-end','نهاية الشهر'],['Hill capital','رأس مال الهيل'],['Hill profit','ربح الهيل'],['Research groups','مجموعات بحثية'],['Special fund','الصندوق الخاص']];
function arDesc(s){let x=String(s||'—');for(const [a,b] of descMap)if(x.toLowerCase().includes(a.toLowerCase()))return b;return x}
function arCat(s){return catAr[s]||s||'أخرى'}
function statusAr(x){const s=norm(x);if(s.includes('collected'))return 'محصل';if(s.includes('confirmed'))return 'مؤكد';if(s.includes('expected'))return 'متوقع';if(s.includes('pending'))return 'معلق';if(s.includes('paid'))return 'مدفوع';if(s.includes('excluded'))return 'مستبعد';return x||'—'}
function monthAr(d){const m=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];const x=new Date((d||'')+'T00:00:00');return Number.isNaN(x)?'':m[x.getMonth()]}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden')}
function showLogin(msg=''){$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');set('loginError',msg)}
async function fetchJson(url,opts={}){const headers={'content-type':'application/json',...(opts.headers||{})};if(token)headers.authorization='Bearer '+token;const r=await fetch(url,{...opts,headers});let x={};try{x=await r.json()}catch{}if(r.status===401)throw new Error('unauthorized');if(!r.ok)throw new Error(x.error||'تعذر الاتصال');return x}
async function api(path,opts={}){return fetchJson(API+'/'+path,opts)}
async function extra(path,opts={}){return fetchJson(EXTRA+'/'+path,opts)}
async function login(){const key=$('loginKey').value.trim();set('loginError','');if(!key){set('loginError','أدخل مفتاح الدخول');return}$('loginBtn').disabled=true;try{const r=await fetch(LOGIN,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({access_key:key})});const x=await r.json();if(!r.ok)throw new Error(x.error||'فشل الدخول');token=x.token;localStorage.setItem('wealth_session',token);showApp();await loadAll()}catch(e){set('loginError',e.message||String(e))}finally{$('loginBtn').disabled=false}}
async function logout(){try{await api('logout',{method:'POST',body:'{}'})}catch{}localStorage.removeItem('wealth_session');token='';showLogin('تم تسجيل الخروج')}
async function loadAll(){try{const results=await Promise.allSettled([api('dashboard'),extra('income'),extra('investments')]);if(results[0].status!=='fulfilled')throw results[0].reason;data=results[0].value;if(results[1].status==='fulfilled')incomeData=results[1].value;if(results[2].status==='fulfilled')investmentData=results[2].value;renderAll();diagnostic()}catch(e){if(e.message==='unauthorized'){localStorage.removeItem('wealth_session');token='';showLogin('انتهت الجلسة. أدخل مفتاح الدخول من جديد.')}else alert('تعذر تحميل البيانات: '+e.message)}}
function renderAll(){renderDashboard();renderTransactions();renderIncome();renderPlan();renderInvestments();renderWealth();renderRetirement();renderSettings()}
function currentMonthTransactions(){const ym=String(data?.settings?.current_month||new Date().toISOString()).slice(0,7);return (data?.transactions?.recent||[]).filter(t=>String(t.happened_at||'').slice(0,7)===ym && norm(t.direction)!=='income' && !t.excluded_from_spend)}
function renderDashboard(){const s=data.settings||{},n=data.now||{},r=data.retirement||{},tx=currentMonthTransactions();const spend=tx.reduce((z,t)=>z+Number(t.amount||0),0);set('monthSpend',money(spend));set('monthBudgetLabel','ميزانية التشغيل '+money(n.operating_total));const remaining=Math.max(0,Number(n.operating_total||0)-spend);set('budgetVariance',remaining>0?'متبقي '+money(remaining):'تجاوز '+money(spend-Number(n.operating_total||0)));set('bankBalance',money(s.bank_balance));set('payAll',money(s.visa_pay_all));set('safeSpend',money(n.spend_allowed));set('liquidPortfolio',money(s.liquid_portfolio));set('salary',money(s.salary));set('operating',money(n.operating_total));set('baseResidual',money(n.base_residual));set('sinkingTarget',money(n.sinking_target_6m));set('newCycle',money(n.new_cycle_balance));set('salaryDaysBadge',numfmt(s.days_to_salary)+' يوم حتى الراتب');set('sourceBadge','v26 · '+(s.scenario_view||'FALLBACK'));const st=(n.status||'').toLowerCase();const pill=$('decisionStatus');pill.className='status-pill '+st;pill.textContent=n.status==='GREEN'?'آمن':n.status==='YELLOW'?'تنبيه':n.status==='STOP'?'توقف':'أساسيات فقط';set('decisionText',n.status==='GREEN'?'أنت ضمن الخطة. لا تعتبر الرصيد الظاهر مالًا حرًا.':'المتاح الآمن للصرف الآن هو '+money(n.spend_allowed)+'؛ أي إنفاق إضافي يضغط الراتب القادم.');renderSpendChart(tx,n.operating_total);renderUpcoming();renderRecent();const capPct=Math.min(1,Number(r.projected_liquid_at_50||0)/Math.max(1,Number(r.required_prehome_liquid||1)));$('retireRing').style.setProperty('--p',capPct*100);set('retireProgress',pct(capPct));set('retireGap',money(r.gap_to_required_prehome));set('retireIncomeText','الدخل المستدام المتوقع '+money(r.prehome_sustainable_income_monthly)+' / شهر');set('unreviewedMini',(data.transactions?.unreviewed||0)+' عملية تحتاج مراجعة')}
function renderSpendChart(tx,budget){const days=31,daily=Array(days).fill(0);tx.forEach(t=>{const d=parseInt(String(t.happened_at||'').slice(8,10));if(d>=1&&d<=days)daily[d-1]+=Number(t.amount||0)});let cum=0;const vals=daily.map(v=>cum+=v),max=Math.max(Number(budget||0),...vals,1),w=520,h=120,p=8;const pts=vals.map((v,i)=>`${p+i*(w-2*p)/(days-1)},${h-p-v/max*(h-2*p)}`).join(' ');const end=vals[vals.length-1];$('spendChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line x1="${p}" x2="${w-p}" y1="${h-p-Number(budget||0)/max*(h-2*p)}" y2="${h-p-Number(budget||0)/max*(h-2*p)}" stroke="#d9deea" stroke-dasharray="5 5"/><polyline points="${pts}" fill="none" stroke="#5c7cfa" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${w-p}" cy="${h-p-end/max*(h-2*p)}" r="4" fill="#fff" stroke="#5c7cfa" stroke-width="3"/></svg>`}
function renderUpcoming(){const arr=(data.pipeline?.upcoming||[]).slice(0,5);$('upcomingCalendar').innerHTML=arr.length?arr.map(x=>{const d=new Date((x.event_date||'')+'T00:00:00');return `<div class="upcoming-item"><div class="date-box"><b>${String(d.getDate()).padStart(2,'0')}</b><span>${monthAr(x.event_date).slice(0,4)}</span></div><div class="desc"><b>${esc(arDesc(x.description))}</b><small>${esc(arCat(x.category))}</small></div><div class="amount">${money(x.amount)}</div></div>`}).join(''):'<div class="empty">لا توجد التزامات قريبة</div>'}
function renderRecent(){const arr=(data.transactions?.recent||[]).slice(0,5);$('recentTransactions').innerHTML=arr.length?arr.map(t=>`<div class="recent-row"><div class="merchant-icon">${esc((t.merchant||t.description||'؟').trim().charAt(0).toUpperCase())}</div><div><b>${esc(t.merchant||t.description||'عملية')}</b><small>${esc(arCat(t.category))} · ${esc(String(t.happened_at||'').slice(0,10))}</small></div><div class="amount">${money(t.amount)}</div></div>`).join(''):'<div class="empty">لا توجد عمليات</div>'}
function txFiltered(){let arr=[...(data.transactions?.recent||[])];const q=norm($('txSearch')?.value),cat=$('txCategory')?.value||'all',sort=$('txSort')?.value||'newest';if(q)arr=arr.filter(t=>[t.merchant,t.description,t.category,t.rail].some(v=>norm(v).includes(q)));if(cat!=='all')arr=arr.filter(t=>(t.category||'Other')===cat);arr.sort((a,b)=>sort==='oldest'?String(a.happened_at).localeCompare(String(b.happened_at)):sort==='amount_desc'?Number(b.amount)-Number(a.amount):sort==='amount_asc'?Number(a.amount)-Number(b.amount):String(b.happened_at).localeCompare(String(a.happened_at)));return arr}
function renderTransactions(){const arr=txFiltered();$('txRows').innerHTML=arr.length?arr.map(t=>`<tr><td>${esc(String(t.happened_at||'').slice(0,16).replace('T',' '))}</td><td><b>${esc(t.merchant||t.description||'—')}</b></td><td><span class="tag">${esc(arCat(t.category))}</span></td><td>${esc(t.rail||'—')}</td><td class="amount">${money(t.amount)}</td><td>${t.reviewed?'<span class="tag ok">تمت المراجعة</span>':`<button class="review-btn" data-review="${esc(t.id)}">اعتماد</button>`}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">لا توجد نتائج</td></tr>';set('unreviewedBadge',(data.transactions?.unreviewed||0)+' غير مراجعة')}
function incomeFiltered(){let arr=[...(incomeData.rows||[])];const q=norm($('incomeSearch')?.value),sort=$('incomeSort')?.value||'date';if(q)arr=arr.filter(x=>[x.description,x.category,x.certainty,x.recognition_status].some(v=>norm(v).includes(q)));const rank=x=>x.actual_date?0:x.include_confirmed?1:2;arr.sort((a,b)=>sort==='amount_desc'?Number(b.amount)-Number(a.amount):sort==='status'?rank(a)-rank(b):String(a.event_date||'9999').localeCompare(String(b.event_date||'9999')));return arr}
function renderIncome(){const sm=incomeData.summary||{};set('incomeCollectedMonth',money(sm.collected_this_month));set('incomeCollectedTotal',money(sm.collected_total));set('incomeConfirmed',money(sm.confirmed_upcoming));set('incomeExpected',money(sm.expected_pending));const arr=incomeFiltered();$('incomeRows').innerHTML=arr.length?arr.map(x=>{const st=x.actual_date?'محصل':x.include_confirmed?'مؤكد':'متوقع';const cls=x.actual_date?'ok':x.include_confirmed?'warn':'';return `<tr><td>${esc(x.event_date||'—')}</td><td><b>${esc(arDesc(x.description))}</b><small class="subline">${esc(arCat(x.category))}</small></td><td class="amount">${money(x.amount)}</td><td><span class="tag ${cls}">${st}</span></td><td>${esc(x.actual_date||'—')}</td><td>${x.actual_date?'':`<button class="collect-btn" data-collect="${esc(x.id)}" data-amount="${esc(x.amount)}">تسجيل التحصيل</button>`}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">لا توجد مداخيل</td></tr>'}
function planFiltered(){let arr=[...(data.pipeline?.upcoming||[])];const q=norm($('planSearch')?.value),sort=$('planSort')?.value||'date';if(q)arr=arr.filter(x=>[x.description,x.category,x.recognition_status,x.certainty].some(v=>norm(v).includes(q)));arr.sort((a,b)=>sort==='amount_desc'?Number(b.amount)-Number(a.amount):sort==='amount_asc'?Number(a.amount)-Number(b.amount):String(a.event_date||'').localeCompare(String(b.event_date||'')));return arr}
function renderPlan(){const r=data.retirement||{};set('fallbackGap',money(r.max_fallback_gap));set('fallbackMonth','أعلى ضغط: '+String(r.max_fallback_gap_month||'').slice(0,7));set('workingGap',money(r.working_max_gap));set('expectedTotal',money((data.pipeline?.expected||[]).reduce((z,x)=>z+Number(x.amount||0),0)));const arr=planFiltered();$('planRows').innerHTML=arr.length?arr.map(x=>`<tr><td>${esc(x.event_date||'—')}</td><td><b>${esc(arDesc(x.description))}</b></td><td>${esc(arCat(x.category))}</td><td class="amount">${money(x.amount)}</td><td><span class="tag ${norm(x.recognition_status||x.certainty).includes('confirmed')?'ok':'warn'}">${esc(statusAr(x.recognition_status||x.certainty))}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty">لا توجد التزامات</td></tr>'}
function investmentFiltered(){let arr=[...(investmentData.rows||[])];const q=norm($('investmentSearch')?.value),sort=$('investmentSort')?.value||'value_desc';if(q)arr=arr.filter(x=>[x.platform,x.asset,x.asset_class,x.risk].some(v=>norm(v).includes(q)));arr.sort((a,b)=>sort==='platform'?String(a.platform).localeCompare(String(b.platform)):sort==='risk'?String(a.risk).localeCompare(String(b.risk)):Number(b.market_value_sar)-Number(a.market_value_sar));return arr}
function renderInvestments(){const sm=investmentData.summary||{};set('invObserved',money(sm.observed));set('invLiquid',money(sm.liquid_target));set('invAlt',money(sm.alternative_restricted));set('invFamily',money(sm.family_earmarked));set('highRiskPct',pct(sm.high_risk_pct));$('highRiskBar').style.width=Math.min(100,Number(sm.high_risk_pct||0)*100)+'%';const cls=investmentData.by_class||[],total=cls.reduce((z,x)=>z+Number(x.value||0),0)||1;$('allocationBars').innerHTML=cls.length?cls.map(x=>`<div class="alloc-row"><span>${esc(classAr[x.name]||x.name)}</span><div class="track"><i style="width:${Math.min(100,Number(x.value)/total*100)}%"></i></div><b>${money(x.value)}</b></div>`).join(''):'<div class="empty">لا توجد بيانات</div>';const arr=investmentFiltered();$('investmentRows').innerHTML=arr.length?arr.map(x=>`<tr><td>${esc(x.platform||'—')}</td><td><b>${esc(x.asset||'—')}</b></td><td>${esc(classAr[x.asset_class]||x.asset_class||'أخرى')}</td><td class="amount">${money(x.market_value_sar)}</td><td class="amount">${x.pl_orig==null?'—':numfmt(x.pl_orig)}</td><td>${esc(riskAr[x.risk]||x.risk||'—')}</td><td>${esc(liquidityAr[x.liquidity]||x.liquidity||'—')}</td><td><button class="edit-btn" data-invest="${esc(x.id)}" data-value="${esc(x.market_value_sar)}">تحديث</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">لا توجد استثمارات</td></tr>'}
function assetFiltered(){let arr=(data.wealth?.assets||[]).filter(x=>x.asset_type==='property');const q=norm($('assetSearch')?.value),sort=$('assetSort')?.value||'net_desc',net=x=>Number(x.current_value||0)-Number(x.outstanding_obligation||0);if(q)arr=arr.filter(x=>[x.label,x.key,x.notes].some(v=>norm(v).includes(q)));arr.sort((a,b)=>sort==='value_desc'?Number(b.current_value)-Number(a.current_value):sort==='income_desc'?Number(b.monthly_net_income)-Number(a.monthly_net_income):net(b)-net(a));return arr}
function renderWealth(){const arr=assetFiltered(),gross=arr.reduce((z,x)=>z+Number(x.current_value||0),0),equity=arr.reduce((z,x)=>z+Number(x.current_value||0)-Number(x.outstanding_obligation||0),0);set('netWorth',money(data.wealth?.net_worth_now));set('propertyGross',money(gross));set('propertyEquity',money(equity));$('assetRows').innerHTML=arr.length?arr.map(x=>`<tr><td><b>${esc(x.label||x.key)}</b></td><td class="amount">${money(x.current_value)}</td><td class="amount">${money(x.outstanding_obligation)}</td><td class="amount">${money(Number(x.current_value||0)-Number(x.outstanding_obligation||0))}</td><td class="amount">${money(x.monthly_net_income)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">لا توجد عقارات</td></tr>'}
function renderRetirement(){const r=data.retirement||{};set('retTarget',money(r.target_monthly));set('retIncome',money(r.prehome_sustainable_income_monthly));set('retLiquid',money(r.projected_liquid_at_50));set('retRequired',money(r.required_prehome_liquid));set('retGap',money(r.gap_to_required_prehome));set('retCoverage',pct(r.prehome_coverage));$('retRing').style.setProperty('--p',Math.min(100,Number(r.prehome_coverage||0)*100))}
function renderSettings(){const s=data.settings||{};$('setBank').value=s.bank_balance??'';$('setPayAll').value=s.visa_pay_all??'';$('setSalary').value=s.salary??'';$('setDays').value=s.days_to_salary??'';$('setStatement').value=String(Boolean(s.visa_statement_paid));$('setScenario').value=s.scenario_view||'FALLBACK'}
async function addTransaction(){const amount=Number($('txAmount').value),merchant=$('txMerchant').value.trim(),rail=$('txRail').value,category=$('txNewCategory').value;if(!amount||amount<=0){alert('أدخل مبلغًا صحيحًا');return}await api('transactions',{method:'POST',body:JSON.stringify({amount,merchant,rail,category,reviewed:false})});$('txAmount').value='';$('txMerchant').value='';$('addTxPanel').classList.add('hidden');await loadAll()}
async function reviewTransaction(id){await api('transaction',{method:'PATCH',body:JSON.stringify({id,reviewed:true})});await loadAll()}
async function addIncome(){const description=$('incomeDescription').value.trim(),amount=Number($('incomeAmount').value),event_date=$('incomeDate').value,certainty=$('incomeCertainty').value;if(!description||!amount||amount<=0){alert('أدخل الوصف والمبلغ');return}await extra('income',{method:'POST',body:JSON.stringify({description,amount,event_date,certainty})});$('addIncomePanel').classList.add('hidden');$('incomeDescription').value='';$('incomeAmount').value='';await loadAll()}
async function collectIncome(id,amount){const v=prompt('المبلغ الفعلي المحصل',String(amount||''));if(v===null)return;const d=prompt('تاريخ التحصيل YYYY-MM-DD',new Date().toISOString().slice(0,10));if(d===null)return;await extra('mark-collected',{method:'POST',body:JSON.stringify({id,amount:Number(v),actual_date:d})});await loadAll()}
async function saveInvestment(){const id=$('editInvestmentId').value,value=Number($('editInvestmentValue').value);if(!id||!value||value<0){alert('أدخل قيمة صحيحة');return}await extra('investment',{method:'PATCH',body:JSON.stringify({id,market_value_sar:value})});$('investmentModal').classList.add('hidden');await loadAll()}
async function saveSettings(){await api('settings',{method:'PATCH',body:JSON.stringify({bank_balance:Number($('setBank').value),visa_pay_all:Number($('setPayAll').value),salary:Number($('setSalary').value),days_to_salary:Number($('setDays').value),visa_statement_paid:$('setStatement').value==='true',scenario_view:$('setScenario').value})});await loadAll();alert('تم الحفظ وإعادة الحساب')}
async function diagnostic(){try{const x=await api('diagnostic');set('integrityBadge',x.ok?'v26 مطابق':'خطأ في المطابقة');$('integrityBadge').className='badge '+(x.ok?'':'soft');set('diagBox',x.ok?'الموقع مطابق لآخر Excel v26 ضمن حدود الاختبار.':'يوجد اختلاف عن Excel v26؛ لا تعتمد القرارات حتى الإصلاح.')}catch(e){set('integrityBadge','تعذر الفحص');set('diagBox','تعذر إجراء فحص التطابق')}}
function switchTab(tab){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===tab));document.querySelectorAll('#sideNav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));const map={dashboard:['الرئيسية','ملخص مالي واضح ومباشر'],transactions:['العمليات','بحث وتصنيف ومراجعة'],income:['المداخيل','تواريخ الوصول والتحصيل الفعلي'],plan:['الخطة','الالتزامات وفجوة السيولة'],investments:['الاستثمارات','المحفظة والتوزيع والمخاطر'],wealth:['الثروة والعقار','القيمة الصافية للعقارات والسيولة'],retirement:['التقاعد 50','تقدمك نحو 50,000 ريال شهريًا'],settings:['الإعدادات','مدخلات التشغيل فقط']};set('pageTitle',map[tab][0]);set('pageSubtitle',map[tab][1])}
function globalIndex(){const out=[];(data.transactions?.recent||[]).forEach(x=>out.push({tab:'transactions',title:x.merchant||x.description||'عملية',sub:`${arCat(x.category)} · ${money(x.amount)}`}));(incomeData.rows||[]).forEach(x=>out.push({tab:'income',title:arDesc(x.description),sub:`${statusAr(x.recognition_status||x.certainty)} · ${money(x.amount)}`}));(data.pipeline?.upcoming||[]).forEach(x=>out.push({tab:'plan',title:arDesc(x.description),sub:`${x.event_date||''} · ${money(x.amount)}`}));(investmentData.rows||[]).forEach(x=>out.push({tab:'investments',title:x.asset||'استثمار',sub:`${x.platform||''} · ${money(x.market_value_sar)}`}));(data.wealth?.assets||[]).forEach(x=>out.push({tab:'wealth',title:x.label||x.key||'أصل',sub:money(x.current_value)}));return out}
function showSearch(){const q=norm($('globalSearch').value);if(!q||!data){$('searchResults').classList.add('hidden');return}const res=globalIndex().filter(x=>norm(x.title+' '+x.sub).includes(q)).slice(0,14);$('searchResults').innerHTML=res.length?res.map((x,i)=>`<div class="search-item" data-i="${i}"><b>${esc(x.title)}</b><span>${esc(x.sub)}</span></div>`).join(''):'<div class="empty">لا توجد نتائج</div>';$('searchResults').dataset.items=JSON.stringify(res);$('searchResults').classList.remove('hidden')}
$('loginBtn').addEventListener('click',login);$('loginKey').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').addEventListener('click',logout);$('refreshBtn').addEventListener('click',loadAll);$('syncNowBtn').addEventListener('click',loadAll);$('sideNav').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)switchTab(b.dataset.tab)});document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.go)));$('globalSearch').addEventListener('input',showSearch);$('searchResults').addEventListener('click',e=>{const row=e.target.closest('.search-item');if(!row)return;const items=JSON.parse($('searchResults').dataset.items||'[]'),it=items[Number(row.dataset.i)];if(it){switchTab(it.tab);$('globalSearch').value='';$('searchResults').classList.add('hidden')}});['txSearch','txCategory','txSort'].forEach(id=>$(id).addEventListener(id==='txSearch'?'input':'change',renderTransactions));['incomeSearch','incomeSort'].forEach(id=>$(id).addEventListener(id==='incomeSearch'?'input':'change',renderIncome));['planSearch','planSort'].forEach(id=>$(id).addEventListener(id==='planSearch'?'input':'change',renderPlan));['investmentSearch','investmentSort'].forEach(id=>$(id).addEventListener(id==='investmentSearch'?'input':'change',renderInvestments));['assetSearch','assetSort'].forEach(id=>$(id).addEventListener(id==='assetSearch'?'input':'change',renderWealth));$('showAddTx').addEventListener('click',()=>$('addTxPanel').classList.remove('hidden'));$('cancelAddTx').addEventListener('click',()=>$('addTxPanel').classList.add('hidden'));$('addTxBtn').addEventListener('click',addTransaction);$('txRows').addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(b)reviewTransaction(b.dataset.review)});$('showAddIncome').addEventListener('click',()=>$('addIncomePanel').classList.remove('hidden'));$('cancelAddIncome').addEventListener('click',()=>$('addIncomePanel').classList.add('hidden'));$('addIncomeBtn').addEventListener('click',addIncome);$('incomeRows').addEventListener('click',e=>{const b=e.target.closest('[data-collect]');if(b)collectIncome(b.dataset.collect,b.dataset.amount)});$('investmentRows').addEventListener('click',e=>{const b=e.target.closest('[data-invest]');if(!b)return;$('editInvestmentId').value=b.dataset.invest;$('editInvestmentValue').value=b.dataset.value;$('investmentModal').classList.remove('hidden')});$('closeInvestmentModal').addEventListener('click',()=>$('investmentModal').classList.add('hidden'));$('saveInvestment').addEventListener('click',saveInvestment);$('saveSettings').addEventListener('click',saveSettings);document.addEventListener('click',e=>{if(!e.target.closest('.global-search'))$('searchResults').classList.add('hidden')});if(token){showApp();loadAll()}else showLogin();
