const ROOT='https://hwuintdzmozamnmgtfly.supabase.co/functions/v1';
const LOGIN=ROOT+'/wealth-access-login';
const API=ROOT+'/wealth-api';
const EXTRA=ROOT+'/wealth-extra-api';
let token=localStorage.getItem('wealth_session')||'';
let data=null, incomeData={rows:[],summary:{}}, investmentData={rows:[],summary:{},by_class:[],by_platform:[]};
let currentTab='today';
const $=id=>document.getElementById(id);
const money=n=>'SAR '+new Intl.NumberFormat('en-US',{minimumFractionDigits:0,maximumFractionDigits:2}).format(Number(n||0));
const number=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
const pct=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:1,maximumFractionDigits:1}).format(Number(n||0)*100)+'%';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLowerCase();
const num=v=>Number(v||0);
function setText(id,v){const el=$(id);if(el)el.textContent=v}
function fmtDate(s){if(!s)return '—';const d=new Date(String(s).slice(0,10)+'T00:00:00');return isNaN(d)?String(s):new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden')}
function showLogin(msg=''){$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');$('loginError').textContent=msg}
async function request(base,path,opts={}){const headers={'content-type':'application/json'};if(token)headers.authorization='Bearer '+token;const r=await fetch(base+'/'+path,{...opts,headers});let x={};try{x=await r.json()}catch{}if(r.status===401){localStorage.removeItem('wealth_session');token='';showLogin('انتهت الجلسة، أدخل مفتاح الدخول مرة أخرى.');throw new Error('unauthorized')}if(!r.ok)throw new Error(x.error||'فشل الاتصال');return x}
const api=(path,opts={})=>request(API,path,opts);
const extra=(path,opts={})=>request(EXTRA,path,opts);
async function login(){const key=$('loginKey').value.trim();$('loginError').textContent='';if(!key){$('loginError').textContent='أدخل مفتاح الدخول';return}$('loginBtn').disabled=true;try{const r=await fetch(LOGIN,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({access_key:key})});const x=await r.json();if(!r.ok)throw new Error(x.error||'فشل الدخول');token=x.token;localStorage.setItem('wealth_session',token);showApp();await loadAll()}catch(e){$('loginError').textContent=e.message||String(e)}finally{$('loginBtn').disabled=false}}
async function logout(){try{await api('logout',{method:'POST',body:'{}'})}catch{}localStorage.removeItem('wealth_session');token='';showLogin('تم تسجيل الخروج')}
async function loadAll(){try{const [d,i,inv]=await Promise.all([api('dashboard'),extra('income'),extra('investments')]);data=d;incomeData=i;investmentData=inv;renderAll();diagnostic()}catch(e){if(e.message!=='unauthorized')alert('تعذر تحميل البيانات: '+e.message)}}
function renderAll(){const n=data.now||{},r=data.retirement||{},s=data.settings||{},w=data.wealth||{};setText('safeSpend',money(n.spend_allowed));setText('bankBalance',money(s.bank_balance));setText('payAll',money(s.visa_pay_all));setText('newCycle',money(n.new_cycle_balance));setText('hardStop',money(n.hard_stop));setText('salary',money(s.salary));setText('operating',money(n.operating_total));setText('baseResidual',money(n.base_residual));setText('sinkingTarget',money(n.sinking_target_6m));setText('sourceBadge','v26 · '+(s.scenario_view||'FALLBACK'));const chip=$('statusChip');chip.textContent=n.status||'—';chip.className='statusChip '+norm(n.status);setText('heroAction',n.status==='GREEN'?'ضمن الخطة. حافظ على مستوى الصرف الحالي ولا تعتبر أي رصيد إضافي مالاً حراً.':'أساسيات فقط الآن. المتاح الآمن هو '+money(n.spend_allowed)+'؛ أي إنفاق إضافي يضغط الراتب القادم.');setText('fallbackGap',money(r.max_fallback_gap));setText('fallbackMonth','أعلى ضغط: '+String(r.max_fallback_gap_month||'').slice(0,7));setText('workingGap',money(r.working_max_gap));setText('expectedTotal',money(num(incomeData.summary?.expected_pending)));const assetNet=(w.assets||[]).reduce((z,x)=>z+num(x.current_value)-num(x.outstanding_obligation),0);setText('netWorth',money(num(s.bank_balance)+assetNet));setText('liquidPortfolio',money(s.liquid_portfolio));setText('retTarget',money(r.target_monthly));setText('retIncome',money(r.prehome_sustainable_income_monthly));setText('retLiquid',money(r.projected_liquid_at_50));setText('retRequired',money(r.required_prehome_liquid));setText('retGap',money(r.gap_to_required_prehome));setText('retCoverage',pct(r.prehome_coverage));const ringP=Math.max(0,Math.min(100,num(r.prehome_coverage)*100));$('retRing').style.setProperty('--p',ringP);const capitalP=Math.max(0,Math.min(100,num(r.projected_liquid_at_50)/Math.max(1,num(r.required_prehome_liquid))*100));$('retMiniPct').textContent=number(capitalP)+'%';$('retMiniPct').parentElement.style.setProperty('--p',capitalP+'%');setText('retMiniGap',money(r.gap_to_required_prehome));$('setBank').value=s.bank_balance??'';$('setPayAll').value=s.visa_pay_all??'';$('setSalary').value=s.salary??'';$('setDays').value=s.days_to_salary??'';$('setStatement').value=String(Boolean(s.visa_statement_paid));$('setScenario').value=s.scenario_view||'FALLBACK';renderMiniUpcoming();renderTransactions();renderIncome();renderPlan();renderInvestments();renderAssets()}
function renderMiniUpcoming(){const arr=((data.pipeline&&data.pipeline.upcoming)||[]).slice(0,4);$('upcomingMini').innerHTML=arr.length?arr.map(x=>`<div class="miniItem"><time>${esc(fmtDate(x.event_date))}</time><div><strong>${esc(x.description||'—')}</strong><small>${esc(x.category||'')}</small></div><div class="amount">${money(x.amount)}</div></div>`).join(''):'<div class="empty">لا توجد التزامات قريبة</div>'}
function txFiltered(){let arr=[...((data.transactions&&data.transactions.recent)||[])];const q=norm($('txSearch')?.value);const cat=$('txCategory')?.value||'all';if(q)arr=arr.filter(t=>[t.merchant,t.description,t.category,t.rail].some(v=>norm(v).includes(q)));if(cat!=='all')arr=arr.filter(t=>(t.category||'Other')===cat);const sort=$('txSort')?.value||'newest';arr.sort((a,b)=>sort==='oldest'?String(a.happened_at).localeCompare(String(b.happened_at)):sort==='amount_desc'?num(b.amount)-num(a.amount):sort==='amount_asc'?num(a.amount)-num(b.amount):String(b.happened_at).localeCompare(String(a.happened_at)));return arr}
function renderTransactions(){const arr=txFiltered();$('txRows').innerHTML=arr.length?arr.map(t=>`<tr><td>${esc(String(t.happened_at||'').slice(0,16).replace('T',' '))}</td><td><strong>${esc(t.merchant||t.description||'—')}</strong></td><td><span class="tag">${esc(t.category||'Other')}</span></td><td>${esc(t.rail||'')}</td><td class="amount">${money(t.amount)}</td><td>${t.reviewed?'<span class="tag ok">Reviewed</span>':`<button class="reviewBtn" data-review="${esc(t.id)}">اعتماد</button>`}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">لا توجد نتائج</td></tr>';setText('unreviewedBadge',number((data.transactions&&data.transactions.unreviewed)||0)+' غير مراجعة')}
function incomeStatus(x){if(x.actual_date)return 'collected';if(x.include_confirmed)return 'confirmed';return 'expected'}
function incomeFiltered(){let arr=[...(incomeData.rows||[])];const q=norm($('incomeSearch')?.value);const st=$('incomeStatus')?.value||'all';if(q)arr=arr.filter(x=>[x.description,x.category,x.property_name,x.certainty,x.recognition_status].some(v=>norm(v).includes(q)));if(st!=='all')arr=arr.filter(x=>incomeStatus(x)===st);const sort=$('incomeSort')?.value||'date_asc';const d=x=>String(x.actual_date||x.event_date||'9999-12-31');arr.sort((a,b)=>sort==='date_desc'?d(b).localeCompare(d(a)):sort==='amount_desc'?num(b.amount)-num(a.amount):sort==='amount_asc'?num(a.amount)-num(b.amount):d(a).localeCompare(d(b)));return arr}
function statusBadge(x){const s=incomeStatus(x),label=s==='collected'?'Collected':s==='confirmed'?'Confirmed':'Expected';return `<span class="statusTag ${s}">${label}</span>`}
function renderIncome(){const s=incomeData.summary||{};setText('incomeCollectedMonth',money(s.collected_this_month));setText('incomeConfirmed',money(s.confirmed_upcoming));setText('incomeExpected',money(s.expected_pending));setText('incomeCollectedTotal',money(s.collected_total));const timeline=[...(incomeData.rows||[])].filter(x=>x.event_date||x.actual_date).sort((a,b)=>String(a.actual_date||a.event_date).localeCompare(String(b.actual_date||b.event_date))).slice(0,8);$('incomeTimeline').innerHTML=timeline.length?timeline.map(x=>`<article class="timelineItem ${incomeStatus(x)}"><div class="tDate">${esc(fmtDate(x.actual_date||x.event_date))}</div><div class="tTitle">${esc(x.description||'Income')}</div><div class="tAmount">${money(x.amount)}</div><div class="hint">${statusBadge(x)}</div></article>`).join(''):'<div class="empty">لا توجد مداخيل مسجلة</div>';const arr=incomeFiltered();$('incomeRows').innerHTML=arr.length?arr.map(x=>`<tr><td>${esc(fmtDate(x.event_date))}</td><td><strong>${esc(x.description||'—')}</strong></td><td>${esc(x.category||'')}</td><td class="amount">${money(x.amount)}</td><td>${statusBadge(x)}</td><td>${esc(fmtDate(x.actual_date))}</td><td>${x.actual_date?'<span class="tag ok">تم</span>':`<button class="collectBtn" data-collect="${esc(x.id)}" data-amount="${esc(x.amount)}">تحصيل</button>`}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">لا توجد نتائج</td></tr>'}
function planFiltered(){let arr=[...((data.pipeline&&data.pipeline.upcoming)||[])];const q=norm($('planSearch')?.value);if(q)arr=arr.filter(x=>[x.description,x.category,x.recognition_status,x.certainty].some(v=>norm(v).includes(q)));const sort=$('planSort')?.value||'date';arr.sort((a,b)=>sort==='amount_desc'?num(b.amount)-num(a.amount):sort==='amount_asc'?num(a.amount)-num(b.amount):String(a.event_date||'').localeCompare(String(b.event_date||'')));return arr}
function renderPlan(){const arr=planFiltered();$('planRows').innerHTML=arr.length?arr.map(x=>`<tr><td>${esc(fmtDate(x.event_date))}</td><td><strong>${esc(x.description||'—')}</strong></td><td>${esc(x.category||'')}</td><td class="amount">${money(x.amount)}</td><td><span class="tag ok">${esc(x.recognition_status||x.certainty||'')}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty">لا توجد نتائج</td></tr>'}
function riskGroup(r){const x=norm(r);if(x.includes('very high')||x==='high'||x.startsWith('high/'))return 'high';if(x.includes('medium'))return 'medium';return 'low'}
function investmentFiltered(){let arr=[...(investmentData.rows||[])];const q=norm($('investmentSearch')?.value);const rf=$('investmentRisk')?.value||'all';if(q)arr=arr.filter(x=>[x.platform,x.owner_earmark,x.asset,x.asset_class,x.risk,x.liquidity].some(v=>norm(v).includes(q)));if(rf!=='all')arr=arr.filter(x=>riskGroup(x.risk)===rf);const sort=$('investmentSort')?.value||'value_desc';arr.sort((a,b)=>sort==='value_asc'?num(a.market_value_sar)-num(b.market_value_sar):sort==='pl_desc'?num(b.pl_orig)-num(a.pl_orig):sort==='pl_asc'?num(a.pl_orig)-num(b.pl_orig):num(b.market_value_sar)-num(a.market_value_sar));return arr}
function renderInvestments(){const s=investmentData.summary||{};setText('invObserved',money(s.observed));setText('invRetEligible',money(s.retirement_eligible));setText('invLiquid',money(s.liquid_target));setText('invAlt',money(s.alternative_restricted));setText('invFamily',money(s.family_earmarked));setText('invRiskPct',pct(s.high_risk_pct));setText('invRiskAmount',money(s.high_risk_liquid)+' من السائل');const max=Math.max(1,...(investmentData.by_class||[]).map(x=>num(x.value)));$('allocationBars').innerHTML=(investmentData.by_class||[]).slice(0,8).map(x=>`<div class="allocRow"><div class="allocName">${esc(x.name)}</div><div class="allocTrack"><div class="allocFill" style="width:${Math.max(2,num(x.value)/max*100)}%"></div></div><div class="allocValue">${money(x.value)}</div></div>`).join('')||'<div class="empty">لا توجد بيانات توزيع</div>';const signals=[];signals.push({c:s.high_risk_pct>0.2?'bad':'',t:'تركيز المخاطر',d:`التعرض العالي/العالي جداً يمثل ${pct(s.high_risk_pct)} من المحفظة السائلة المؤهلة.`});signals.push({c:'',t:'فصل أموال العائلة',d:`مخصصات العائلة ${money(s.family_earmarked)} ظاهرة منفصلة ولا تدخل تمويل التقاعد.`});signals.push({c:'',t:'سيولة التقاعد',d:`المؤهل مباشرة لهدف رأس المال السائل ${money(s.liquid_target)}؛ البديل/المقيد ${money(s.alternative_restricted)}.`});$('investmentSignals').innerHTML=signals.map(x=>`<div class="signal ${x.c}"><strong>${x.t}</strong><span>${x.d}</span></div>`).join('');const arr=investmentFiltered();$('investmentRows').innerHTML=arr.length?arr.map(x=>{const pl=num(x.pl_orig),pc=pl>0?'plPos':pl<0?'plNeg':'';return `<tr><td>${esc(x.platform||'—')}</td><td class="ownerCell">${esc(x.owner_earmark||'—')}</td><td><div class="assetTitle">${esc(x.asset||'—')}</div><div class="assetSub">${esc(x.currency||'')}</div></td><td>${esc(x.asset_class||'')}</td><td class="amount">${money(x.market_value_sar)}</td><td class="amount ${pc}">${x.pl_orig==null?'—':number(pl)+' '+esc(x.currency||'')}</td><td class="risk${riskGroup(x.risk)[0].toUpperCase()+riskGroup(x.risk).slice(1)}">${esc(x.risk||'—')}</td><td>${esc(x.liquidity||'—')}</td><td><button class="editInvBtn" data-invest="${esc(x.id)}">تحديث</button></td></tr>`}).join(''):'<tr><td colspan="9" class="empty">لا توجد نتائج</td></tr>'}
function assetFiltered(){let arr=[...((data.wealth&&data.wealth.assets)||[])].filter(x=>x.asset_type==='property');const q=norm($('assetSearch')?.value);if(q)arr=arr.filter(x=>[x.label,x.key,x.notes].some(v=>norm(v).includes(q)));const sort=$('assetSort')?.value||'net_desc';const net=x=>num(x.current_value)-num(x.outstanding_obligation);arr.sort((a,b)=>sort==='value_desc'?num(b.current_value)-num(a.current_value):sort==='income_desc'?num(b.monthly_net_income)-num(a.monthly_net_income):net(b)-net(a));return arr}
function renderAssets(){const arr=assetFiltered();$('assetRows').innerHTML=arr.length?arr.map(x=>{const net=num(x.current_value)-num(x.outstanding_obligation);return `<tr><td><strong>${esc(x.label||x.key||'—')}</strong></td><td class="amount">${money(x.current_value)}</td><td class="amount">${money(x.outstanding_obligation)}</td><td class="amount">${money(net)}</td><td class="amount">${money(x.monthly_net_income)}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">لا توجد أصول عقارية</td></tr>'}
async function addTransaction(){const amount=num($('txAmount').value),merchant=$('txMerchant').value.trim(),rail=$('txRail').value,category=$('txNewCategory').value;if(!amount||amount<=0){alert('أدخل مبلغاً صحيحاً');return}await api('transactions',{method:'POST',body:JSON.stringify({amount,merchant,rail,category,reviewed:false})});$('txAmount').value='';$('txMerchant').value='';$('addTxPanel').classList.add('hidden');await loadAll()}
async function reviewTransaction(id){await api('transaction',{method:'PATCH',body:JSON.stringify({id,reviewed:true})});await loadAll()}
async function addIncome(){const amount=num($('incomeAmount').value),description=$('incomeDesc').value.trim(),event_date=$('incomeDate').value,certainty=$('incomeCertainty').value;if(!amount||amount<=0||!description){alert('أدخل المصدر والمبلغ');return}await extra('income',{method:'POST',body:JSON.stringify({amount,description,event_date:event_date||null,certainty})});$('incomeAmount').value='';$('incomeDesc').value='';$('addIncomePanel').classList.add('hidden');await loadAll()}
async function markCollected(id,defaultAmount){const amount=prompt('المبلغ المحصل فعلياً',String(defaultAmount||''));if(amount===null)return;const actual_date=prompt('تاريخ التحصيل YYYY-MM-DD',new Date().toISOString().slice(0,10));if(actual_date===null)return;await extra('mark-collected',{method:'POST',body:JSON.stringify({id,amount:num(amount),actual_date})});await loadAll()}
function openInvestment(id){const x=(investmentData.rows||[]).find(r=>r.id===id);if(!x)return;$('investmentId').value=x.id;$('investmentDialogTitle').textContent=x.asset;$('investmentDialogSub').textContent=(x.platform||'')+' · '+(x.owner_earmark||'');$('investmentValue').value=x.market_value_sar??'';$('investmentOrigValue').value=x.market_value_orig??'';$('investmentQty').value=x.qty??'';$('investmentNotes').value=x.notes??'';$('investmentDialog').showModal()}
async function saveInvestment(e){e.preventDefault();const id=$('investmentId').value;if(!id)return;await extra('investment',{method:'PATCH',body:JSON.stringify({id,market_value_sar:num($('investmentValue').value),market_value_orig:$('investmentOrigValue').value===''?null:num($('investmentOrigValue').value),qty:$('investmentQty').value===''?null:num($('investmentQty').value),notes:$('investmentNotes').value})});$('investmentDialog').close();await loadAll()}
async function saveSettings(){const z={bank_balance:num($('setBank').value),visa_pay_all:num($('setPayAll').value),salary:num($('setSalary').value),days_to_salary:num($('setDays').value),visa_statement_paid:$('setStatement').value==='true',scenario_view:$('setScenario').value};await api('settings',{method:'PATCH',body:JSON.stringify(z)});await loadAll();alert('تم الحفظ وإعادة الحساب')}
async function diagnostic(){try{const x=await api('diagnostic');const el=$('integrityBadge');el.textContent=x.ok?'v26 PASS':'v26 LIVE';el.className='pill '+(x.ok?'':'subtle');$('diagBox').textContent=x.ok?'v26 Integrity: PASS — المحرك على baseline المرجعي.':'المحرك v26 يعمل على بيانات حية تغيّرت عن baseline؛ هذا طبيعي بعد التحديثات اليومية.'}catch(e){$('integrityBadge').textContent='v26';$('diagBox').textContent='تعذر فحص baseline: '+e.message}}
function switchTab(tab){currentTab=tab;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===tab));document.querySelectorAll('#sideNav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));const map={today:['اليوم','قرار مالي واحد واضح الآن'],transactions:['العمليات','بحث، تصنيف ومراجعة'],income:['المداخيل','المبالغ، الحالة وتاريخ التحصيل'],plan:['الخطة','الالتزامات والفجوات النقدية'],investments:['الاستثمارات','المقتنيات، السيولة والمخاطر'],wealth:['الثروة','العقار والسيولة وصافي القيمة'],retirement:['التقاعد 50','هل الخطة تمول 50,000 SAR شهرياً؟'],settings:['الإعدادات','مدخلات التشغيل فقط']};setText('pageTitle',map[tab][0]);setText('pageSubtitle',map[tab][1]);if(tab==='income')renderIncome();if(tab==='investments')renderInvestments()}
function globalIndex(){const out=[];((data.transactions&&data.transactions.recent)||[]).forEach(x=>out.push({tab:'transactions',title:x.merchant||x.description||'عملية',sub:`${x.category||''} · ${money(x.amount)}`}));(incomeData.rows||[]).forEach(x=>out.push({tab:'income',title:x.description||'دخل',sub:`${fmtDate(x.event_date)} · ${money(x.amount)} · ${incomeStatus(x)}`}));((data.pipeline&&data.pipeline.upcoming)||[]).forEach(x=>out.push({tab:'plan',title:x.description||'التزام',sub:`${fmtDate(x.event_date)} · ${money(x.amount)}`}));(investmentData.rows||[]).forEach(x=>out.push({tab:'investments',title:x.asset||'استثمار',sub:`${x.platform||''} · ${money(x.market_value_sar)}`}));((data.wealth&&data.wealth.assets)||[]).filter(x=>x.asset_type==='property').forEach(x=>out.push({tab:'wealth',title:x.label||x.key||'أصل',sub:money(x.current_value)}));return out}
function showSearch(){const q=norm($('globalSearch').value);if(!q||!data){$('searchResults').classList.add('hidden');return}const res=globalIndex().filter(x=>norm(x.title+' '+x.sub).includes(q)).slice(0,14);$('searchResults').innerHTML=res.length?res.map((x,i)=>`<div class="searchResult" data-i="${i}"><b>${esc(x.title)}</b><span>${esc(x.sub)}</span></div>`).join(''):'<div class="empty">لا توجد نتائج</div>';$('searchResults').dataset.items=JSON.stringify(res);$('searchResults').classList.remove('hidden')}
$('loginBtn').addEventListener('click',login);$('loginKey').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').addEventListener('click',logout);$('refreshBtn').addEventListener('click',loadAll);$('sideNav').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)switchTab(b.dataset.tab)});document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.go)));$('globalSearch').addEventListener('input',showSearch);$('searchResults').addEventListener('click',e=>{const row=e.target.closest('.searchResult');if(!row)return;const items=JSON.parse($('searchResults').dataset.items||'[]');const item=items[Number(row.dataset.i)];if(item){switchTab(item.tab);$('globalSearch').value='';$('searchResults').classList.add('hidden')}});['txSearch','txSort','txCategory'].forEach(id=>$(id).addEventListener(id==='txSearch'?'input':'change',renderTransactions));['incomeSearch','incomeStatus','incomeSort'].forEach(id=>$(id).addEventListener(id==='incomeSearch'?'input':'change',renderIncome));['planSearch','planSort'].forEach(id=>$(id).addEventListener(id==='planSearch'?'input':'change',renderPlan));['investmentSearch','investmentRisk','investmentSort'].forEach(id=>$(id).addEventListener(id==='investmentSearch'?'input':'change',renderInvestments));['assetSearch','assetSort'].forEach(id=>$(id).addEventListener(id==='assetSearch'?'input':'change',renderAssets));$('showAddTx').addEventListener('click',()=>{$('addTxPanel').classList.remove('hidden');$('txAmount').focus()});$('cancelAddTx').addEventListener('click',()=>$('addTxPanel').classList.add('hidden'));$('addTxBtn').addEventListener('click',addTransaction);$('txRows').addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(b)reviewTransaction(b.dataset.review)});$('showAddIncome').addEventListener('click',()=>{$('addIncomePanel').classList.remove('hidden');$('incomeDate').value=new Date().toISOString().slice(0,10);$('incomeDesc').focus()});$('cancelAddIncome').addEventListener('click',()=>$('addIncomePanel').classList.add('hidden'));$('addIncomeBtn').addEventListener('click',addIncome);$('incomeRows').addEventListener('click',e=>{const b=e.target.closest('[data-collect]');if(b)markCollected(b.dataset.collect,b.dataset.amount)});$('investmentRows').addEventListener('click',e=>{const b=e.target.closest('[data-invest]');if(b)openInvestment(b.dataset.invest)});$('saveInvestmentBtn').addEventListener('click',saveInvestment);$('saveSettings').addEventListener('click',saveSettings);document.addEventListener('click',e=>{if(!e.target.closest('.searchBox'))$('searchResults').classList.add('hidden')});if(token){showApp();loadAll()}else showLogin();