(function(){
  const INTEL=ROOT+'/wealth-intelligence-api';
  const REV=ROOT+'/wealth-revenue-api';
  let intel=null;
  const q=id=>document.getElementById(id);
  const fmt=n=>'SAR '+new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
  const escX=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sevAr={critical:'حرج',warning:'تنبيه',opportunity:'فرصة',info:'معلومة'};
  const tabAr={dashboard:'الرئيسية',transactions:'العمليات',income:'الإيرادات',plan:'الخطة',investments:'الاستثمارات',wealth:'الثروة والعقار',retirement:'التقاعد 50',settings:'الإعدادات'};
  async function intelReq(){const r=await fetch(INTEL+'/daily',{headers:{authorization:'Bearer '+token,'content-type':'application/json'}});const x=await r.json();if(!r.ok)throw new Error(x.error||'تعذر تحميل مركز اليوم');return x}
  async function revReq(action,opts={}){const r=await fetch(REV+'/'+action,{...opts,headers:{authorization:'Bearer '+token,'content-type':'application/json'}});const x=await r.json();if(!r.ok)throw new Error(x.error||'تعذر حفظ الإيراد');return x}
  function ensureUI(){
    const dash=q('dashboard'); if(dash&&!q('dailyCommandCenter')){
      const box=document.createElement('section');box.id='dailyCommandCenter';box.className='daily-command-center';
      box.innerHTML=`<div class="dcc-head"><div><span class="dcc-kicker">مركز اليوم</span><h2 id="dccHeadline">جارٍ التحليل...</h2><p id="dccMessage">يراجع الصرف، الإيرادات، الالتزامات، العجز والاستثمار.</p></div><div class="dcc-head-actions"><span id="dccStatus" class="dcc-status">—</span><button id="dccRefresh" class="dcc-icon" title="تحديث">↻</button></div></div><div class="dcc-grid"><div class="dcc-task"><span>مهمة اليوم</span><b id="dccTaskTitle">—</b><p id="dccTaskMessage">—</p><button id="dccTaskBtn" class="dcc-link">افتح</button></div><div class="dcc-metric"><span>المتاح الآمن</span><b id="dccSafe">—</b><small>ليس رصيد البنك</small></div><div class="dcc-metric"><span>التنبيهات</span><b id="dccCount">—</b><small id="dccCritical">—</small></div><div class="dcc-metric"><span>بوابة الاستثمار</span><b id="dccInvest">—</b><small>تفتح بعد الأمان</small></div></div><div class="dcc-insights-head"><b>أهم التنبيهات</b><button id="dccRescueBtn" class="dcc-link">خطة منع العجز</button></div><div id="dccInsights" class="dcc-insights"></div>`;
      const banner=q('decisionBanner'); if(banner)dash.insertBefore(box,banner); else dash.prepend(box);
    }
    if(!q('quickAddFab')){
      const fab=document.createElement('button');fab.id='quickAddFab';fab.className='quick-add-fab';fab.innerHTML='<span>＋</span> إدخال سريع';document.body.appendChild(fab);
      const modal=document.createElement('div');modal.id='quickAddModal';modal.className='qa-modal hidden';modal.innerHTML=`<div class="qa-card"><div class="qa-head"><div><h3>إدخال سريع</h3><p>مكان واحد لكل ما يغيّر الخطة</p></div><button id="qaClose">×</button></div><div class="qa-types"><button class="active" data-qa-type="expense">مصروف</button><button data-qa-type="income">إيراد</button><button data-qa-type="commitment">التزام قادم</button><button data-qa-type="snapshot">تحديث الأرصدة</button></div><form id="qaForm"><div id="qaDynamic"></div><div class="qa-actions"><button type="submit" class="btn primary">حفظ وإعادة الحساب</button><button type="button" id="qaCancel" class="btn">إلغاء</button></div><div class="qa-note">بعد الحفظ يعاد حساب المتاح الآمن، فجوة السيولة، والاستثمار والتقاعد.</div></form></div>`;document.body.appendChild(modal);
    }
    if(!q('rescueModal')){const m=document.createElement('div');m.id='rescueModal';m.className='qa-modal hidden';m.innerHTML='<div class="qa-card rescue-card"><div class="qa-head"><div><h3>خطة منع العجز</h3><p>مقتبسة من Auto-Rescue v22 ومقيدة بأرقام v26</p></div><button id="rescueClose">×</button></div><div id="rescueBody"></div></div>';document.body.appendChild(m)}
    renderQaFields('expense');bindOnce();
  }
  function bindOnce(){if(window.__wealthDccBound)return;window.__wealthDccBound=true;
    document.addEventListener('click',e=>{const t=e.target.closest('[data-dcc-tab]');if(t){switchTab(t.dataset.dccTab);window.scrollTo({top:0,behavior:'smooth'})}});
    q('dccRefresh')?.addEventListener('click',loadIntel);q('dccTaskBtn')?.addEventListener('click',()=>{const tab=intel?.daily?.task?.tab||'dashboard';switchTab(tab)});q('dccRescueBtn')?.addEventListener('click',openRescue);
    q('quickAddFab')?.addEventListener('click',()=>q('quickAddModal').classList.remove('hidden'));q('qaClose')?.addEventListener('click',closeQa);q('qaCancel')?.addEventListener('click',closeQa);q('quickAddModal')?.addEventListener('click',e=>{if(e.target===q('quickAddModal'))closeQa()});
    document.querySelectorAll('[data-qa-type]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-qa-type]').forEach(x=>x.classList.toggle('active',x===b));renderQaFields(b.dataset.qaType)}));
    q('qaForm')?.addEventListener('submit',submitQuickAdd);q('rescueClose')?.addEventListener('click',()=>q('rescueModal').classList.add('hidden'));q('rescueModal')?.addEventListener('click',e=>{if(e.target===q('rescueModal'))q('rescueModal').classList.add('hidden')});
  }
  function closeQa(){q('quickAddModal')?.classList.add('hidden')}
  function activeQaType(){return document.querySelector('[data-qa-type].active')?.dataset.qaType||'expense'}
  function renderQaFields(type){const d=q('qaDynamic');if(!d)return;const date=new Date().toISOString().slice(0,10);if(type==='expense')d.innerHTML=`<div class="qa-field hero"><label>المبلغ</label><input id="qaAmount" inputmode="decimal" placeholder="0.00"></div><div class="qa-row"><div class="qa-field"><label>التاجر / الوصف</label><input id="qaDesc" placeholder="مثال: تميمي"></div><div class="qa-field"><label>وسيلة الدفع</label><select id="qaRail"><option>Visa</option><option>Mada</option><option>Cash</option><option>Transfer</option></select></div></div><div class="qa-row"><div class="qa-field"><label>الفئة</label><select id="qaCategory"><option value="Groceries">بقالة</option><option value="Fuel">وقود</option><option value="Dining/Coffee">مطاعم وقهوة</option><option value="Personal">شخصي</option><option value="Bills">فواتير</option><option value="School">مدرسة</option><option value="Car">سيارة</option><option value="Medical">صحة</option><option value="Other">أخرى</option></select></div><div class="qa-field"><label>التاريخ</label><input id="qaDate" type="date" value="${date}"></div></div>`;
    else if(type==='income')d.innerHTML=`<div class="qa-field hero"><label>المبلغ</label><input id="qaAmount" inputmode="decimal" placeholder="0.00"></div><div class="qa-row"><div class="qa-field"><label>المصدر</label><input id="qaDesc" placeholder="مثال: براء"></div><div class="qa-field"><label>الحالة</label><select id="qaIncomeStatus"><option value="expected">متوقع</option><option value="confirmed">مؤكد</option><option value="collected">محصل فعليًا</option></select></div></div><div class="qa-row"><div class="qa-field"><label>الفئة</label><input id="qaCategoryText" placeholder="دخل إضافي"></div><div class="qa-field"><label>التاريخ</label><input id="qaDate" type="date" value="${date}"></div></div>`;
    else if(type==='commitment')d.innerHTML=`<div class="qa-field hero"><label>المبلغ</label><input id="qaAmount" inputmode="decimal" placeholder="0.00"></div><div class="qa-row"><div class="qa-field"><label>الالتزام</label><input id="qaDesc" placeholder="مثال: قسط عقار"></div><div class="qa-field"><label>التاريخ</label><input id="qaDate" type="date" value="${date}"></div></div><div class="qa-row"><div class="qa-field"><label>الفئة</label><select id="qaCategory"><option value="Property payment">دفعة عقار</option><option value="School">مدرسة</option><option value="Debt payoff">سداد دين</option><option value="Car repair">سيارة</option><option value="Other">أخرى</option></select></div><div class="qa-field"><label>الحالة</label><select id="qaCommitStatus"><option value="confirmed">مؤكد</option><option value="pending">معلق/غير محدد</option></select></div></div>`;
    else d.innerHTML=`<div class="qa-row"><div class="qa-field hero"><label>رصيد البنك</label><input id="qaBank" inputmode="decimal" value="${Number(data?.settings?.bank_balance||0)}"></div><div class="qa-field hero"><label>إجمالي الفيزا الحالي</label><input id="qaVisa" inputmode="decimal" value="${Number(data?.settings?.visa_pay_all||0)}"></div></div><p class="qa-warning">حدّثهما من القيم الفعلية فقط. النظام سيعيد حساب الدورة الجديدة والمتاح الآمن.</p>`;
    setTimeout(()=>q('qaAmount')?.focus(),80)
  }
  async function submitQuickAdd(e){e.preventDefault();const type=activeQaType();const submit=e.submitter;if(submit)submit.disabled=true;try{
    if(type==='expense'){const amount=Number(q('qaAmount').value),desc=q('qaDesc').value.trim();if(!(amount>0)||!desc)throw new Error('أدخل المبلغ والوصف');await api('transactions',{method:'POST',body:JSON.stringify({amount,merchant:desc,description:desc,rail:q('qaRail').value,category:q('qaCategory').value,happened_at:(q('qaDate').value||new Date().toISOString().slice(0,10))+'T12:00:00+03:00',reviewed:true})})}
    else if(type==='income'){const amount=Number(q('qaAmount').value),description=q('qaDesc').value.trim(),event_date=q('qaDate').value,status=q('qaIncomeStatus').value,category=q('qaCategoryText').value.trim()||'Special income';if(!(amount>=0)||!description)throw new Error('أدخل المصدر والمبلغ');const created=await revReq('create',{method:'POST',body:JSON.stringify({description,amount,event_date,category,status:status==='collected'?'confirmed':status})});if(status==='collected'&&created?.row?.id)await revReq('collect',{method:'POST',body:JSON.stringify({id:created.row.id,amount,actual_date:event_date||new Date().toISOString().slice(0,10)})})}
    else if(type==='commitment'){const amount=Number(q('qaAmount').value),description=q('qaDesc').value.trim(),event_date=q('qaDate').value,certainty=q('qaCommitStatus').value;if(!(amount>=0)||!description)throw new Error('أدخل الالتزام والمبلغ');await api('events',{method:'POST',body:JSON.stringify({flow:'expense',description,amount,event_date,category:q('qaCategory').value,certainty})})}
    else {const bank=Number(q('qaBank').value),visa=Number(q('qaVisa').value);if(bank<0||visa<0)throw new Error('القيم لا يمكن أن تكون سالبة');await api('settings',{method:'PATCH',body:JSON.stringify({bank_balance:bank,visa_pay_all:visa})})}
    closeQa();await loadAll();await loadIntel();
  }catch(err){alert(err.message||String(err))}finally{if(submit)submit.disabled=false}}
  function renderIntel(){if(!intel)return;const d=intel.daily||{},s=intel.snapshot||{};q('dccHeadline').textContent=d.headline||'—';q('dccMessage').textContent=d.message||'—';q('dccStatus').textContent=d.status==='RED'?'أساسيات فقط':d.status==='STOP'?'توقف':d.status==='YELLOW'?'تنبيه':'آمن';q('dccStatus').className='dcc-status '+String(d.status||'').toLowerCase();q('dccSafe').textContent=fmt(s.safe_spend);q('dccCount').textContent=String(d.alerts_count||0);q('dccCritical').textContent=(d.critical_count||0)+' حرج';q('dccInvest').textContent=d.investment_gate==='OPEN'?'مفتوحة':'مقفلة';q('dccTaskTitle').textContent=d.task?.title||'—';q('dccTaskMessage').textContent=d.task?.message||'—';q('dccTaskBtn').textContent='افتح '+(tabAr[d.task?.tab]||'التفاصيل');const arr=(intel.insights||[]).slice(0,4);q('dccInsights').innerHTML=arr.map(x=>`<button class="dcc-insight ${x.severity}" data-dcc-tab="${escX(x.action?.tab||'dashboard')}"><span class="dcc-sev">${sevAr[x.severity]||'معلومة'}</span><div><b>${escX(x.title)}</b><p>${escX(x.message)}</p></div><span class="dcc-arrow">←</span></button>`).join('')||'<div class="empty">لا توجد تنبيهات اليوم</div>';maybeDailyToast()}
  function maybeDailyToast(){const key='wealth_daily_brief_'+new Date().toISOString().slice(0,10);if(localStorage.getItem(key)||!intel)return;localStorage.setItem(key,'1');const t=document.createElement('div');t.className='daily-toast';t.innerHTML=`<b>${escX(intel.daily?.task?.title||'مهمة اليوم')}</b><span>${escX(intel.daily?.task?.message||'')}</span>`;document.body.appendChild(t);setTimeout(()=>t.classList.add('show'),100);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),400)},7000)}
  function openRescue(){if(!intel?.rescue)return;const r=intel.rescue;q('rescueBody').innerHTML=`<div class="rescue-hero"><span>الفجوة القصوى</span><b>${fmt(r.deficit)}</b><small>${escX(r.deficit_month)} · ${r.months_to_gap} شهر حتى الذروة</small></div><div class="rescue-list">${(r.sequence||[]).map(x=>`<div class="rescue-step"><span class="rank">${x.rank}</span><div><b>${escX(x.label)}</b><p>${escX(x.why)}</p>${x.monthly_needed?`<small>المطلوب شهريًا تقريبًا ${fmt(x.monthly_needed)}</small>`:''}</div><strong>${fmt(x.impact)}</strong>${x.conditional?'<em>مشروط</em>':'<em class="direct">مباشر</em>'}</div>`).join('')}</div><div class="rescue-footer">التمويل الخارجي يبقى آخر خيار. Expected لا يُحسب حتى يصل فعليًا.</div>`;q('rescueModal').classList.remove('hidden')}
  async function loadIntel(){if(!token)return;try{intel=await intelReq();renderIntel()}catch(e){console.warn('Daily intelligence',e)}}
  ensureUI();const baseLoadAll=loadAll;loadAll=async function(){const r=await baseLoadAll();await loadIntel();return r};if(token)setTimeout(loadIntel,150);setInterval(()=>{if(document.visibilityState==='visible'&&token)loadIntel()},2*60*1000);
})();
