(function(){
  const SAL=ROOT+'/wealth-salary-api';
  let salaryData={items:[],summary:{},settings:{}};
  let editingItem=null;
  const q=id=>document.getElementById(id);
  const fmt=n=>'SAR '+new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
  const nf=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
  const escS=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const catAr={Fixed:'ثابت',Staff:'رواتب ومساعدة منزلية',Bills:'فواتير',Family:'العائلة',Fuel:'وقود',Groceries:'مقاضي',Personal:'شخصي',Other:'أخرى'};
  const labelAr={loan:'قسط البنك',wafaa_salary:'راتب وفاء',maids:'العاملتان',driver:'السائق',redha:'رضا',aileen:'أيلين',mobile:'الجوال',internet:'الإنترنت',electricity:'الكهرباء',personal:'المصروف الشخصي',family_fuel:'بنزين سيارة العائلة',groceries:'المقاضي الأساسية',daily_groceries:'المقاضي اليومية / الخفيفة'};
  const cadenceAr={monthly:'شهري',weekly:'أسبوعي',daily:'يومي'};
  function itemLabel(x){return labelAr[x.key]||x.label||x.key||'بند'}
  async function req(action,opts={}){const headers={'content-type':'application/json'};if(token)headers.authorization='Bearer '+token;const r=await fetch(SAL+'/'+action,{...opts,headers});let x={};try{x=await r.json()}catch{}if(r.status===401)throw new Error('unauthorized');if(!r.ok)throw new Error(x.error||'تعذر تنفيذ العملية');return x}
  function ensureUI(){
    const nav=q('sideNav');if(nav&&!nav.querySelector('[data-tab="salary"]')){const b=document.createElement('button');b.dataset.tab='salary';b.innerHTML='<span>﷼</span>الراتب';const first=nav.querySelector('[data-tab="transactions"]');nav.insertBefore(b,first||null)}
    const content=document.querySelector('.content');if(content&&!q('salary')){const sec=document.createElement('section');sec.id='salary';sec.className='page salary-page';sec.innerHTML=`
      <div class="page-head salary-page-head"><div><h1>الراتب</h1><p>وزّع الراتب قبل الصرف. أي تعديل هنا يعيد حساب العجز والاستثمار والتقاعد مباشرة.</p></div><div class="salary-head-actions"><button id="editSalaryBtn" class="btn">تعديل الراتب</button><button id="addSalaryItemBtn" class="btn primary">+ إضافة بند</button></div></div>
      <div class="salary-hero-grid">
        <article class="salary-hero-card"><span class="salary-kicker">الراتب الشهري</span><div class="salary-hero-value" id="salaryPageAmount">—</div><small id="salaryPageDays">—</small><div class="salary-stack" id="salaryStack"></div><div class="salary-stack-legend" id="salaryStackLegend"></div></article>
        <article class="salary-decision-card" id="salaryDecisionCard"><span>قرار الراتب</span><h2 id="salaryDecisionTitle">جارٍ الحساب...</h2><p id="salaryDecisionText">—</p><div class="salary-decision-metrics"><div><span>المتاح الحر بعد حماية الالتزامات</span><b id="salaryFree">—</b></div><div><span>بوابة الاستثمار</span><b id="salaryInvestGate">—</b></div></div></article>
      </div>
      <div class="summary-grid four salary-summary-grid"><div class="stat-card"><span>التشغيل الشهري</span><b id="salaryOperating">—</b><small id="salaryOperatingPct">—</small></div><div class="stat-card"><span>الفائض الأولي</span><b id="salaryResidual">—</b><small>قبل الالتزامات المستقبلية</small></div><div class="stat-card warning"><span>هدف حماية 6 أشهر</span><b id="salarySinking">—</b><small>لمنع العجز القادم</small></div><div class="stat-card danger"><span>فجوة التخصيص</span><b id="salaryAllocationGap">—</b><small>ما ينقص الراتب للوصول للحماية المطلوبة</small></div></div>
      <div class="salary-plan-grid">
        <article class="card salary-waterfall"><div class="card-title-row"><div><h3>ترتيب يوم الراتب</h3><small>من الأهم إلى الأقل — الاستثمار يأتي أخيرًا</small></div><span id="salaryStatusChip" class="mini-badge">—</span></div><div id="salaryWaterfall" class="salary-waterfall-list"></div></article>
        <article class="card salary-ynab"><div class="card-title-row"><div><h3>توزيع الراتب</h3><small>مستوحى من Envelope / YNAB لكن بقواعد Wealth OS</small></div></div><div id="salaryAllocationCards" class="salary-allocation-cards"></div></article>
      </div>
      <div class="section-title salary-items-title"><div><h2>بنود الراتب والتشغيل</h2><p>تعديل، إضافة أو حذف أي بند. المبلغ الشهري المكافئ هو ما يدخل المحرك.</p></div><div class="toolbar small"><input id="salarySearch" placeholder="بحث في البنود"><select id="salaryCategoryFilter"><option value="all">كل الفئات</option></select><select id="salaryStatusFilter"><option value="active">النشطة</option><option value="all">الكل</option><option value="inactive">الموقوفة</option></select></div></div>
      <div class="table-card salary-table-wrap"><table><thead><tr><th>البند</th><th>الفئة</th><th>الدورية</th><th>المبلغ</th><th>المكافئ الشهري</th><th>الأولوية</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody id="salaryRows"></tbody></table></div>
      <div class="salary-footnote">قاعدة المحرك: الدخل المتوقع لا يموّل هذه البنود. إذا كانت فجوة FALLBACK أكبر من صفر فبوابة الاستثمار تبقى مقفلة مهما كان الفائض الظاهر.</div>`;
      const dashboard=q('dashboard');if(dashboard)dashboard.after(sec);else content.prepend(sec)
    }
    if(!q('salaryItemModal')){const m=document.createElement('div');m.id='salaryItemModal';m.className='modal hidden';m.innerHTML=`<div class="modal-card salary-modal-card"><div class="modal-head"><h3 id="salaryModalTitle">إضافة بند</h3><button id="closeSalaryModal" class="icon-btn">×</button></div><div class="salary-form-grid"><label class="field"><span>اسم البند</span><input id="salaryItemLabel"></label><label class="field"><span>المبلغ</span><input id="salaryItemAmount" inputmode="decimal"></label><label class="field"><span>الدورية</span><select id="salaryItemCadence"><option value="monthly">شهري</option><option value="weekly">أسبوعي</option><option value="daily">يومي</option></select></label><label class="field"><span>الفئة</span><select id="salaryItemCategory"><option value="Fixed">ثابت</option><option value="Staff">رواتب ومساعدة منزلية</option><option value="Bills">فواتير</option><option value="Family">العائلة</option><option value="Fuel">وقود</option><option value="Groceries">مقاضي</option><option value="Personal">شخصي</option><option value="Other">أخرى</option></select></label><label class="field check-field"><input id="salaryItemEssential" type="checkbox"><span>بند أساسي</span></label><label class="field check-field"><input id="salaryItemActive" type="checkbox" checked><span>نشط في الخطة</span></label><label class="field salary-notes-field"><span>ملاحظات</span><input id="salaryItemNotes"></label></div><div class="form-actions"><button id="saveSalaryItem" class="btn primary">حفظ وإعادة الحساب</button><button id="deleteSalaryItem" class="btn salary-delete hidden">حذف البند</button><button id="cancelSalaryItem" class="btn">إلغاء</button></div></div>`;document.body.appendChild(m)}
    if(!q('salaryAmountModal')){const m=document.createElement('div');m.id='salaryAmountModal';m.className='modal hidden';m.innerHTML=`<div class="modal-card salary-amount-card"><div class="modal-head"><h3>تعديل الراتب الشهري</h3><button id="closeSalaryAmount" class="icon-btn">×</button></div><label class="field"><span>الراتب الفعلي الشهري</span><input id="salaryAmountInput" inputmode="decimal"></label><p class="salary-modal-note">بعد الحفظ يعيد النظام حساب التشغيل، الفائض، فجوة السيولة، بوابة الاستثمار والتقاعد.</p><button id="saveSalaryAmount" class="btn primary wide">حفظ وإعادة الحساب</button></div>`;document.body.appendChild(m)}
    bindOnce();
  }
  function bindOnce(){if(window.__salaryBound)return;window.__salaryBound=true;
    q('addSalaryItemBtn')?.addEventListener('click',()=>openItem());q('editSalaryBtn')?.addEventListener('click',openSalaryAmount);q('closeSalaryModal')?.addEventListener('click',closeItem);q('cancelSalaryItem')?.addEventListener('click',closeItem);q('saveSalaryItem')?.addEventListener('click',saveItem);q('deleteSalaryItem')?.addEventListener('click',deleteItem);q('closeSalaryAmount')?.addEventListener('click',()=>q('salaryAmountModal').classList.add('hidden'));q('saveSalaryAmount')?.addEventListener('click',saveSalaryAmount);
    q('salaryRows')?.addEventListener('click',e=>{const b=e.target.closest('[data-salary-edit]');if(!b)return;const x=salaryData.items.find(r=>r.id===b.dataset.salaryEdit);if(x)openItem(x)});
    ['salarySearch','salaryCategoryFilter'].forEach(id=>q(id)?.addEventListener(id==='salarySearch'?'input':'change',renderRows));q('salaryStatusFilter')?.addEventListener('change',renderRows);
    q('salaryItemModal')?.addEventListener('click',e=>{if(e.target===q('salaryItemModal'))closeItem()});q('salaryAmountModal')?.addEventListener('click',e=>{if(e.target===q('salaryAmountModal'))q('salaryAmountModal').classList.add('hidden')});
  }
  function openSalaryAmount(){q('salaryAmountInput').value=salaryData.settings?.salary||data?.settings?.salary||'';q('salaryAmountModal').classList.remove('hidden');setTimeout(()=>q('salaryAmountInput')?.focus(),70)}
  function openItem(x=null){editingItem=x;setText('salaryModalTitle',x?'تعديل بند الراتب':'إضافة بند جديد');q('salaryItemLabel').value=x?itemLabel(x):'';q('salaryItemAmount').value=x?.amount??'';q('salaryItemCadence').value=x?.cadence||'monthly';q('salaryItemCategory').value=x?.category||'Other';q('salaryItemEssential').checked=Boolean(x?.essential);q('salaryItemActive').checked=x?x.active!==false:true;q('salaryItemNotes').value=x?.notes||'';q('deleteSalaryItem').classList.toggle('hidden',!x);q('salaryItemModal').classList.remove('hidden');setTimeout(()=>q('salaryItemLabel')?.focus(),70)}
  function closeItem(){q('salaryItemModal')?.classList.add('hidden');editingItem=null}
  function setText(id,v){const e=q(id);if(e)e.textContent=v}
  function monthlyPct(v){const salary=Number(salaryData.summary?.salary||1);return salary>0?Math.max(0,Number(v||0))/salary:0}
  function populateFilters(){const f=q('salaryCategoryFilter');if(!f)return;const cur=f.value||'all';const cats=[...new Set((salaryData.items||[]).map(x=>x.category||'Other'))].sort();f.innerHTML='<option value="all">كل الفئات</option>'+cats.map(c=>`<option value="${escS(c)}">${escS(catAr[c]||c)}</option>`).join('');f.value=[...f.options].some(o=>o.value===cur)?cur:'all'}
  function renderSummary(){const s=salaryData.summary||{},st=salaryData.settings||{};setText('salaryPageAmount',fmt(s.salary));setText('salaryPageDays',`${nf(st.days_to_salary||0)} يوم حتى الراتب القادم`);setText('salaryOperating',fmt(s.operating_total));setText('salaryOperatingPct',`${nf(monthlyPct(s.operating_total)*100)}% من الراتب`);setText('salaryResidual',fmt(s.base_residual));setText('salarySinking',fmt(s.sinking_target_6m));setText('salaryAllocationGap',fmt(s.allocation_gap));setText('salaryFree',fmt(s.free_after_sinking));setText('salaryInvestGate',s.investment_allowed>0&&s.max_fallback_gap<=0?'مفتوحة':'مقفلة');setText('salaryStatusChip',s.status==='GREEN'?'آمن':s.status==='YELLOW'?'تنبيه':s.status==='STOP'?'توقف':'أساسيات فقط');
    const card=q('salaryDecisionCard');if(card){const safe=s.allocation_gap<=0&&s.max_fallback_gap<=0;card.className='salary-decision-card '+(safe?'safe':'alert');setText('salaryDecisionTitle',safe?'الراتب يغطي الحماية الحالية':'لا تعتبر الفائض مالًا حرًا');setText('salaryDecisionText',safe?`بعد التشغيل والحماية يتبقى ${fmt(s.free_after_sinking)} قابل للتوجيه وفق قواعد الاستثمار.`:`الفائض الأولي ${fmt(s.base_residual)} أقل من هدف حماية الالتزامات ${fmt(s.sinking_target_6m)}. فجوة التخصيص ${fmt(s.allocation_gap)}، لذلك الاستثمار الجديد مقفل.`)}
    const parts=[['القرض',s.loan,'#5c7cfa'],['الثوابت',s.fixed_ex_loan,'#2fbf91'],['المتغير',s.variable,'#f59f00'],['الفائض الأولي',Math.max(0,s.base_residual),'#9c6ade']];const total=Math.max(1,Number(s.salary||0));const stack=q('salaryStack');if(stack)stack.innerHTML=parts.map(([label,v,color])=>`<i title="${label} ${fmt(v)}" style="width:${Math.max(0,Number(v))/total*100}%;background:${color}"></i>`).join('');const legend=q('salaryStackLegend');if(legend)legend.innerHTML=parts.map(([label,v,color])=>`<span><i style="background:${color}"></i>${label}<b>${fmt(v)}</b></span>`).join('');
    const waterfall=q('salaryWaterfall');if(waterfall){const rows=[['1','سداد/حجز كشف البطاقة المستحق',st.visa_statement_paid?0:Number(st.visa_statement_due||0),'قبل أي صرف جديد'],['2','قسط البنك',s.loan,'التزام ثابت'],['3','الثوابت والرواتب والفواتير',s.fixed_ex_loan,'لا تؤجل دون قرار'],['4','ظرف المعيشة المتغير',s.variable,'سقف لا هدف للصرف'],['5','حماية الالتزامات القادمة',s.sinking_target_6m,'تعالج فجوة الأشهر القادمة'],['6','الاستثمار',s.investment_allowed,'فقط بعد صفر فجوة وسيولة آمنة']];waterfall.innerHTML=rows.map(r=>`<div class="salary-step"><span>${r[0]}</span><div><b>${r[1]}</b><small>${r[3]}</small></div><strong>${fmt(r[2])}</strong></div>`).join('')}
    const alloc=q('salaryAllocationCards');if(alloc){const rows=[['القرض',s.loan,monthlyPct(s.loan)],['ثوابت بدون القرض',s.fixed_ex_loan,monthlyPct(s.fixed_ex_loan)],['متغير',s.variable,monthlyPct(s.variable)],['فائض أولي',Math.max(0,s.base_residual),monthlyPct(Math.max(0,s.base_residual))]];alloc.innerHTML=rows.map(([label,v,p])=>`<div class="salary-alloc"><div><span>${label}</span><b>${fmt(v)}</b></div><div class="salary-alloc-track"><i style="width:${Math.min(100,Number(p)*100)}%"></i></div><small>${nf(Number(p)*100)}%</small></div>`).join('')}
  }
  function filtered(){let arr=[...(salaryData.items||[])];const search=String(q('salarySearch')?.value||'').toLowerCase(),cat=q('salaryCategoryFilter')?.value||'all',status=q('salaryStatusFilter')?.value||'active';if(search)arr=arr.filter(x=>[itemLabel(x),x.label,x.category,x.notes].some(v=>String(v||'').toLowerCase().includes(search)));if(cat!=='all')arr=arr.filter(x=>(x.category||'Other')===cat);if(status==='active')arr=arr.filter(x=>x.active!==false);else if(status==='inactive')arr=arr.filter(x=>x.active===false);return arr.sort((a,b)=>Number(b.monthly_equivalent||0)-Number(a.monthly_equivalent||0))}
  function renderRows(){const body=q('salaryRows');if(!body)return;const arr=filtered();body.innerHTML=arr.length?arr.map(x=>`<tr class="${x.active===false?'salary-inactive':''}"><td><b>${escS(itemLabel(x))}</b><small class="subline">${escS(x.notes||x.key||'')}</small></td><td><span class="tag">${escS(catAr[x.category]||x.category||'أخرى')}</span></td><td>${escS(cadenceAr[x.cadence]||x.cadence||'شهري')}</td><td class="amount">${fmt(x.amount)}</td><td class="amount"><b>${fmt(x.monthly_equivalent)}</b></td><td>${x.essential?'<span class="salary-essential">أساسي</span>':'<span class="salary-optional">مرن</span>'}</td><td>${x.active!==false?'<span class="tag ok">نشط</span>':'<span class="tag">موقوف</span>'}</td><td><button class="edit-btn" data-salary-edit="${escS(x.id)}">تعديل</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">لا توجد بنود تطابق الفلتر</td></tr>'}
  function render(){populateFilters();renderSummary();renderRows()}
  async function loadSalary(){if(!token)return;try{salaryData=await req('summary');render()}catch(e){if(e.message!=='unauthorized')console.warn('Salary load',e)}}
  async function saveSalaryAmount(){const v=Number(q('salaryAmountInput').value);if(!(v>0)){alert('أدخل راتبًا صحيحًا');return}const b=q('saveSalaryAmount');b.disabled=true;try{await req('salary',{method:'PATCH',body:JSON.stringify({salary:v})});q('salaryAmountModal').classList.add('hidden');await loadAll();await loadSalary()}catch(e){alert(e.message||String(e))}finally{b.disabled=false}}
  async function saveItem(){const label=q('salaryItemLabel').value.trim(),amount=Number(q('salaryItemAmount').value);if(!label||!Number.isFinite(amount)||amount<0){alert('أدخل اسم البند ومبلغًا صحيحًا');return}const payload={label,amount,cadence:q('salaryItemCadence').value,category:q('salaryItemCategory').value,essential:q('salaryItemEssential').checked,active:q('salaryItemActive').checked,notes:q('salaryItemNotes').value.trim()||null};const b=q('saveSalaryItem');b.disabled=true;try{if(editingItem)await req('item',{method:'PATCH',body:JSON.stringify({id:editingItem.id,...payload})});else await req('item',{method:'POST',body:JSON.stringify(payload)});closeItem();await loadAll();await loadSalary()}catch(e){alert(e.message||String(e))}finally{b.disabled=false}}
  async function deleteItem(){if(!editingItem)return;if(!confirm(`حذف بند «${itemLabel(editingItem)}»؟ سيُعاد حساب الخطة فورًا.`))return;const b=q('deleteSalaryItem');b.disabled=true;try{await req('item',{method:'DELETE',body:JSON.stringify({id:editingItem.id})});closeItem();await loadAll();await loadSalary()}catch(e){alert(e.message||String(e))}finally{b.disabled=false}}
  ensureUI();
  const baseSwitch=switchTab;switchTab=function(tab){if(tab==='salary'){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='salary'));document.querySelectorAll('#sideNav button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='salary'));if(q('pageTitle'))q('pageTitle').textContent='الراتب';if(q('pageSubtitle'))q('pageSubtitle').textContent='توزيع الراتب وبنوده من مكان واحد';loadSalary();return}return baseSwitch(tab)};
  if(typeof globalIndex==='function'){const baseIndex=globalIndex;globalIndex=function(){const out=baseIndex();(salaryData.items||[]).forEach(x=>out.push({tab:'salary',title:itemLabel(x),sub:`${catAr[x.category]||x.category||''} · ${fmt(x.monthly_equivalent)}`}));return out}}
  const baseLoad=loadAll;loadAll=async function(){const r=await baseLoad();setTimeout(loadSalary,100);return r};
  setTimeout(loadSalary,600);q('refreshBtn')?.addEventListener('click',()=>setTimeout(loadSalary,350));
})();