(function(){
  const V22=ROOT+'/wealth-v22-api';
  let v22=null;
  const q=id=>document.getElementById(id);
  const fmt=n=>'SAR '+new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
  const pct=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(Number(n||0)*100)+'%';
  const escV=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const monthName=s=>{const m=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];const d=new Date(String(s||'')+'T00:00:00Z');return Number.isNaN(d.getTime())?String(s||'—'):`${m[d.getUTCMonth()]} ${d.getUTCFullYear()}`};
  async function loadV22(){if(!token)return;try{const r=await fetch(V22+'/summary',{headers:{authorization:'Bearer '+token,'content-type':'application/json'}});const x=await r.json();if(!r.ok)throw new Error(x.error||'تعذر تحميل أدوات v22');v22=x;ensureV22UI();renderV22();maybeCriticalNotification()}catch(e){console.warn('v22 merge',e)}}
  function ensureV22UI(){
    const dash=q('dashboard');if(dash&&!q('v22DecisionLayer')){
      const sec=document.createElement('section');sec.id='v22DecisionLayer';sec.className='v22-decision-layer';sec.innerHTML=`
        <div class="v22-section-head"><div><span>طبقة القرار</span><h2>الصحة المالية والتوقع النقدي</h2><p>أدوات مختارة من AdeebFamily v22، لكن الحسابات تأتي من Excel v26 ومحرك FALLBACK الحالي.</p></div><span class="v22-source">v22 UX · v26 أرقام</span></div>
        <div class="v22-grid">
          <article class="v22-card v22-health"><div class="v22-card-head"><div><span>مؤشر الصحة المالية</span><b id="v22HealthSummary">—</b></div><div id="v22HealthRing" class="v22-health-ring"><strong id="v22HealthScore">—</strong><small>/100</small></div></div><div id="v22HealthFactors" class="v22-health-factors"></div></article>
          <article class="v22-card v22-growth"><div class="v22-card-head"><div><span>محرك بناء الثروة</span><b id="v22GrowthGate">—</b></div></div><div class="v22-growth-main"><div><span>السائل الآن</span><b id="v22CurrentLiquid">—</b></div><div class="v22-arrow">←</div><div><span>المتوقع عند 50</span><b id="v22FutureLiquid">—</b></div></div><div class="v22-growth-meta"><div><span>مضاعف النمو</span><b id="v22GrowthMultiple">—</b></div><div><span>تغطية التقاعد</span><b id="v22RetCoverage">—</b></div><div><span>أكبر فجوة آمنة</span><b id="v22MaxGap">—</b></div></div><p id="v22GrowthRule" class="v22-rule">—</p></article>
        </div>
        <article class="v22-card v22-cashflow"><div class="v22-card-head"><div><span>توقع السيولة</span><b>12 شهرًا — السيناريو الآمن</b></div><button class="v22-link" data-v22-tab="plan">فتح الخطة</button></div><div id="v22CashflowChart" class="v22-cashflow-chart"></div><div id="v22CashflowStrip" class="v22-cashflow-strip"></div></article>`;
      const dcc=q('dailyCommandCenter');if(dcc)dcc.after(sec);else dash.prepend(sec);
    }
    const qa=document.querySelector('.qa-types');if(qa&&!qa.querySelector('[data-qa-type="investment"]')){
      const b=document.createElement('button');b.type='button';b.dataset.qaType='investment';b.textContent='استثمار';qa.appendChild(b);b.addEventListener('click',()=>{qa.querySelectorAll('[data-qa-type]').forEach(x=>x.classList.toggle('active',x===b));renderInvestmentQuickAdd()});
    }
    const head=document.querySelector('.dcc-head-actions');if(head&&!q('enableBrowserAlerts')){const b=document.createElement('button');b.id='enableBrowserAlerts';b.className='dcc-icon v22-bell';b.title='تفعيل تنبيهات المتصفح';b.textContent='🔔';b.addEventListener('click',enableNotifications);head.prepend(b)}
    if(!window.__v22MergeBound){window.__v22MergeBound=true;document.addEventListener('click',e=>{const b=e.target.closest('[data-v22-tab]');if(b) switchTab(b.dataset.v22Tab)});const form=q('qaForm');if(form)form.addEventListener('submit',interceptInvestmentSubmit,true);q('refreshBtn')?.addEventListener('click',()=>setTimeout(loadV22,500));q('syncNowBtn')?.addEventListener('click',()=>setTimeout(loadV22,500));}
  }
  function renderInvestmentQuickAdd(){const d=q('qaDynamic');if(!d)return;const rows=investmentData?.rows||[];d.innerHTML=`<div class="qa-field"><label>الاستثمار</label><select id="qaInvestmentId">${rows.map(x=>`<option value="${escV(x.id)}">${escV(x.platform||'')} · ${escV(x.asset||'')}</option>`).join('')}</select></div><div class="qa-field hero"><label>القيمة السوقية الحالية بالريال</label><input id="qaInvestmentValue" inputmode="decimal" placeholder="0.00"></div><p class="qa-warning">هذا تحديث للقيمة فقط، وليس أمر شراء. الاستثمار الجديد يبقى مقفلاً ما دامت فجوة FALLBACK أكبر من صفر.</p>`;setTimeout(()=>q('qaInvestmentValue')?.focus(),60)}
  async function interceptInvestmentSubmit(e){const active=document.querySelector('[data-qa-type].active')?.dataset.qaType;if(active!=='investment')return;e.preventDefault();e.stopImmediatePropagation();const id=q('qaInvestmentId')?.value,value=Number(q('qaInvestmentValue')?.value);if(!id||!Number.isFinite(value)||value<0){alert('اختر الاستثمار وأدخل قيمة صحيحة');return}const submit=e.submitter;if(submit)submit.disabled=true;try{await extra('investment',{method:'PATCH',body:JSON.stringify({id,market_value_sar:value})});q('quickAddModal')?.classList.add('hidden');await loadAll();await loadV22()}catch(err){alert(err.message||String(err))}finally{if(submit)submit.disabled=false}}
  function renderV22(){if(!v22)return;const h=v22.health||{},g=v22.growth||{},cf=v22.cashflow||[];q('v22HealthScore').textContent=Math.round(Number(h.overall||0));q('v22HealthSummary').textContent=h.summary||'—';const ring=q('v22HealthRing');if(ring){ring.style.setProperty('--health',Math.max(0,Math.min(100,Number(h.overall||0))));ring.className='v22-health-ring '+(h.status||'warning')}
    q('v22HealthFactors').innerHTML=(h.factors||[]).map(f=>`<div class="v22-factor"><div><b>${escV(f.label)}</b><span>${Math.round(Number(f.score||0))}/100 · وزن ${f.weight}%</span></div><div class="v22-factor-track"><i style="width:${Math.max(0,Math.min(100,Number(f.score||0)))}%"></i></div><small>${escV(f.detail)}</small></div>`).join('');
    const open=g.investment_gate==='OPEN';q('v22GrowthGate').textContent=open?'بوابة الاستثمار مفتوحة':'بوابة الاستثمار مقفلة';q('v22GrowthGate').className=open?'v22-open':'v22-locked';q('v22CurrentLiquid').textContent=fmt(g.current_liquid);q('v22FutureLiquid').textContent=fmt(g.projected_liquid);q('v22GrowthMultiple').textContent=new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(Number(g.multiple||0))+'×';q('v22RetCoverage').textContent=pct(g.retirement_coverage);q('v22MaxGap').textContent=fmt(g.max_gap);q('v22GrowthRule').textContent=open?'فائضك مؤهل للاستثمار وفق قواعد السيولة والمخاطر.':'الأولوية الآن: صفر عجز + سيولة محمية. لا يوصي النظام بضخ استثمار جديد قبل فتح البوابة.';renderCashflow(cf)}
  function renderCashflow(rows){const box=q('v22CashflowChart'),strip=q('v22CashflowStrip');if(!box||!strip)return;if(!rows.length){box.innerHTML='<div class="empty">لا توجد توقعات</div>';return}const vals=rows.map(x=>Number(x.end_cash||0)),max=Math.max(1,...vals.map(Math.abs));box.innerHTML=rows.map(x=>{const v=Number(x.end_cash||0),gap=Number(x.gap||0),h=Math.max(5,Math.min(100,Math.abs(v)/max*100));return `<button class="v22-cf-col ${gap>0?'gap':''}" title="${escV(monthName(x.month))}: ${fmt(v)}"><span>${fmt(v)}</span><i style="height:${h}%"></i><b>${escV(monthName(x.month).split(' ')[0].slice(0,4))}</b></button>`}).join('');const worst=[...rows].sort((a,b)=>Number(b.gap||0)-Number(a.gap||0))[0];strip.innerHTML=`<div><span>أقل رصيد/أعلى ضغط</span><b>${fmt(worst?.end_cash)}</b><small>${monthName(worst?.month)}</small></div><div><span>فجوة خلال 12 شهر</span><b>${fmt(Math.max(...rows.map(x=>Number(x.gap||0))))}</b></div><div><span>استثمار تلقائي خلال 12 شهر</span><b>${fmt(rows.reduce((z,x)=>z+Number(x.investment||0),0))}</b></div>`}
  async function enableNotifications(){if(!('Notification' in window)){alert('المتصفح لا يدعم التنبيهات');return}const p=await Notification.requestPermission();q('enableBrowserAlerts').textContent=p==='granted'?'🔔✓':'🔕';if(p==='granted')maybeCriticalNotification()}
  function maybeCriticalNotification(){if(!v22||!('Notification' in window)||Notification.permission!=='granted')return;const critical=(v22.intelligence?.insights||[]).find(x=>x.severity==='critical');if(!critical)return;const key='wealth_critical_notification_'+new Date().toISOString().slice(0,10)+'_'+critical.id;if(localStorage.getItem(key))return;localStorage.setItem(key,'1');new Notification('Wealth OS — '+critical.title,{body:critical.message,tag:'wealth-os-critical'})}
  const oldLoad=window.loadAll;if(typeof oldLoad==='function')window.loadAll=async function(){const r=await oldLoad.apply(this,arguments);setTimeout(loadV22,120);return r};
  setTimeout(()=>{ensureV22UI();loadV22()},900);setInterval(()=>{if(!document.hidden&&token)loadV22()},120000);
})();