/* iSCARB shared classroom runtime. Authored hints are not AI grading.
 * Source availability, draft completeness, self-report and assessed competence
 * are deliberately different states. No responses are sent to a server.
 */
(()=>{'use strict';
const D=JSON.parse(document.getElementById('lecture-data').textContent),$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=`iscarb:classroom:ch${D.chapter}:v3`,validField=k=>/^[a-z][a-z0-9_]{0,59}$/.test(k)&&!['constructor','prototype','__proto__'].includes(k);
let savedOK=true,state={fields:{},seen:[],quiz:{},ai:{},self:{},theme:'night'},index=0,stationMode=false,quizIndex=0,returnFocus=null;
try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s&&s.schema==='iscarb-classroom-v3'&&s.chapter===D.chapter){state={...state,...sanitize(s).state};}}catch(e){savedOK=false;}
let remaining=180,deadline=0,ticker=null;
const labels={claim:'CLAIM',evidence:'EVIDENCE',warrant:'WARRANT',uncertainty:'UNCERTAINTY',counter:'COUNTER-EVIDENCE',verdict:'VERDICT',owner:'DECISION OWNER',reviewer:'EVIDENCE REVIEWER',signoff:'SIGN-OFF ROLE',initial:'INITIAL DECISION',revision:'REVISED DECISION',ai_disclosure:'AI DISCLOSURE / INDEPENDENT CHECK',constraint:'CONSTRAINT',derive:'DERIVE',principle:'NAME THE PRINCIPLE',prediction:'PREDICT',known:'KNOWN',unknown:'UNKNOWN',monitor:'MONITOR',architecture:'ARCHITECTURE / IMPLEMENTATION',practice:'CONTEMPORARY PRACTICE',workload:'WORKLOAD / HANDOVER',local_context:'LOCAL CONTEXT / AUTHORITY',evidence_gap:'EVIDENCE GAP',self_level:'SELF-PLACEMENT / REASON'};
function pack(){return {schema:'iscarb-classroom-v3',chapter:D.chapter,release:D.release,exportedAt:new Date().toISOString(),state};}
function save(){try{localStorage.setItem(key,JSON.stringify(pack()));savedOK=true;}catch(e){savedOK=false;}$$('[data-save-status]').forEach(e=>e.textContent=savedOK?'Draft saved on this device · not submitted or graded':'Local saving unavailable · export a backup before leaving');}
function field(k,label,ph='',value){return `<label class="field"><span>${esc(label||labels[k]||k)}</span><textarea data-field="${esc(k)}" maxlength="15000" placeholder="${esc(ph)}">${esc(value??state.fields[k]??'')}</textarea></label>`;}
function button(label,open,cls=''){return `<button class="${cls}" data-open="${esc(open)}">${esc(label)}</button>`;}
function jumpButton(k,label){return `<button data-jump="${esc(k)}">${esc(label||titleOf(k))}</button>`;}
function titleOf(k){return D.slides.find(s=>s.id===k)?.title||({RULES:'20-rule map',CARD:'Decision card',READING:'Required source review',QUIZ:'Five-objective practice',READINESS:'NCAAA / Jaheziah',RUBRIC:'Four-level rubric',HSTACK:'H-Stack',PREDICT:'Prediction',MONITOR:'Known / Unknown / Monitor',AI:'AI gate',PORTFOLIO:'Portfolio and assignment',EVIDENCE:'Evidence policy',LOCAL:'Saudi context',PRACTICE:'Contemporary practice',WELLBEING:'Practitioner wellbeing',BRIDGE:'Implementation annotation'}[k]||k);}
function sourceLink(s,label='Open source detail'){let a=s.sourceStart||firstNumber(s.sourceRange)||1;return `<a href="sources/Ch${D.chapter}-Study.html#source-slide-${a}" target="_blank" rel="noopener">${esc(label)}</a>`;}
function firstNumber(s){return Number(String(s||'').match(/\d+/)?.[0]||1);}
function ref(s){return s.sourceLabel|| (s.sourceRange?`Sommerville Ch.${D.chapter} · source slides ${s.sourceRange}`:'Course-created teaching activity · fictional case');}
function points(ps){return `<ul class="points">${(ps||[]).map(p=>`<li><strong>${esc(p[0])}.</strong> ${esc(p[1])}</li>`).join('')}</ul>`;}
function table(v){return `<table class="table-main"><thead><tr>${(v.heads||['CONCEPT','MEANING']).map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${v.rows.map(r=>`<tr>${r.map((x,i)=>`<${i?'td':'th'}${i?'':' scope="row"'}>${esc(x)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table>`;}
function visual(s){if(s.rows)return table(s);if(s.visual?.rows)return table(s.visual);if(s.approaches)return `<div class="two-approaches">${s.approaches.map(a=>`<section class="approach"><h3>${esc(a.label)}</h3><p>${esc(a.title||'')}</p><div class="arrow-chain">${(a.nodes||[]).map(n=>`<span>${esc(n)}</span>`).join('')}</div><p>${esc(a.text||'')}</p></section>`).join('')}</div>`;
if(s.figure)return `<button class="figure-button" data-image="${esc(s.figure)}" data-caption="${esc(s.caption||s.title)}" aria-label="Enlarge figure: ${esc(s.title)}"><img src="${esc(s.figure)}" alt="${esc(s.caption||s.title)}" decoding="async"></button><p class="caption">${esc(s.caption||'Original source figure · select to enlarge')}</p>`;
let ns=s.nodes?.length?s.nodes:(s.bullets||[]).slice(0,3).map(p=>[p[0],'']);return `<div class="concepts ${s.flow?'flow':''}">${ns.map(n=>`<div class="concept"><b>${esc(n[0])}</b>${n[1]?`<span>${esc(n[1])}</span>`:''}</div>`).join('')}</div>`;}
function render(){const s=D.slides[index],stop=D.stations.find(x=>x.at===s.id);$('#chapter-main').className='chapter-main'+(s.fullTable?' full-table':'');
$('#chapter-main').innerHTML=`<div class="heading"><div><p class="ey">${esc(stationMode?'CLASSROOM STATION':s.phase||'LEARN')} · CHAPTER ${D.chapter}</p><h1>${esc(s.id==='TITLE'?'A decision you can explain':s.id==='MAP'?'Chapter mind map':s.title)}</h1></div><span class="counter">${index+1} / ${D.slides.length}</span></div>`;
if(stationMode&&stop){renderStation(stop);updateNav();return;}
if(s.id==='TITLE'){$('#chapter-main').insertAdjacentHTML('beforeend',`<div class="hero"><div><p class="ey">iSCARB · CPIT-455</p><h2>${esc(D.title)}</h2><p>${esc(D.case.headline)}</p><div class="route-tags"><span>SEE</span><span>EXPLAIN</span><span>TEST</span><span>DECIDE</span></div><p class="small">Professor Adeeb Noor · King Abdulaziz University<br>20 classroom slides · five objectives · one evolving artifact</p><div class="actions">${jumpButton('MAP','See the chapter map →')}${button('Resume draft','CARD')}</div></div><img src="${esc(D.brand)}" alt="Approved iSCARB visual identity"></div><p class="scope-note">Classroom and named source review are required. Tools support the same work; they are not 20 extra assignments.</p>`);}
else if(s.id==='MAP'){renderMindMap();}
else if(s.id==='START'){$('#chapter-main').insertAdjacentHTML('beforeend',`<p class="takeaway">${esc(D.case.headline)}</p><div class="body-grid"><div class="case-box"><p class="case-label">Fictional teaching case · not operational advice</p><p>${esc(D.case.text)}</p></div><div class="meaning"><h2>THE DECISION</h2>${points([['Initial view',D.case.question],['Evidence','Separate supplied facts, derived values and missing tests.'],['Return','Revise the same decision when the constraint changes.']])}</div></div><div class="question"><p class="question-text"><b>FIRST RESPONSE</b>State a tentative answer; do not invent measurements.</p><div class="actions">${button('Record initial view','PREDICT','primary')}${button('Five objectives','OBJECTIVES')}</div></div>`);}
else if(s.id==='END'){$('#chapter-main').insertAdjacentHTML('beforeend',`<p class="takeaway">One coherent artifact—not a collection of disconnected answers.</p><div class="body-grid"><div class="concepts"><div class="concept"><b>1 · Explain</b><span>Use the chapter concepts and the exact required source.</span></div><div class="concept"><b>2 · Defend</b><span>Keep the claim, evidence, limits and changed decision together.</span></div><div class="concept"><b>3 · Transfer</b><span>Apply the method to the separate assessed case.</span></div></div><div class="meaning"><h2>BEFORE THE ASSIGNMENT</h2>${points([['Source','Finish the named source review; a citation alone is not explanation.'],['Practice','Check all five objectives and explain a changed example.'],['Backup','Export your classroom card; Blackboard remains the submission system.']])}</div></div><div class="question"><div class="actions">${button('Required reading','READING','primary')}${button('Five-objective practice','QUIZ')}${button('Card / export','CARD')}<a href="../../fbr-submission.html?chapter=${D.chapter}">Open Assignment ${D.assignment}</a></div><p class="small">Do not resubmit an already completed assignment merely because the lecture interface changed.</p></div>`);}
else{$('#chapter-main').insertAdjacentHTML('beforeend',`<p class="takeaway">${esc(s.takeaway||s.title)}</p><div class="body-grid"><div class="visual">${visual(s)}</div><div class="meaning"><h2>WHAT IT MEANS</h2>${points(s.bullets)}</div></div><div class="question"><p class="question-text"><b>APPLY THE IDEA</b>${esc(s.question||'Explain the concept using the teaching case.')}</p><div class="actions"><div class="buttons"><button data-full="${esc(s.id)}">Full explanation</button><button data-answer="${esc(s.id)}">Model answer</button>${stop?`<button class="primary" id="stationBtn">Station ${stop.no} · build the card</button>`:''}</div><span class="source-line">${esc(ref(s))} · ${sourceLink(s)}</span></div></div>`);}
updateNav();}
function updateNav(){$('#prevBtn').disabled=index===0;$('#nextBtn').disabled=index===D.slides.length-1;$('#progress').innerHTML=`${new Set(state.seen).size} / ${D.slides.length} visited · not mastery<span class="nav-shortcuts">Enter → · Backspace ←</span>`;$('#live').textContent=`Slide ${index+1} of ${D.slides.length}: ${D.slides[index].title}`;updateMapLocation();save();}
function go(n,history=true){if(!Number.isInteger(n)||n<0||n>=D.slides.length)return;pauseTimer();stationMode=false;index=n;if(!state.seen.includes(D.slides[index].id))state.seen.push(D.slides[index].id);render();if(history)try{window.history.replaceState(null,'','#'+D.slides[index].id);}catch(e){}if(matchMedia('(max-width:1000px)').matches)window.scrollTo(0,0);}
function jump(k){const aliases=D.aliases||{};k=aliases[k]||k;let n=D.slides.findIndex(s=>s.id===k);closeModal();if(n>=0)go(n);else open(k);}
function modal(title,html){pauseTimer();returnFocus=document.activeElement;$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;$('#modal').hidden=false;$('#modal-close').focus();save();}
function closeModal(){if($('#modal').hidden)return;$('#modal').hidden=true;$('#modal-body').innerHTML='';if(returnFocus?.isConnected)returnFocus.focus();}
function full(k){const s=D.slides.find(x=>x.id===k);if(!s)return;modal('Full explanation · '+s.title,`<div class="callout">${esc(ref(s))}. Source detail remains required; the short classroom bullets do not replace it.</div>${s.full||`<p>${esc(s.explanation||'')}</p>`}${s.extra?`<p>${esc(s.extra)}</p>`:''}<h3>Source and qualifications</h3><p>${sourceLink(s,'Read the original explanation, examples and caveats')}</p><p class="small">Historical examples and terminology are preserved as source material. Course-created scenarios and proposed tests are not reported as measured operational results.</p>`);}
function answer(k){const s=D.slides.find(x=>x.id===k);if(!s)return;modal('Model answer · attempt first',`<p>${esc(s.question)}</p><div class="callout">${esc(s.answer||'A defensible response identifies the mechanism, states its assumptions and names evidence that could support or defeat it.')}</div><p class="small">An illustrative response, not the only acceptable wording or an automatic grade. The assessed assignment uses its own case and commit/reveal sequence.</p>${sourceLink(s)}`);}
function renderStation(st){remaining=st.seconds||180;$('#chapter-main').insertAdjacentHTML('beforeend',`<div class="station"><div class="station-top"><div><p class="ey">STATION ${st.no} / 3 · THE SAME DECISION CARD</p><h2>${esc(st.title)}</h2></div><div class="timer"><output id="timer-output" class="timer-output">03:00</output><button id="timer-start">Start</button><button id="timer-reset">Reset</button></div></div><div class="station-steps"><div><b>THINK · 30 SECONDS</b>${esc(st.think)}</div><div><b>PAIR · 60 SECONDS</b>${esc(st.pair)}</div><div><b>WRITE · 90 SECONDS</b>${esc(st.write)}</div></div><div class="station-fields">${st.fields.map(k=>field(k,labels[k],st.prompts?.[k]||'Use facts, a source concept or a clearly labelled proposed check.')).join('')}</div><div class="hint-box" id="coach">${esc('Authored coach: attempt the task first. A filled box records a draft, not a correct answer.')}</div><div class="actions"><button id="hintBtn" data-no="${st.no}">Hint before the answer</button><button id="station-answer" data-no="${st.no}">Discuss a possible answer</button>${button('Whole card / export','CARD')}<button id="station-back">Return to explanation</button></div><p class="scope-note">${esc(st.note||'Use the same artifact. Discuss reasoning; do not award a level from field length or a timer.')} <span data-save-status></span></p></div>`);timerLabel();}
function timerLabel(){const o=$('#timer-output');if(!o)return;o.textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');$('.timer')?.classList.toggle('over',remaining===0);$('#timer-start').textContent=ticker?'Pause':remaining===0?'Restart':'Start';}
function pauseTimer(){if(ticker){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));clearInterval(ticker);ticker=null;}timerLabel();}
function startTimer(){if(ticker){pauseTimer();return;}if(remaining<=0)remaining=180;deadline=Date.now()+remaining*1000;ticker=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));timerLabel();if(!remaining){pauseTimer();$('#live').textContent='Station time complete. Finish the reasoning; this is not a grade.';}},250);timerLabel();}
function indexModal(){modal('20 classroom slides',`<div class="index-grid">${D.slides.map((s,i)=>`<button data-go="${i}" class="${i===index?'active':''}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(s.id==='MAP'?'Chapter mind map':s.title)}</span></button>`).join('')}</div>`);}
function reading(){modal('Required source review',`<div class="callout"><b>Classroom + named source detail are required.</b> The original source is preserved separately and loads only when opened. Finishing a chapter includes its named review, not only its main-slide count.</div><table><tr><th>Required selection</th><th>Original slide numbers</th><th>Action</th></tr>${D.readings.map(r=>`<tr><td>${esc(r.title)}</td><td>${esc(r.range)}</td><td><a href="sources/Ch${D.chapter}-Study.html#source-slide-${firstNumber(r.range)}" target="_blank" rel="noopener">Read selected source</a></td></tr>`).join('')}</table><h3>Observable work</h3><p>Explain how one named source concept changes or supports your artifact. Keep the source number, reasoning and limit together. A checkbox or a copied quotation alone is not enough.</p><div class="actions">${button('Five-objective practice','QUIZ')}${button('Source-to-lesson map','COVERAGE')}<a href="sources/Ch${D.chapter}-Study.html">All original slides and textbook reference</a></div><p class="small">Calendar deadlines and grade contributions remain in Blackboard. Toolkit extensions are optional unless assigned. Do not repeat an already completed submission under this edition.</p>`);}
function coverage(){modal('Source-to-lesson map',`<div class="callout">A map of content availability—not a claim that it was taught, read or mastered. Source slide numbers and textbook PDF pages are separately labelled.</div><table><tr><th>Original section</th><th>Source slides</th><th>Classroom locations</th></tr>${D.groups.map(g=>`<tr><td>${esc(g.title)}</td><td>${g.start}–${g.end}</td><td>${g.units.map(k=>jumpButton(k)).join(' ')}</td></tr>`).join('')}</table><p><a href="sources/Ch${D.chapter}-Study.html">Complete source ledger · ${D.sourceCount} original slides</a></p><p><a href="${esc(D.original)}" target="_blank" rel="noopener">Original supplied slide pack</a>${D.textbook?` · <a href="${esc(D.textbook)}" target="_blank" rel="noopener">Original textbook chapter · ${D.bookPages} PDF pages</a>`:''}</p><h3>Original figures</h3><p>The source ledger retains all original source text and links each diagram to its source pack. Preserved diagram assets are available in its figure gallery.</p>`);}
function rules(){modal('The 20 iSCARB rules · canonical map',`<div class="callout">Exact approved headings and order. The links show where a rule is implemented; they do not certify that a student performed it. The three stations build one artifact, not 20 additional assignments.</div><div class="rule-grid">${D.rules.map(r=>`<section class="rule-card" data-rule="${r.no}"><h3><b>${String(r.no).padStart(2,'0')}</b>${esc(r.title)}</h3><p>${esc(r.evidence)}</p><div class="actions">${r.targets.map(k=>button(titleOf(k),k)).join(' ')}</div></section>`).join('')}</div>`);}
function legacyTools(){modal('iSCARB toolkit',`<div class="callout">Use these tools to strengthen the same artifact. Only the classroom stations and named source review are required by default; extra tasks need an explicit instructor assignment.</div><div class="tool-grid">${['RULES','CARD','HSTACK','PREDICT','BRIDGE','MONITOR','LOCAL','PRACTICE','WELLBEING','AI','EVIDENCE','RUBRIC','READINESS','PORTFOLIO'].map(k=>button(titleOf(k),k)).join('')}${D.chapter===11?button('Metric calculator','CALCULATOR'):''}</div>`);}
function card(){modal('One decision card · classroom worksheet',`<div class="callout">Your work is saved locally when storage is available. No cloud sync, grade, LMS submission or operational approval occurs here. The assessed case is separate.</div><div class="two-col">${['claim','evidence','warrant','counter','uncertainty','verdict'].map(k=>field(k,labels[k])).join('')}</div><h3>Revision and responsibility</h3>${field('initial')}${field('revision')}<div class="two-col">${['owner','reviewer','signoff','ai_disclosure'].map(k=>field(k,labels[k])).join('')}</div><div class="actions"><button data-export="json">Export backup · JSON</button><button data-export="md">Export readable card</button><button id="import">Import backup</button><button id="copy">Copy card</button><button id="clear">Clear classroom draft</button></div><p class="status" data-save-status></p><p class="small">Earlier lecture drafts have not been erased. <a href="previous-lectures/Ch${D.chapter}-Previous-Lecture.html" target="_blank" rel="noopener">Open the previous lecture to recover its local draft</a>. Assignment drafts and locked Part A are untouched by this worksheet.</p>`);}
function hstack(){const names=['Analyze','Judge','Evidence','System','Risk','Ethics'];const texts=['Separate the concepts and trace the mechanism.','Compare alternatives under stated constraints.','Connect the claim to a source or inspectable result.','Follow interfaces, dependencies and operating context.','State uncertainty, counter-evidence and fallback.','Disclose assistance and name human responsibility.'];modal('Six H-Stack capabilities',`<p>The approved course capability vocabulary—not a national classification or an automatic score.</p><table><tr><th>Capability</th><th>Visible in your chapter artifact</th></tr>${names.map((x,i)=>`<tr><th>${x}</th><td>${texts[i]}</td></tr>`).join('')}</table>${button('Review the card','CARD')}`);}
function predict(){modal('Predict → Constraint → Derive → Name',`<div class="callout">${esc(D.case.text)}</div>${field('initial','INITIAL DECISION','Your tentative decision before the explanation.')}${field('prediction')}${field('constraint','CONSTRAINT','What operating condition limits this answer?')}${field('derive','DERIVE','Why does the mechanism support your prediction? Show units if calculating.')}${field('principle','NAME','Name the source concept you used.')}<p class="small">Keep the original view and write later changes under revision. This is reflective practice, not a secure assessment lock.</p>`);}
function bridge(){modal('Architecture / implementation structure',`<p>${esc(D.bridge)}</p>${field('architecture','IMPLEMENTATION ANNOTATION','Input / component / interface → decision or transformation → output / fallback. Name one shared dependency.')}${field('evidence_gap','VERIFICATION ARTIFACT','The actual or proposed test, model, table or trace that checks this implementation.')}<div class="actions">${jumpButton(D.mechanism,'Return to the chapter mechanism')}${button('Evidence policy','EVIDENCE')}</div>`);}
function monitor(){modal('Known / Unknown / Monitor',`${field('known','KNOWN','Only supplied source/case facts and derived calculations.')}${field('unknown','UNKNOWN','The missing condition, dependency or unexecuted check.')}${field('monitor','MONITOR','Quantity or event + window + proposed/approved trigger + owner + action.')}<p class="small">A proposed threshold is not an observed result or an approved operating limit.</p>`);}
function local(){modal('Saudi-aligned engineering context',`<p>This is a fictional teaching context, not a description of a live KAU system. Identify the actual service owner, affected users, language/access needs and authority before applying the argument to a real organization.</p>${field('local_context','LOCAL CONSTRAINT → EVIDENCE → EFFECT','Which institutional document, version or owner establishes this constraint? How would it change the chapter artifact?')}${field('owner')}${field('signoff')}<p class="small">No regulatory approval, national compliance or official mapping is inferred from a Saudi setting.</p>`);}
function practice(){modal('Trend / contemporary practice',`<p>Connect a source mechanism to a tool or workflow you have actually used. This is an evidence-seeking exercise, not a claim that the textbook’s historical examples are the latest standard.</p>${field('practice','CURRENT PRACTICE → SOURCE → VERSIONED ARTIFACT',D.practice)}<p class="small">Name the tool/version and authoritative documentation date. Keep an untested suggestion labelled proposed.</p>`);}
function wellbeing(){modal('Practitioner wellbeing as a system variable',`<p>${esc(D.workload)}</p>${field('workload','WORKLOAD / HANDOVER → DESIGN CHANGE → CHECK','Identify an operator burden, a feasible change and evidence that would evaluate it.')}<p class="small">The course exercise treats workload as a design variable; it does not diagnose a person or claim a measured wellbeing effect.</p>`);}
function aiVerdict(a){if(a[0]===undefined)return 'Record whether the output enters the evidence chain.';if(a[0]==='no')return 'Preparation only: check factual claims and disclose assistance; do not file generated text as verified evidence.';if(a[3]==='no')return 'Not permitted as assurance evidence: named human review is missing.';if(a[1]==='no'&&a[2]==='no')return 'Not permitted as assurance evidence: neither independent re-derivation nor testing is available.';if(a[3]!=='yes')return 'Incomplete: identify the responsible human review.';if(a[1]==='yes')return 'Conditionally permitted under the course policy: retain the independent derivation and named review.';if(a[2]==='yes')return 'Conditionally permitted: retain the independently executed test and its result, not the generated answer alone.';return 'Incomplete: establish an independent checking route.';}
function ai(){const qs=['Will this output enter the evidence chain?','Can its relevant result be independently re-derived?','Can its relevant claim be independently tested?','Is a named human responsible for review and sign-off?'];modal('Critical AI literacy · permissibility gate',`<p>Use only authorized, non-sensitive teaching inputs. No AI service is called by this page.</p>${qs.map((q,i)=>`<div class="ai-row"><span>${i+1}. ${esc(q)}</span>${['yes','no'].map(v=>`<button data-ai="${i}" data-value="${v}" aria-pressed="${state.ai[i]===v}">${v==='yes'?'Yes':'No'}</button>`).join('')}</div>`).join('')}<div id="ai-result" class="result" role="status">${esc(aiVerdict(state.ai))}</div>${field('ai_disclosure','ASSISTANCE + INDEPENDENT CHECK + HUMAN OWNER','No AI used, or describe the assistance, check and review.')}`);}
function evidence(){modal('Evidence policy / proof of capability',`<table><tr><th>Evidence type</th><th>Required honest record</th></tr><tr><td>Source explanation</td><td>Exact source/slide/page, relevant meaning and limitations.</td></tr><tr><td>Fictional case input</td><td>Label as supplied teaching data—not live operational measurement.</td></tr><tr><td>Derived result</td><td>Inputs, method/formula, units, independent arithmetic and scope.</td></tr><tr><td>Proposed test</td><td>Unexecuted plan, expected result, owner and conditions.</td></tr><tr><td>Executed test</td><td>Actual version, inputs, date, log, outcome and reviewer.</td></tr><tr><td>AI assistance</td><td>Disclosure and independent verification; not authority by itself.</td></tr></table><p>Opening pages is not learning evidence by itself. Field completeness is not correctness. A plan is not a passed test.</p>${field('evidence_gap')}`);}
function rubric(){const rows=[['L1 · Asserting','Names a decision but lacks sufficient mechanism or inspectable support.'],['L2 · Reasoning','Explains a relevant mechanism and source concept; major evidence remains missing.'],['L3 · Justifying','Provides a checkable artifact, counter-evidence and explicit assumptions/limits.'],['L4 · Accountable','Defends a revision under the changed constraint and names review and decision responsibility.']];modal('Four-level capability rubric',`<table><tr><th>Level</th><th>What a reviewer examines</th></tr>${rows.map(r=>`<tr><th>${r[0]}</th><td>${r[1]}</td></tr>`).join('')}</table>${field('self_level','PROVISIONAL SELF-PLACEMENT + REASON','Use the descriptor and identify the next evidence gap.')}<p class="small">Descriptors support human review. The assignment retains its published raw-point rubric; no grade or level is awarded automatically by this lecture.</p>`);}
function readiness(){modal('NCAAA / Jaheziah readiness',`<div class="callout warning"><b>Required practice; official mapping is not asserted.</b> The supplied sources do not establish an approved program mapping for these authored chapter objectives. Exact national codes, exam weights and attainment are not invented.</div><table><tr><th>Chapter objective</th><th>Practice evidence</th><th>Assignment field / opportunity</th></tr>${D.objectives.map((o,i)=>`<tr><td><b>CLO ${i+1}</b> ${esc(o)}</td><td>${esc(D.alignment[i].evidence)}</td><td>${esc(D.alignment[i].field)}</td></tr>`).join('')}</table><p>Candidate domains are knowledge, skills, and values/responsibility. The program must approve the formal crosswalk. These opportunities do not mean one multiple-choice item certifies an outcome.</p><div class="actions">${button('Five-objective practice','QUIZ')}${button('Four-level rubric','RUBRIC')}${button('Card','CARD')}</div>`);}
function portfolio(){modal('One portfolio artifact · transfer to the assignment',`<p>${esc(D.artifact)}</p><ol><li>Explain the chapter-specific concept using the named source.</li><li>Build the requested technical artifact; do not invent executed tests.</li><li>State counter-evidence, uncertainty and a bounded decision.</li><li>Retain the initial view and justify a revision when the constraint changes.</li></ol><div class="callout">The three classroom stations feed one practice card. The separate assignment keeps its own case, existing ${D.points}-point rubric, commit/reveal sequence and Blackboard deadline. Do not add another full report merely to satisfy the 20 rules.</div><div class="actions"><a href="../../fbr-submission.html?chapter=${D.chapter}">Open Assignment ${D.assignment}</a>${button('Card / export','CARD')}${button('Outcome crosswalk','READINESS')}</div>`);}
function quiz(){const q=D.quiz[quizIndex],r=state.quiz[quizIndex]||{};modal(`Five-objective practice · CLO ${quizIndex+1}`,`<div class="quiz-dots">${D.quiz.map((_,i)=>`<button data-quiz="${i}" class="${i===quizIndex?'active':''}">${i+1}</button>`).join('')}</div><p><b>${esc(q.q)}</b></p><div class="quiz-options">${q.options.map((o,i)=>`<label><input type="radio" name="quiz" value="${i}" ${r.answer===i?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div><div class="actions" style="margin-top:16px"><button id="quiz-check" class="primary">Check after attempting</button><button data-quiz="${Math.min(4,quizIndex+1)}" ${quizIndex===4?'disabled':''}>Next objective</button></div><div id="quiz-feedback" role="status" hidden></div><p class="small" style="margin-top:15px">Course-authored formative practice, not official exam questions or a secure assessment. One correct response does not establish mastery.</p>`);if(r.checked)quizFeedback();}
function quizFeedback(){const r=state.quiz[quizIndex],q=D.quiz[quizIndex],b=$('#quiz-feedback');b.hidden=false;b.className='feedback'+(r?.answer===q.answer?'':' wrong');b.textContent=(r?.answer===q.answer?'Correct for this case. ':'Review this distinction. ')+q.why;}
function calculator(){modal('Reliability metric calculator · observed ratios',`<div class="callout">Define the failure event and exposure. These are observed estimates, not a reliability certificate. The chapter’s reciprocal-rate convention for MTTF is used.</div><div class="two-col">${[['demands','Demands',10000],['failed','Failed demands',20],['events','Outage events',2],['time','Service window (hours)',1000],['down','Unavailable hours',1]].map(([k,l,v])=>`<label class="field"><span>${l}</span><input id="calc-${k}" type="number" min="0" step="any" value="${v}"></label>`).join('')}</div><button id="calculate">Calculate with units</button><div id="calc-result" class="result" role="status"></div><p class="small">Do not compare a rate per hour to a probability per demand without the relevant denominator. Zero observed events are not proof of infinite reliability.</p>`);compute();}
function compute(){const vs=['demands','failed','events','time','down'].map(k=>$('#calc-'+k)?.value);const b=$('#calc-result');if(vs.some(x=>x===undefined||x.trim()==='')){b.textContent='Enter every value; a blank is not zero.';return;}const [n,f,e,t,d]=vs.map(Number);if(![n,f,e,t,d].every(Number.isFinite)||n<=0||t<=0||f<0||f>n||e<0||d<0||d>t||![n,f,e].every(Number.isInteger)){b.textContent='Invalid observations: positive demand/window; whole non-negative counts; failed ≤ demands; downtime ≤ window.';return;}const fmt=n=>Number(n.toPrecision(8));b.innerHTML=`<p>POFOD estimate = ${f}/${n} = <b>${fmt(f/n)} per demand</b></p><p>ROCOF = ${e}/${t} = <b>${fmt(e/t)} outage events/hour</b></p><p>Reciprocal-rate MTTF = <b>${e?fmt(t/e)+' hours':'not estimable from zero observed events'}</b></p><p>AVAIL = (${t}−${d})/${t} = <b>${fmt(100*(t-d)/t)}%</b></p>`;}
function notes(){const s=D.slides[index];modal('Instructor notes · '+s.title,`<p>${esc(s.notes||'Ask students to distinguish the source concept, the mechanism and its operating assumptions. Attempt before revealing; use the named source for detail rather than shrinking the main slide.')}</p><h3>Teaching move</h3><p>Use the three stations to develop one artifact. Sample reasoning orally. If a source topic is not finished, announce the precise required review rather than making it optional.</p><p>${esc(ref(s))}</p>${sourceLink(s)}`);}
function help(){modal('Navigation, sources and saving',`<p>Start at the cover, then the Chapter mind map on slide 2. Use Chapter map to return, Slides to jump, and Study &amp; tools for required review, your card, methodology and display settings.</p><table><tr><th>Enter / Backspace</th><td>Next / previous classroom slide. On a focused button or link, Enter activates that control.</td></tr><tr><th>Mouse click / Shift + click</th><td>Next / previous on non-interactive slide content in desktop presentation mode. Dragging to select text does not navigate.</td></tr><tr><th>← / →</th><td>Previous / next classroom slide.</td></tr><tr><th>Home / End</th><td>First / final slide.</td></tr><tr><th>O / C / N</th><td>Slide index / decision card / instructor notes.</td></tr><tr><th>Escape</th><td>Close a dialog; typing fields do not trigger navigation.</td></tr></table><p>Desktop uses presentation layout; reading mode and smaller screens reflow content. Sources open separately on demand. Keep the accompanying runtime/assets folders when using an offline ZIP.</p><p>Classroom drafts are local. Export JSON to restore them, or Markdown to read them. The assessed assignment preserves its own identity, draft storage and commitment rules.</p><div class="actions">${button('Source coverage','COVERAGE')}${button('Export card','CARD')}</div>`);}
// Mind-map v1: source concepts and student workflow are distinct layers.
// This is an authored learning organizer, not an original textbook figure.
function renderMindMap(){
 const r=D.roadmap, next=D.slides[2].id;
 $('#chapter-main').classList.add('mindmap-page');
 const wires='<svg class="mind-wires" viewBox="0 0 1000 300" preserveAspectRatio="none" aria-hidden="true"><path d="M374 135 C342 135 350 50 310 50"/><path d="M374 165 C342 165 350 250 310 250"/><path d="M626 120 C652 120 650 50 690 50"/><path d="M626 150 L690 150"/><path d="M626 180 C652 180 650 250 690 250"/></svg>';
 $('#chapter-main').insertAdjacentHTML('beforeend',`<div class="mindmap-board" aria-label="Chapter concepts and their relationships">${wires}<div class="mind-centre"><span class="mind-kicker">CHAPTER ${D.chapter} · THE BIG QUESTION</span><h2>${esc(r.question)}</h2><span class="mind-chapter">${esc(D.title)}</span></div>${r.branches.map((b,i)=>`<button class="mind-branch branch-${i+1}" data-jump="${esc(b.target)}" aria-label="${esc(b.label)}: ${esc(b.verb)}. Open the related lesson."><span class="mind-verb">${i+1} · ${esc(b.verb)}</span><strong>${esc(b.label)}</strong><span class="mind-detail">${esc(b.detail)}</span></button>`).join('')}</div><p class="mind-link"><b>HOW THE IDEAS CONNECT</b> ${esc(r.connection)}</p><div class="student-roadmap" aria-label="Instructor and student roles"><section class="road-stage"><h3><span>01</span> In class</h3><p><b>Instructor:</b> Explain and guide three stations.</p><p><b>You:</b> ${esc(r.inClass)}</p><p class="road-result">Keep one evolving practice card.</p></section><section class="road-stage"><h3><span>02</span> Required review</h3><p><b>Instructor:</b> Specify source reading.</p><p><b>You:</b> Source slides ${D.readings.map(x=>esc(x.range)).join(' + ')}; then five practice questions.</p><p class="road-result">Explain the idea before checking the answer.</p></section><section class="road-stage"><h3><span>03</span> Assignment ${D.assignment}</h3><p><b>Instructor:</b> Review with the published rubric.</p><p><b>You:</b> ${esc(r.deliverable)}</p><p class="road-result">New case → commit → STRESS → REFIT → Blackboard.</p></section></div><div class="map-bottom"><p><b>REQUIRED:</b> Class + named review + assignment. Other tools support the work; no extra tasks unless assigned.</p><div class="actions"><button data-open="OBJECTIVES">Five objectives</button>${jumpButton(next,'Start learning →')}</div></div>`);
}
function mapObjectives(){
 modal('Five chapter objectives · source outline',`<div class="callout">The mind map groups the existing source concepts for learning. It does not replace the five objectives, original sections or assigned source review.</div><ol class="objective-list">${D.objectives.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>Original chapter spine</h3><ul>${D.sections.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Check your understanding</h3><p>${esc(D.roadmap.success)}</p><h3>Our fictional classroom case</h3><p>${esc(D.case.text)}</p><p><b>${esc(D.case.question)}</b></p><div class="actions">${jumpButton('MAP','Back to chapter map')}${button('Five-objective practice','QUIZ')}</div>`);
}
function studyTools(){
 modal('Study & tools',`<p class="callout">Follow the main slides first. Required review and the assignment are clearly marked below. The other tools support the same work—not another set of assignments.</p><div class="study-groups"><section><h3>In class · one practice card</h3><div class="tool-grid">${button('Decision card / save a backup','CARD')}${button('Five objectives & source outline','OBJECTIVES')}${button('Instructor notes for this slide','NOTES')}${D.chapter===11?button('Reliability metric calculator','CALCULATOR'):''}</div></section><section><h3>Required after class</h3><div class="tool-grid">${button('Required self-study','READING')}${button('Five-objective practice','QUIZ')}<a class="tool-link" href="../../fbr-submission.html?chapter=${D.chapter}">Assignment ${D.assignment} · separate case</a>${button('Assignment artifact & workflow','PORTFOLIO')}</div><p class="small">Blackboard gives dates and confirms submission. A local draft is not submitted work.</p></section><section><h3>Sources, methodology & support</h3><div class="tool-grid">${button('20 iSCARB rules','RULES')}${button('Source-to-lesson coverage','COVERAGE')}${button('NCAAA / Jaheziah practice','READINESS')}${button('AI use & independent checking','AI')}</div><details class="tool-details"><summary>More iSCARB tools · use when relevant or assigned</summary><div class="tool-grid">${['HSTACK','PREDICT','BRIDGE','MONITOR','LOCAL','PRACTICE','WELLBEING','EVIDENCE','RUBRIC'].map(k=>button(titleOf(k),k)).join('')}</div></details></section><section><h3>Display</h3><div class="actions"><button id="themeBtn">Day / night</button><button id="fullBtn">Fullscreen</button>${button('Navigation and saving help','HELP')}</div></section></div>`);
}
function updateMapLocation(){
 const s=D.slides[index],r=D.roadmap,b=r.branches.find(x=>x.units.includes(s.id)),label=$('#topic-location');
 if(label)label.textContent=s.id==='MAP'?'Your overview':s.id==='TITLE'?'Start here':b?b.label:stationMode?'Practice station':'Case and learning path';
 const mapButton=$('#mapBtn');if(mapButton)mapButton.setAttribute('aria-current',s.id==='MAP'?'step':'false');
}

function open(k){k=(D.aliases||{})[k]||k;if(D.slides.some(s=>s.id===k)){jump(k);return;}const aliases={PREP:'QUIZ',C01:'COVERAGE',J01:'READINESS',J02:'QUIZ',AIGATE:'AI',READING:'READING'};k=aliases[k]||k;({UNITS:indexModal,READING:reading,COVERAGE:coverage,RULES:rules,TOOLS:studyTools,OBJECTIVES:mapObjectives,CARD:card,HSTACK:hstack,PREDICT:predict,BRIDGE:bridge,MONITOR:monitor,LOCAL:local,PRACTICE:practice,WELLBEING:wellbeing,AI:ai,EVIDENCE:evidence,RUBRIC:rubric,READINESS:readiness,PORTFOLIO:portfolio,QUIZ:quiz,CALCULATOR:calculator,HELP:help,NOTES:notes}[k]||(()=>modal('Source or tool',`<p>This earlier unit is available in the complete source review.</p><a href="sources/Ch${D.chapter}-Study.html">Open the source ledger</a>`)))();}
function readable(){return [`# Chapter ${D.chapter}: ${D.title}`,'Professor Adeeb Noor · CPIT-455',`Release ${D.release}`,'Fictional teaching case. Student draft; not a grade, submission or certification.','',...Object.entries(state.fields).flatMap(([k,v])=>['## '+(labels[k]||k),v||'[not entered]','']),'## AI gate',aiVerdict(state.ai)].join('\n');}
function download(text,name,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}
function sanitize(p){if(!p||p.schema!=='iscarb-classroom-v3'||p.chapter!==D.chapter||!p.state)throw Error('This backup belongs to a different chapter or format.');let x=p.state,st={fields:{},seen:[],quiz:{},ai:{},self:{},theme:x.theme==='day'?'day':'night'};for(const [k,v]of Object.entries(x.fields||{})){if(!validField(k)||typeof v!=='string'||v.length>15000)throw Error('Invalid text field.');st.fields[k]=v;}for(const [k,v]of Object.entries(x.quiz||{})){if(!/^[0-4]$/.test(k)||!v||!Number.isInteger(v.answer)||v.answer<0||v.answer>=D.quiz[k].options.length)throw Error('Invalid quiz record.');st.quiz[k]={answer:v.answer,checked:!!v.checked};}for(const[k,v]of Object.entries(x.ai||{})){if(!/^[0-3]$/.test(k)||!['yes','no'].includes(v))throw Error('Invalid AI record.');st.ai[k]=v;}st.seen=(Array.isArray(x.seen)?x.seen:[]).filter(k=>D.slides.some(s=>s.id===k));return {state:st};}
async function restore(file){try{if(file.size>1000000)throw Error('Backup is too large.');const p=sanitize(JSON.parse(await file.text()));if(!confirm('Replace this chapter’s current classroom draft with the imported backup? Assignment work will not change.'))return;state=p.state;save();render();card();}catch(e){modal('Import did not complete',`<p>${esc(e.message)}</p><p>Your existing draft was not changed.</p>`);}}
document.addEventListener('input',e=>{const k=e.target.dataset.field;if(k&&validField(k)){state.fields[k]=e.target.value;save();}});
document.addEventListener('change',e=>{if(e.target.name==='quiz'){state.quiz[quizIndex]={answer:Number(e.target.value),checked:false};save();$('#quiz-feedback').hidden=true;}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){open(b.dataset.open);return;}if(b.dataset.jump){jump(b.dataset.jump);return;}if(b.dataset.go!==undefined){closeModal();go(Number(b.dataset.go));return;}if(b.dataset.full){full(b.dataset.full);return;}if(b.dataset.answer){answer(b.dataset.answer);return;}if(b.dataset.image){modal(b.dataset.caption||'Source figure',`<img class="zoom-figure" src="${esc(b.dataset.image)}" alt="${esc(b.dataset.caption)}"><p class="small">Original figure retained; use the source pack for surrounding explanation.</p>`);return;}if(b.dataset.quiz!==undefined){quizIndex=Number(b.dataset.quiz);quiz();return;}if(b.dataset.ai!==undefined){state.ai[b.dataset.ai]=b.dataset.value;save();$$('[data-ai="'+b.dataset.ai+'"]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.value===b.dataset.value)));$('#ai-result').textContent=aiVerdict(state.ai);return;}if(b.dataset.export){download(b.dataset.export==='json'?JSON.stringify(pack(),null,2):readable(),`Ch${D.chapter}-classroom-${b.dataset.export==='json'?'backup.json':'card.md'}`,b.dataset.export==='json'?'application/json':'text/markdown');return;}
switch(b.id){case 'prevBtn':go(index-1);break;case 'nextBtn':go(index+1);break;case 'modal-close':closeModal();break;case 'stationBtn':stationMode=true;render();break;case 'station-back':pauseTimer();stationMode=false;render();break;case 'timer-start':startTimer();break;case 'timer-reset':pauseTimer();remaining=180;timerLabel();break;case 'hintBtn':{const st=D.stations.find(x=>x.no===Number(b.dataset.no));$('#coach').innerHTML='<b>Authored hint.</b> '+esc(st.hint);break;}case 'station-answer':{const st=D.stations.find(x=>x.no===Number(b.dataset.no));modal('Station discussion · illustrative reasoning',`<p>${esc(st.answer)}</p><p class="small">Check the mechanism and assumptions. This is not an answer to the separately assessed case.</p>`);break;}case 'quiz-check':if(state.quiz[quizIndex]?.answer===undefined){$('#quiz-feedback').hidden=false;$('#quiz-feedback').textContent='Choose an answer before opening feedback.';}else{state.quiz[quizIndex].checked=true;save();quizFeedback();}break;case 'calculate':compute();break;case 'import':{const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>i.files[0]&&restore(i.files[0]);i.click();break;}case 'clear':if(confirm('Clear this chapter’s classroom draft? Export a backup first. Assignment work will not change.')){state.fields={};state.quiz={};state.ai={};save();card();}break;case 'copy':try{await navigator.clipboard.writeText(readable());$('#live').textContent='Card copied.';}catch(e){download(readable(),`Ch${D.chapter}-card.md`,'text/markdown');}break;case 'viewBtn':document.body.classList.toggle('reading');b.setAttribute('aria-pressed',String(document.body.classList.contains('reading')));b.textContent=document.body.classList.contains('reading')?'Presentation':'Reading view';break;case 'themeBtn':state.theme=state.theme==='day'?'night':'day';document.body.classList.toggle('day',state.theme==='day');save();break;case 'fullBtn':try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){$('#live').textContent='Fullscreen was not allowed; normal and reading views remain available.';}break;case 'notesBtn':notes();break;case 'helpBtn':help();break;}
});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal();});

// Navigation v1: native controls/editing win over presentation shortcuts.
const navControl='input,textarea,select,button,a[href],label,summary,audio,video,iframe,[role="button"],[role="textbox"],[role="combobox"],[role="slider"],[data-no-slide-nav]';
function navInteractive(target){return !(target instanceof Element)||target.isContentEditable||!!target.closest(navControl);}
function selectedText(){const s=window.getSelection();return !!(s&&!s.isCollapsed);}
function mousePresentation(){return !stationMode&&$('#modal').hidden&&!document.body.classList.contains('reading')&&matchMedia('(min-width:1001px)').matches;}
let navPointer=null,lastMouseSlide=-Infinity;
$('#chapter-main').addEventListener('pointerdown',e=>{
 navPointer=null;
 if(e.pointerType!=='mouse'||e.button!==0||e.ctrlKey||e.altKey||e.metaKey||!mousePresentation()||navInteractive(e.target))return;
 navPointer={x:e.clientX,y:e.clientY,index,selected:selectedText()};
});
$('#chapter-main').addEventListener('pointercancel',()=>{navPointer=null;});
$('#chapter-main').addEventListener('click',e=>{
 const p=navPointer;navPointer=null;
 if(!p||e.defaultPrevented||e.button!==0||e.detail!==1||e.ctrlKey||e.altKey||e.metaKey||!mousePresentation()||navInteractive(e.target))return;
 if(p.index!==index||p.selected||selectedText()||Math.hypot(e.clientX-p.x,e.clientY-p.y)>8||performance.now()-lastMouseSlide<260)return;
 lastMouseSlide=performance.now();e.preventDefault();go(index+(e.shiftKey?-1:1));
});
$('#prevBtn').title='Previous slide · Backspace or Left arrow';
$('#nextBtn').title='Next slide · Enter or Right arrow';
$('#chapter-main').setAttribute('aria-keyshortcuts','Enter Backspace ArrowLeft ArrowRight Home End');

document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.isComposing||e.ctrlKey||e.altKey||e.metaKey)return;if(!$('#modal').hidden){if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const a=$$('.dialog button,.dialog input,.dialog textarea,.dialog select,.dialog a[href]').filter(x=>!x.disabled&&x.getClientRects().length);if(a.length){if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===a.at(-1)){e.preventDefault();a[0].focus();}}}return;}if(navInteractive(e.target))return;if(e.key==='Enter'||e.key==='Backspace'){if(e.shiftKey)return;e.preventDefault();if(!e.repeat)go(index+(e.key==='Enter'?1:-1));return;}if(e.key==='ArrowRight'){e.preventDefault();go(index+1);}else if(e.key==='ArrowLeft'){e.preventDefault();go(index-1);}else if(e.key==='Home'){e.preventDefault();go(0);}else if(e.key==='End'){e.preventDefault();go(D.slides.length-1);}else if(e.key.toLowerCase()==='o')indexModal();else if(e.key.toLowerCase()==='c')card();else if(e.key.toLowerCase()==='n')notes();});
document.body.classList.toggle('day',state.theme==='day');const hash=location.hash.slice(1);const initial=D.slides.findIndex(s=>s.id===hash);go(initial>=0?initial:0,false);if(hash&&initial<0)open(hash);
window.iscarb={data:D,go,open,jump,full,answer,closeModal,aiVerdict,pack,sanitize,compute,getState:()=>JSON.parse(JSON.stringify(state)),getIndex:()=>index,startStation:no=>{const st=D.stations.find(s=>s.no===no);if(st){go(D.slides.findIndex(s=>s.id===st.at));stationMode=true;render();}},restore};
})();
