(()=>{
const C=window.LEC||(window.LECTURE_V3_DATA&&window.LECTURE_V3_DATA[document.documentElement.dataset.chapter]);if(!C)throw new Error('Missing LEC config');
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=(items,cls='g3')=>`<div class="grid ${cls}">${items.map((x,i)=>`<div class="card ${['mag','teal','sand','violet','green'][i%5]}"><b>${esc(x[0])}</b><p>${esc(x[1])}</p></div>`).join('')}</div>`;
const head=(k,title,sub,pill='SOURCE → JUDGMENT',accent='teal')=>`<div class="head"><div><div class="kicker ${accent}">${esc(k)}</div><div class="pill">${esc(pill)}</div><h1 class="title">${esc(title)}</h1>${sub?`<p class="sub">${esc(sub)}</p>`:''}</div><div class="count"></div></div>`;
const wrap=(meta,body,task='Explain it before you advance.',align='')=>`<section class="slide" data-title="${esc(meta.title)}" data-phase="${meta.phase}">${head(meta.kicker,meta.title,meta.sub,meta.pill,meta.accent)}<div class="content ${align}">${body}</div><div class="speaker">${esc(meta.notes||'')}</div><div class="task" hidden>${esc(task)}</div></section>`;
function sourceDiagram(f,i){const items=(f.look||[]).slice(0,4),type=f.visualType||['taxonomy','process','layers','network','evidence','process'][i%6];if(type==='layers')return `<div class="vdiag layers">${items.map((x,j)=>`<div style="--n:${j}"><b>${j+1}</b><span>${esc(x)}</span></div>`).join('')}</div>`;if(type==='process')return `<div class="vdiag process">${items.map((x,j)=>`<div><b>${j+1}</b><span>${esc(x)}</span></div>${j<items.length-1?'<i>→</i>':''}`).join('')}</div>`;if(type==='network')return `<div class="vdiag network"><div class="hub">${esc(f.title)}</div>${items.map((x,j)=>`<div class="sat s${j+1}">${esc(x)}</div>`).join('')}</div>`;if(type==='evidence')return `<div class="vdiag evidence"><div class="claim">${esc(f.insight)}</div><div class="egrid">${items.map((x,j)=>`<div><b>E${j+1}</b><span>${esc(x)}</span></div>`).join('')}</div></div>`;return `<div class="vdiag taxonomy"><div class="root">${esc(f.title)}</div><div class="branches">${items.map((x,j)=>`<div><b>${j+1}</b><span>${esc(x)}</span></div>`).join('')}</div></div>`;}
function figureSlide(f,i){return wrap({phase:1,kicker:`SOURCE-DERIVED DIAGRAM ${i+1}`,title:f.title,sub:'Redrawn from the course source for projection clarity. Terminology and relationships follow the cited source page.',pill:`${C.sourceShort} · p. ${f.page}`,accent:i%2?'sand':'teal'},`<div class="figureGrid"><div class="figureNotes"><div class="bigLead">${esc(f.insight)}</div><div class="look">${f.look.map((x,j)=>`<div><em>${j+1}</em><span>${esc(x)}</span></div>`).join('')}</div></div><figure class="sourceFigure vector">${sourceDiagram(f,i)}<figcaption>SOURCE-DERIVED DIAGRAM · ${esc(C.sourceShort)} · page ${esc(f.page)}</figcaption></figure></div>`,f.task||'Point to the relationship in the diagram and explain it in your own words.');}
const flow=`<div class="flow">${[['1','CRISIS','What can go wrong?'],['2','MAP','Where does it live?'],['3','TRADE-OFF','What do we gain/lose?'],['4','EVIDENCE','What can be inspected?'],['5','VERDICT','What is justified now?']].map(x=>`<div class="node"><em>${x[0]}</em><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div>`;
let slides=[];
slides.push(`<section class="slide cover" data-title="${esc(C.title)}" data-phase="0"><div class="content"><div class="heroGrid"><div class="heroCopy"><div class="kicker mag">ISCARB · CPIT-455 · ${esc(C.week)}</div><h1 class="title">${esc(C.title)}</h1><p class="sub">${esc(C.coverLine)}</p><div class="sourceTag"><b>PRIMARY SOURCE</b><br>${esc(C.source)}</div><div class="flowline">CRISIS → MAP → TRADE-OFF → EVIDENCE → VERDICT</div></div><div class="heroArt"><img src="${C.hero}" alt="ISCARB camel caravan and Saudi fort visual identity"></div></div></div><div class="speaker">${esc(C.coverNotes)}</div><div class="task" hidden>${esc(C.coverTask)}</div></section>`);
slides.push(wrap({phase:0,kicker:'CRISIS / COMMIT FIRST',title:C.crisisTitle,sub:C.crisisScenario,pill:'VERBAL ONLY · 90 SEC',accent:'mag',notes:C.crisisNotes},cards([['Your call',C.crisisCall],['What you know',C.crisisKnown],['What you do not know',C.crisisUnknown]],'g3'),'State a provisional verdict and one reason.'));
slides.push(wrap({phase:0,kicker:'PREDICT / BEFORE THE SOURCE',title:'Commit before the reveal',sub:'A useful prediction exposes the assumption you are about to test.',pill:'NO SOURCE YET',accent:'sand'},`<div class="statement">${esc(C.prediction)}</div>`,'Give one answer now. You may revise it after evidence.'));
slides.push(wrap({phase:0,kicker:'OUTCOMES / CLO',title:'What you must be able to do',sub:C.clo,pill:'OBSERVABLE OUTCOMES',accent:'green'},cards(C.outcomes.map((x,i)=>[`${i+1} · ${x[0]}`,x[1]]),'g4'),'Choose the outcome you expect to find hardest.'));
slides.push(wrap({phase:1,kicker:'SOURCE / DOMAIN SPINE',title:'The chapter spine',sub:'These are the source concepts we must not lose when we simplify for class.',pill:'COVERAGE GATE',accent:'teal'},cards(C.spine.map(x=>[x[0],x[1]]),'g5'),'Name the five source areas before we start.'));
slides.push(figureSlide(C.figures[0],0));slides.push(wrap({phase:1,kicker:'UNDERSTAND / MECHANISM',title:C.conceptTitle,sub:C.conceptSub,pill:'SOURCE CONCEPT',accent:'teal'},cards(C.concepts,'g3'),C.conceptTask));slides.push(figureSlide(C.figures[1],1));
slides.push(wrap({phase:1,kicker:'MAP / MECHANISM CHAIN',title:C.mapTitle,sub:C.mapSub,pill:'DRAW THE CAUSAL PATH',accent:'teal'},`<div class="flow">${C.mapNodes.map((x,i)=>`<div class="node"><em>${i+1}</em><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div>`,C.mapTask));
slides.push(wrap({phase:2,kicker:'TRADE-OFF / DO NOT PICK A SLOGAN',title:C.tradeTitle,sub:C.tradeSub,pill:'COMPARE BEFORE COMMIT',accent:'sand'},cards(C.trade,'g4'),C.tradeTask));slides.push(figureSlide(C.figures[2],2));
slides.push(wrap({phase:2,kicker:'CASE / SOURCE-ALIGNED APPLICATION',title:C.caseTitle,sub:C.caseScenario,pill:'WHAT FAILED IN THE REASONING?',accent:'mag'},cards(C.caseLessons.map((x,i)=>[`Lesson ${i+1}`,x]),'g3'),C.caseTask));slides.push(figureSlide(C.figures[3],3));
slides.push(wrap({phase:2,kicker:'IMPLEMENT / PROCESS',title:C.processTitle,sub:C.processSub,pill:'FROM CONCEPT TO ACTION',accent:'sand'},cards(C.process.map((x,i)=>[`${i+1} · ${x[0]}`,x[1]]),'g4'),C.processTask));
slides.push(wrap({phase:3,kicker:'EVIDENCE / INSPECTABLE',title:C.evidenceTitle,sub:'Evidence must be observable by another professional — not merely asserted.',pill:'EVIDENCE BEFORE CONFIDENCE',accent:'violet'},`<div class="evidenceList">${C.evidence.map(x=>`<div class="ev"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div>`,C.evidenceTask));slides.push(figureSlide(C.figures[4],4));
slides.push(wrap({phase:3,kicker:'DISTINGUISH / COMMON CONFUSIONS',title:C.compareTitle,sub:'Confusing these terms produces weak engineering decisions.',pill:'COMPARE',accent:'violet'},`<table class="compare">${C.compare.map(x=>`<tr><td>${esc(x[0])}</td><td>${esc(x[1])}</td></tr>`).join('')}</table>`,C.compareTask,'topalign'));
slides.push(wrap({phase:3,kicker:'BUILD / DECISION CARD',title:'Draft the professional decision',sub:'Same four fields every week. The chapter changes; the reasoning grammar does not.',pill:'FIT → BOUND → ACT + EVIDENCE',accent:'green'},`<div class="decision"><div class="dc"><b>FIT</b><p>${esc(C.decision.fit)}</p></div><div class="dc"><b>BOUND</b><p>${esc(C.decision.bound)}</p></div><div class="dc"><b>ACT</b><p>${esc(C.decision.act)}</p></div><div class="dc"><b>EVIDENCE</b><p>${esc(C.decision.evidence)}</p></div></div>`,C.decisionTask));
slides.push(wrap({phase:3,kicker:'BOUNDARY / COUNTER-EVIDENCE',title:C.boundaryTitle,sub:'A professional verdict includes the condition that would make it unsafe to keep believing it.',pill:'WHAT WOULD BREAK THE DECISION?',accent:'mag'},cards(C.boundaries.map(x=>[x[0],x[1]]),'g3'),C.boundaryTask));
if(C.figures[5])slides.push(figureSlide(C.figures[5],5));else slides.push(wrap({phase:3,kicker:'SYNTHESIZE / SOURCE COVERAGE',title:'Put the chapter back together',sub:'The point is not to memorize isolated slides. It is to reconnect the mechanisms.',pill:'SYNTHESIS',accent:'teal'},flow,'Explain how the five-step flow uses this chapter’s mechanisms.'));
slides.push(wrap({phase:4,kicker:'AI / HUMAN SIGN-OFF',title:'AI may accelerate evidence. It does not own the verdict.',sub:C.aiSub,pill:'HUMAN ACCOUNTABILITY',accent:'green'},cards([['AI may assist',C.aiAssist],['Human must own',C.humanOwn],['Escalate when',C.aiEscalate]],'g3'),'Name one AI use you would allow and one you would refuse.'));
slides.push(wrap({phase:4,kicker:'RETRIEVE / NO NOTES',title:'Can you reconstruct the chapter?',sub:'Answer aloud before the reveal. Retrieval is the test of usable knowledge.',pill:'60–90 SEC',accent:'sand'},cards(C.retrieval.map((x,i)=>[`Q${i+1}`,x]),'g3'),'Answer all three from memory.'));
slides.push(wrap({phase:4,kicker:'VERDICT / BOUNDED PROFESSIONAL JUDGMENT',title:C.verdictTitle,sub:'A strong answer is short enough to defend and specific enough to inspect.',pill:'HUMAN SIGN-OFF',accent:'green'},`<div class="statement">${esc(C.verdictFrame)}</div>`,C.verdictTask));
slides.push(wrap({phase:4,kicker:'AFTER-CLASS / FBR',title:'Carry the same reasoning grammar into the assignment',sub:`${C.challenge} · ${C.afterTime}`,pill:'FIT → BOUND → ACT + EVIDENCE → STRESS → REFIT',accent:'green'},`<div class="flow">${[['1','FIT','Choose what fits now'],['2','BOUND','State when it stops fitting'],['3','ACT','Write the engineering artifact'],['4','EVIDENCE','Name inspectable proof'],['5','REFIT','Respond after STRESS']].map(x=>`<div class="node"><em>${x[0]}</em><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div>`,'Open After-Class only after you can defend today’s verdict.'));
const stage=$('#stage');stage.insertAdjacentHTML('beforeend',slides.join(''));const ss=[...stage.querySelectorAll('.slide')];window.U=ss.map((s,i)=>({k:`S${String(i+1).padStart(2,'0')}`,title:s.dataset.title||`Slide ${i+1}`}));window.cur=0;
function fitSlide(s){s.classList.remove('compact','compact2');const c=s.querySelector('.content');if(!c)return;if(c.scrollHeight>c.clientHeight+2)s.classList.add('compact');if(c.scrollHeight>c.clientHeight+2)s.classList.add('compact2');}
function updatePhase(){const p=Number(ss[cur]?.dataset.phase||0);document.querySelectorAll('#phase i').forEach((e,i)=>{e.className=i<p?'done':i===p?'on':''});}
window.go=function(i){cur=Math.max(0,Math.min(ss.length-1,Number(i)||0));window.cur=cur;ss.forEach((s,j)=>s.classList.toggle('on',j===cur));const count=ss[cur].querySelector('.count');if(count)count.textContent=`${cur+1} / ${ss.length}`;document.querySelector('#taskBox span').textContent=ss[cur].querySelector('.task')?.textContent||'';document.querySelector('#progress').textContent=`${cur+1}/${ss.length}`;updatePhase();requestAnimationFrame(()=>fitSlide(ss[cur]));};
window.tog=function(name){if(name==='notes'){const p=$('#notesPanel');p.classList.toggle('on');p.innerHTML=p.classList.contains('on')?`<h2>${esc(U[cur].title)} · Instructor notes</h2><p>${esc(ss[cur].querySelector('.speaker')?.textContent||'Use this slide to prompt student reasoning before explaining.')}</p>`:'';}};
function scale(){const r=Math.min(innerWidth/1333,innerHeight/750);stage.style.transform=`scale(${r})`;}addEventListener('resize',scale);scale();go(0);$('#prev').onclick=()=>go(cur-1);$('#next').onclick=()=>go(cur+1);$('#notes').onclick=()=>tog('notes');document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' '){e.preventDefault();go(cur+1)}else if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(cur-1)}else if(e.key.toLowerCase()==='n'){tog('notes')}});window.__LECTURE_V3__={chapter:C.chapter,slides:ss.length,figures:C.figures.length};
})();