// Mind-map v1: source concepts and student workflow are distinct layers.
// This is an authored learning organizer, not an original textbook figure.
function renderMindMap(){
 const r=D.roadmap, next=D.slides[2].id;
 $('#chapter-main').classList.add('mindmap-page');
 const wires='<svg class="mind-wires" viewBox="0 0 1000 300" preserveAspectRatio="none" aria-hidden="true"><path d="M374 135 C342 135 350 50 310 50"/><path d="M374 165 C342 165 350 250 310 250"/><path d="M626 120 C652 120 650 50 690 50"/><path d="M626 150 L690 150"/><path d="M626 180 C652 180 650 250 690 250"/></svg>';
 $('#chapter-main').insertAdjacentHTML('beforeend',`<div class="mindmap-board" aria-label="Chapter concepts and their relationships">${wires}<div class="mind-centre"><span class="mind-kicker">CHAPTER ${D.chapter} · THE BIG QUESTION</span><h2>${esc(r.question)}</h2><span class="mind-chapter">${esc(D.title)}</span></div>${r.branches.map((b,i)=>`<button class="mind-branch branch-${i+1}" data-jump="${esc(b.target)}" aria-label="${esc(b.label)}: ${esc(b.verb)}. Open the related lesson."><span class="mind-verb">${i+1} · ${esc(b.verb)}</span><strong>${esc(b.label)}</strong><span class="mind-detail">${esc(b.detail)}</span></button>`).join('')}</div><p class="mind-link"><b>HOW THE IDEAS CONNECT</b> ${esc(r.connection)}</p><div class="student-roadmap" aria-label="Instructor and student roles"><section class="road-stage"><h3><span>01</span> In class</h3><p><b>Instructor:</b> Explain and guide three stations.</p><p><b>You:</b> ${esc(r.inClass)}</p><p class="road-result">Keep one evolving practice card.</p></section><section class="road-stage"><h3><span>02</span> Required review</h3><p><b>Instructor:</b> Specify source reading.</p><p><b>You:</b> Source slides ${D.readings.map(x=>esc(x.range)).join(' + ')}; then five practice questions.</p><p class="road-result">Explain the idea before checking the answer.</p></section><section class="road-stage"><h3><span>03</span> Assignment ${D.assignment}</h3><p><b>Instructor:</b> Review with the published rubric.</p><p><b>You:</b> ${esc(r.deliverable)}</p><p class="road-result">New case → commit → STRESS → REFIT → Blackboard.</p></section></div><div class="map-bottom"><p><b>REQUIRED:</b> Class + named review + assignment. Other tools support the work; no extra tasks unless assigned.</p><div class="actions"><button data-open="OBJECTIVES">Five objectives</button>${jumpButton(next,'Start learning →')}</div></div>`);
}
function mapObjectives(){
 modal('Five chapter objectives · source outline',`<div class="callout">The mind map groups the existing source concepts for learning. It does not replace the five objectives, original sections or assigned source review.</div><ol class="objective-list">${D.objectives.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>Original chapter spine</h3><ul>${D.sections.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Check your understanding</h3><p>${esc(D.roadmap.success)}</p><h3>Our fictional classroom case</h3><p>${esc(D.case.text)}</p><p><b>${esc(D.case.question)}</b></p><div class="actions">${jumpButton('MAP','Back to chapter map')}${button('Five-objective practice','QUIZ')}</div>`);
}
function studyTools(){
 modal('Study & tools',`<p class="callout">Follow the main slides first. Required review and the assignment are clearly marked below. The other tools support the same work—not another set of assignments.</p><div class="study-groups"><section><h3>In class · one practice card</h3><div class="tool-grid">${button('Decision card / save a backup','CARD')}${button('Five objectives & source outline','OBJECTIVES')}${button('Instructor notes for this slide','NOTES')}${D.chapter===11?button('Reliability metric calculator','CALCULATOR'):''}</div></section><section><h3>Required after class</h3><div class="tool-grid">${button('Required self-study','READING')}${button('Five-objective practice','QUIZ')}<a class="tool-link" href="../../fbr-submission.html?chapter=${D.chapter}">Assignment ${D.assignment} · separate case</a>${button('Assignment artifact & workflow','PORTFOLIO')}</div><p class="small">Blackboard gives dates and confirms submission. A local draft is not submitted work.</p></section><section><h3>Sources, methodology & support</h3><div class="tool-grid">${button('20 iSCARB rules','RULES')}${button('Source-to-lesson coverage','COVERAGE')}${button('NCAAA / Jaheziah practice','READINESS')}${button('AI use & independent checking','AI')}</div><details class="tool-details"><summary>More iSCARB tools · use when relevant or assigned</summary><div class="tool-grid">${['HSTACK','PREDICT','BRIDGE','MONITOR','LOCAL','PRACTICE','WELLBEING','EVIDENCE','RUBRIC'].map(k=>button(titleOf(k),k)).join('')}</div></details></section><section><h3>Display</h3><div class="actions"><button id="themeBtn">Day / night</button><button id="fullBtn">Fullscreen</button>${button('Navigation and saving help','HELP')}</div></section></div>`);
}
function updateMapLocation(){
 const s=D.slides[index],r=D.roadmap,b=r.branches.find(x=>x.units.includes(s.id)),label=$('#topic-location');
 if(label)label.textContent=s.id==='MAP'?'Your overview':s.id==='TITLE'?'Start here':b?b.label:stationMode?'Practice station':'Case and learning path';
 const mapButton=$('#mapBtn');if(mapButton)mapButton.setAttribute('aria-current',s.id==='MAP'?'step':'false');
}
