            ax=x+w; bx=x+w+gap
            html.append(f'<line x1="{ax}" y1="{y+h/2}" x2="{bx}" y2="{y+h/2}" stroke="#DDB27E" stroke-width="3" marker-end="url(#arrow)"/>')
    html.append('<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><polygon points="0 0, 8 3, 0 6" fill="#DDB27E"/></marker></defs>')
    html.append('</svg><div class="cap">ISCARB engineering flow</div></div>')
    return ''.join(html)

def section(ey,pill,title,sub,body,accent='teal',note=''):
    return f'''<section class="slide" data-title="{escape(title)}">
      <div class="top"><div><div class="ey" data-accent="{accent}">{escape(ey)}</div><div class="pill">{escape(pill)}</div><h1>{escape(title)}</h1><p>{escape(sub)}</p></div><div class="count"></div></div>
      <div class="area">{body}</div>
      <div class="speaker">{escape(note)}</div>
    </section>'''

TEMPLATE_HEAD='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap">
<style>
:root{{--bg:#08070C;--panel:#15121C;--panel2:#100E16;--bar:#0C0A11;--line:#2C2534;--line2:#221C29;--ink:#F5F0EA;--dim:#A99E95;--dim2:#6F665F;--sand:#DDB27E;--mag:#F0189A;--teal:#4FC6CB;--violet:#8E7DEA;--green:#4FBF8B;--disp:"Poppins","Segoe UI",sans-serif;--body:"Inter","Segoe UI",sans-serif}}
*{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--ink);font-family:var(--body);overflow:hidden}} button{{font:inherit;color:inherit;background:none;border:none;cursor:pointer}}
#shell{{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;background:var(--bg)}}
#stage{{width:1333px;height:750px;position:relative;overflow:hidden;transform-origin:center center;background:radial-gradient(900px 460px at 84% -8%,rgba(240,24,154,.10),transparent 62%),radial-gradient(760px 420px at 6% 108%,rgba(221,178,126,.07),transparent 60%),var(--bg)}}
#stars{{position:absolute;inset:0;pointer-events:none;opacity:.5;background-image:radial-gradient(1px 1px at 9% 16%,#fff,transparent),radial-gradient(1px 1px at 25% 8%,#fff,transparent),radial-gradient(1px 1px at 39% 19%,#fff,transparent),radial-gradient(1px 1px at 57% 12%,#fff,transparent),radial-gradient(1px 1px at 72% 18%,#fff,transparent),radial-gradient(1px 1px at 86% 9%,#fff,transparent),radial-gradient(1px 1px at 12% 42%,#fff,transparent),radial-gradient(1px 1px at 90% 31%,#fff,transparent)}}
#rail{{position:absolute;top:0;left:0;right:0;height:3px;display:grid;grid-template-columns:repeat(20,1fr);gap:2px;z-index:4}} #rail i{{display:block;background:var(--line2)}} #rail i.on{{background:var(--mag)}}
.slide{{position:absolute;inset:0 0 78px;padding:24px 38px 10px;display:none;flex-direction:column}} .slide.on{{display:flex}}
.top{{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:flex-start;gap:14px}} .ey{{font-size:12px;font-weight:900;letter-spacing:.11em;text-transform:uppercase;color:var(--teal)}} .ey[data-accent=mag]{{color:var(--mag)}} .ey[data-accent=sand]{{color:var(--sand)}} .ey[data-accent=green]{{color:var(--green)}} .ey[data-accent=violet]{{color:var(--violet)}} .pill{{display:inline-block;margin-top:10px;border:1.5px solid currentColor;border-radius:10px;padding:7px 16px;color:var(--sand);font-size:12px;font-weight:900;letter-spacing:.04em}} h1{{font-family:var(--disp);font-size:44px;line-height:1.05;margin:12px 0 0;letter-spacing:-.02em;max-width:23ch}} p{{font-size:18px;color:var(--dim);line-height:1.36;max-width:74ch;margin:8px 0 0}} .count{{font-size:12px;color:var(--dim2);padding-top:6px}}
.area{{flex:1;display:flex;flex-direction:column;justify-content:center;gap:14px;min-height:0;overflow:hidden}} .hero{{font-family:var(--disp);font-size:46px;line-height:1.1;max-width:980px;margin:auto;text-align:center}} .hero span{{display:block;font-family:var(--body);font-size:18px;color:var(--dim);margin-top:18px;line-height:1.35}}
.grid{{display:grid;gap:14px}} .g1{{grid-template-columns:1fr}} .g2{{grid-template-columns:repeat(2,1fr)}} .g3{{grid-template-columns:repeat(3,1fr)}} .g4{{grid-template-columns:repeat(4,1fr)}} .g5{{grid-template-columns:repeat(5,1fr)}}
.card{{border:1.5px solid var(--line);background:linear-gradient(180deg,rgba(255,255,255,.04),rgba(255,255,255,.013));border-radius:16px;padding:16px 18px;display:flex;flex-direction:column;justify-content:flex-start;gap:8px;min-width:0}} .card .lab{{font-size:12px;letter-spacing:.08em;text-transform:uppercase;font-weight:900;color:var(--teal)}} .card .txt{{font-size:21px;line-height:1.32;font-weight:650}} .card .sm{{font-size:15px;line-height:1.42;color:#D8CEC6;font-weight:500}}
.bands .card:nth-child(1) .lab{{color:var(--mag)}} .bands .card:nth-child(2) .lab{{color:var(--teal)}} .bands .card:nth-child(3) .lab{{color:var(--sand)}} .bands .card:nth-child(4) .lab{{color:var(--violet)}} .bands .card:nth-child(5) .lab{{color:var(--green)}}
.row{{display:grid;grid-template-columns:1.1fr .9fr;gap:16px;align-items:stretch}} .wide{{border:1.5px solid var(--line);border-radius:18px;background:var(--panel);padding:18px 20px}} .wide .wlab{{font-size:12px;letter-spacing:.08em;text-transform:uppercase;font-weight:900;color:var(--sand)}} .wide .wlead{{font-size:30px;line-height:1.15;font-family:var(--disp);margin-top:8px}} .wide .wtxt{{font-size:17px;line-height:1.45;color:#DFD6CF;margin-top:10px}}
.illus{{border:1.5px solid var(--line);background:var(--panel);border-radius:18px;padding:14px}} .illus svg{{width:100%;height:auto;display:block}} .cap{{font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--dim2);text-align:center;margin-top:8px}}
.klo{{display:grid;grid-template-columns:280px 1fr;gap:18px;align-items:start}} .score{{border:1.5px solid var(--line);border-radius:18px;background:var(--panel);padding:20px;text-align:center}} .score .big{{font-family:var(--disp);font-size:82px;line-height:1;color:var(--sand);font-weight:800}} .score .subx{{font-size:14px;color:var(--dim);margin-top:10px;line-height:1.35}} .stds{{display:grid;gap:10px}} .std{{border-left:3px solid var(--teal);padding-left:12px;font-size:17px;line-height:1.4}} .qa{{border:1.5px solid var(--line);border-radius:16px;background:var(--panel);padding:16px}} .qa .q{{font-size:23px;line-height:1.26;font-weight:700}} .ops{{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:12px}} .ops div{{border:1px solid var(--line);border-radius:12px;padding:12px 14px;font-size:17px;line-height:1.33}}
.gate{{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}} .gq{{border:1.5px solid var(--line);background:var(--panel);border-radius:16px;padding:18px}} .gq b{{display:block;font-size:14px;letter-spacing:.06em;text-transform:uppercase;color:var(--green);margin-bottom:8px}} .gq span{{font-size:21px;line-height:1.3;font-weight:600}}
.route{{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}} .route .map{{border:1.5px solid var(--line);background:var(--panel);border-radius:18px;padding:18px;display:grid;gap:12px}} .rk{{display:grid;grid-template-columns:96px 1fr auto;gap:10px;align-items:center;font-size:16px;line-height:1.34}} .rk .tag{{font-size:13px;font-weight:800;color:var(--sand);letter-spacing:.05em}} .rk .to{{border:1px solid var(--mag);color:var(--mag);border-radius:8px;padding:4px 10px;font-size:12px;font-weight:700}} .mini{{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}} .stat{{border:1.5px solid var(--line);background:var(--panel);border-radius:14px;padding:12px;text-align:center}} .stat .n{{font-family:var(--disp);font-size:26px;font-weight:700}} .stat .l{{font-size:11px;color:var(--dim2);letter-spacing:.06em;text-transform:uppercase}}
.statement{{font-size:31px;line-height:1.2;font-family:var(--disp);text-align:center;color:var(--sand)}} .speaker{{display:none}}
#bar{{position:absolute;left:0;right:0;bottom:0;height:78px;border-top:1px solid var(--line);display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding:10px 80px;background:#0c0a11}} #bar button{{border:1px solid var(--line);border-radius:14px;background:var(--panel);color:var(--ink);font-weight:900}} #bar .nav{{font-size:28px;color:var(--sand)}}
</style></head><body><div id="shell"><div id="stage"><div id="stars"></div><div id="rail">{rail}</div>{slides}<div id="bar"><button class="nav" id="prev">←</button><button id="notes">Notes</button><button class="nav" id="next">→</button><button id="present">Present</button></div></div></div><script>
const slides=[...document.querySelectorAll('.slide')], rail=[...document.querySelectorAll('#rail i')]; let idx=0;
function fit(){{const s=document.getElementById('stage'),sh=document.getElementById('shell'); const r=Math.min(sh.clientWidth/1333,sh.clientHeight/750); s.style.transform=`scale(${{r}})`;}}
function show(i){{idx=(i+slides.length)%slides.length; slides.forEach((s,n)=>s.classList.toggle('on',n===idx)); rail.forEach((x,n)=>x.classList.toggle('on',n<=idx)); slides.forEach((s,n)=>s.querySelector('.count').textContent=`${{n+1}}/${{slides.length}}`); document.title=slides[idx].dataset.title+' · {title}';}}
addEventListener('resize',fit); fit(); show(0); document.getElementById('prev').onclick=()=>show(idx-1); document.getElementById('next').onclick=()=>show(idx+1); document.getElementById('present').onclick=()=>document.documentElement.requestFullscreen?.(); document.getElementById('notes').onclick=()=>alert('Use this lecture in-class. After-Class reasoning happens separately.');
addEventListener('keydown',e=>{{if(['ArrowRight','PageDown',' '].includes(e.key)) show(idx+1); if(['ArrowLeft','PageUp'].includes(e.key)) show(idx-1); if(e.key==='Home') show(0); if(e.key==='End') show(slides.length-1);}});
</script></body></html>'''

for ch,data in chapters.items():
    slides=[]
    slides.append(section('ISCARB / CPIT-455','READY',data['title'],'In-Class lecture · visual, evidence-owned, After-Class FBR afterward.',
                          f'<div class="hero">{escape(data["hero"])}<span>{escape(data["code"])} · {escape(data["case"])} · Lecture-first, professional judgment after class.</span></div>', 'green'))
    slides.append(section('UNDERSTAND / CRISIS','RULE 01 · Decide under uncertainty','You sign before you know',data['case'],
                          '<div class="grid g3 bands">'+''.join([
