from pathlib import Path
from html import escape

OUT=Path('lectures/iscarb')

chapters={
 12:{'slug':'Ch12-Safety-Engineering.html','title':'Safety Engineering','code':'Chapter 12','case':'Night-dose confirmation on a hospital infusion pump','hero':'A system can pass all functional tests and still be unsafe in context. Safety begins where harm becomes possible.','spine':['Safety-critical systems','Hazards and losses','Safety requirements','Safety cases','SIL and sign-off'],
     'reveal':[('Hazard','A state that can lead to harm'),('Risk','Likelihood and severity together'),('Safety requirement','A constraint that blocks harm'),('Safety case','Structured argument with evidence')],
     'trade':['Safer workflow, slower operation','More alarms, more fatigue','More automation, less visibility'],
     'evidence':['Hazard log','Trace to safety requirements','Test evidence','Named safety owner'],
     'ai':'AI may summarise incidents or draft checklists, but it must not own hazard acceptance or patient-risk approval.',
     'saudi':'Healthcare software in Saudi Arabia is not judged only by features; it is judged by whether harm is controlled, evidence is inspectable, and accountability is clear.',
     'after':'After-Class: decide whether to release, constrain, or hold a safety-critical change.'},
 13:{'slug':'Ch13-Security-Engineering.html','title':'Security Engineering','code':'Chapter 13','case':'An exposed admin token in a student-information integration','hero':'Security is not a product feature. It is a design decision about assets, threats, trust boundaries, and response.','spine':['Assets and attackers','Threats and vulnerabilities','Security requirements','Trust boundaries','Defense in depth'],
     'reveal':[('Asset','What must be protected'),('Threat','What can cause compromise'),('Vulnerability','A weakness that can be exploited'),('Countermeasure','A control that reduces exposure')],
     'trade':['Stronger control, lower convenience','Faster integration, wider attack surface','More logging, more privacy obligation'],
     'evidence':['Threat model','Access-control design','Audit logs','Incident-response owner'],
     'ai':'AI may triage alerts or summarise logs, but it must not silently approve access, waive controls, or own final incident judgment.',
     'saudi':'Security decisions in Saudi digital services have legal, institutional, and societal consequences. The judgment is about defendable protection, not only technical cleverness.',
     'after':'After-Class: defend a bounded security response under incomplete information.'},
 14:{'slug':'Ch14-Resilience-Engineering.html','title':'Resilience Engineering','code':'Chapter 14','case':'A national payment gateway loses one settlement path at peak load','hero':'The key question is not whether disruption happens, but which critical service survives and how recovery is orchestrated.','spine':['Critical services','Disruptive events','Recognition','Resistance','Recovery and reinstatement'],
     'reveal':[('Recognition','Detect the disruption early'),('Resistance','Limit damage while service continues'),('Recovery','Restore the critical function quickly'),('Reinstatement','Return the wider system to normal')],
     'trade':['Preserve core service, degrade convenience','Queue safely, increase delay','Recover faster, accept temporary simplification'],
     'evidence':['Service-priority map','Runbook and drills','Fallback architecture','Named recovery authority'],
     'ai':'AI may help cluster incidents or propose recovery paths, but the human team must still prioritize critical services and accept the operational risk.',
     'saudi':'In public digital and infrastructure services, resilience means continuity of the essential service under disruption, then accountable restoration of the whole system.',
     'after':'After-Class: choose what the system must keep alive first, and justify the degradation.'},
 15:{'slug':'Ch15-Software-Reuse.html','title':'Software Reuse','code':'Chapter 15','case':'A reused authentication module speeds delivery but carries hidden lifecycle risk','hero':'Reuse saves time only when you also inherit the obligations: compatibility, maintenance, licensing, and failure ownership.','spine':['Reuse levels','COTS and open source','Software product lines','Lifecycle risk','Cost of adaptation'],
     'reveal':[('Asset you gain','Speed and proven capability'),('Debt you inherit','Assumptions, defects, and vendor constraints'),('Decision','Adopt, adapt, or build'),('Obligation','Own updates, interfaces, and evidence')],
     'trade':['Faster delivery, less local control','Lower development effort, higher dependency risk','Cheaper today, costlier adaptation later'],
     'evidence':['Compatibility analysis','Supplier/version plan','Adaptation evidence','Exit or fallback plan'],
     'ai':'AI may compare alternatives and summarise library histories, but it cannot decide whether the reused component is acceptable for your context.',
     'saudi':'Reuse in institutional systems is valuable only when the organization can defend the dependency, not merely install it.',
     'after':'After-Class: decide whether reuse is justified when the hidden lifecycle cost appears.'},
 16:{'slug':'Ch16-Component-Based-Software-Engineering.html','title':'Component-Based Software Engineering','code':'Chapter 16','case':'Two approved components integrate, but their interface semantics disagree at runtime','hero':'A component is useful only when its interfaces, contracts, and assumptions remain true when composed with others.','spine':['Components and interfaces','Required/provided services','Contracts','Composition risk','Glue code and adaptation'],
     'reveal':[('Provided service','What the component offers'),('Required service','What it needs from others'),('Contract','The condition under which the promise holds'),('Composition risk','The failure that appears between good parts')],
     'trade':['More reuse, more interface dependence','Cleaner composition, more adapter work','Stable component, rigid contract'],
     'evidence':['Interface specification','Integration tests','Semantic assumptions list','Ownership of composition'],
     'ai':'AI may draft adapters or inspect interface descriptions, but a human must still judge semantic compatibility and acceptance risk.',
     'saudi':'Enterprise and public-sector systems fail at the seams as often as inside the parts. CBSE is therefore a judgment about composition, not procurement alone.',
     'after':'After-Class: judge a component decision where semantics, not syntax, is the real risk.'},
 17:{'slug':'Ch17-Distributed-Software-Engineering.html','title':'Distributed Software Engineering','code':'Chapter 17','case':'A network partition leaves orders accepted in one service and invisible in another','hero':'In distributed systems, time, failure, and partial knowledge are design conditions — not bugs you can wish away.','spine':['Concurrency and distribution','Middleware and messaging','Replication and consistency','Partial failure','Observability and recovery'],
     'reveal':[('Partial failure','One part fails while others continue'),('Consistency','When replicas agree and when they do not'),('Latency','Time is part of correctness'),('Recovery','Reconcile state without inventing truth')],
     'trade':['Availability versus stronger consistency','More replication, more coordination cost','Faster response, more uncertainty'],
     'evidence':['Failure scenario trace','Consistency policy','Event or log evidence','Recovery owner and boundary'],
     'ai':'AI may inspect traces or summarise service behavior, but it cannot own consistency policy or reconcile truth between disagreeing services.',
     'saudi':'Distributed government and enterprise platforms must defend what happens under delay, duplication, and partition — not only in the happy path demo.',
     'after':'After-Class: defend a bounded distributed-systems verdict under partition.'},
 20:{'slug':'Ch20-Systems-of-Systems.html','title':'Systems of Systems','code':'Chapter 20','case':'Transport, health, and security systems each work alone but clash during a major event','hero':'A system of systems is not one obedient machine. Independent systems, owners, timelines, and semantics must still produce a coherent public outcome.','spine':['Operational independence','Managerial independence','Emergent behavior','Coordination and governance','Semantic alignment'],
     'reveal':[('Operational independence','Each system can operate on its own'),('Managerial independence','Owners differ and control is distributed'),('Emergence','Important behavior appears only in the whole'),('Coordination burden','Governance becomes part of engineering')],