                              '<div class="card"><div class="lab">Decision</div><div class="txt">Make a bounded professional judgment now.</div><div class="sm">You must decide whether to continue, constrain, hold, or revise.</div></div>',
                              '<div class="card"><div class="lab">Unknown</div><div class="txt">Not every relevant fact is visible yet.</div><div class="sm">The chapter gives mechanisms, but the room must still decide under uncertainty.</div></div>',
                              '<div class="card"><div class="lab">Goal</div><div class="txt">Evidence before confidence.</div><div class="sm">The standard is defendability, not the illusion of certainty.</div></div>'
                          ])+'</div>','mag'))
    slides.append(section('PRACTISE / FLOW','RULE 02 · ISCARB engineering flow','The five-step engineering flow','The source supplies mechanisms; the flow turns them into a decision.',build_svg_flow(),'sand'))
    slides.append(section('UNDERSTAND / CLOs','RULE 03 · Observable outcomes','Five outcomes you must prove','Do not memorize headings. Produce evidence for outcomes.',
                          '<div class="grid g5 bands">'+''.join([f'<div class="card"><div class="lab">{a}</div><div class="txt">{b}</div></div>' for a,b in [('1 · Explain',f'Explain the core idea of {data["title"]}.'),('2 · Trace','Trace the decision across technical and sociotechnical layers.'),('3 · Compare','Compare alternatives and name the trade-off.'),('4 · Build','Create a bounded verdict with inspectable evidence.'),('5 · Defend','Revise the verdict when the condition changes.')]])+'</div>','teal'))
    slides.append(section('UNDERSTAND / DOMAIN SPINE','RULE 04 · Source spine','The source spine','These are the chapter concepts that drive the engineering decision.',build_svg_spine(data['title'],data['spine']),'teal'))
    slides.append(section('SOURCE EXPANSION','X01 · Core concepts','The reveal','Now compare your first intuition with the source logic.',card_grid(data['reveal'],4),'sand'))
    slides.append(section('UNDERSTAND / MECHANISM','RULE 05 · Mechanism from first principles','Mechanism before vocabulary','Name the chain that turns a situation into a decision.',
                          '<div class="row"><div class="wide"><div class="wlab">MECHANISM</div><div class="wlead">Condition → constraint → evidence → verdict</div><div class="wtxt">A strong answer names the condition that matters, the constraint it creates, the evidence needed to defend it, and the professional verdict that follows.</div></div>'+build_svg_spine('Judgment chain',['Condition','Constraint','Evidence','Verdict'],'#8E7DEA')+'</div>','teal'))
    slides.append(section('PRACTISE / MAP','RULE 06 · Architecture and implementation','Map the system before you judge','Name the parts, people, policies, and evidence sources before selecting a verdict.',
                          card_grid([('Technical layer','software, data, interfaces, components, architecture'),('Operational layer','users, operators, workflow, monitoring, timing'),('Governance layer','policy, regulation, accountability, sign-off')],3),'violet'))
    slides.append(section('PRACTISE / TRADE-OFF','RULE 07 · Alternatives + trade-off','The attractive answer still has a cost','Every strong option creates a new obligation.',
                          '<div class="grid g3 bands">'+''.join([f'<div class="card"><div class="lab">Trade-off</div><div class="txt">{escape(t)}</div><div class="sm">Say what you gain, and what new burden you accept.</div></div>' for t in data['trade']])+'</div>','sand'))
    slides.append(section('PRACTISE / EVIDENCE','RULE 08 · Evidence before confidence','What would another professional inspect?','Do not ask “am I right?” first. Ask “what makes this judgment inspectable?”',
                          card_grid([(x,'This is evidence only if another professional can inspect it and use it to challenge or support the claim.') for x in data['evidence']],2),'violet'))
    slides.append(section('DISTINGUISH / KNOWN-UNKNOWN-MONITOR','RULE 09 · Boundary of assurance','Known, unknown, and monitored are not the same thing','A safe-looking answer often fails because it mixes evidence with hope.',
                          card_grid([('Known','What the evidence actually establishes now.'),('Unknown','What matters but is not yet established.'),('Monitor','What you permit only if a clear signal and response exist.')],3),'mag'))
    slides.append(section('DISTINGUISH / CONTEXT','RULE 10 · Saudi-aligned professional context','Why this chapter matters here','This topic is not abstract. It has a named destination in professional practice.',
                          f'<div class="wide"><div class="wlab">LOCAL PROFESSIONAL JUDGMENT</div><div class="wlead">{escape(data["saudi"][:96])}</div><div class="wtxt">{escape(data["saudi"])} This is why the course treats the decision as an owned engineering act rather than a generic summary of the chapter.</div></div>','green'))
    slides.append(section('MASTER / PRACTICE','RULE 11 · Worked example','A worked example of bounded judgment','The chapter becomes practical when a claim, evidence path, and boundary appear together.',
                          '<div class="row"><div class="wide"><div class="wlab">MICRO-CASE</div><div class="wlead">'+escape(data['case'])+'</div><div class="wtxt">Say what the system owes, what could fail first, what evidence you need, and what verdict you would sign right now.</div></div>'+card_grid([('FIT','What goal or requirement matters most?'),('BOUND','What condition or constraint changes the claim?'),('ACT','What professional move do you choose?'),('EVIDENCE','What artifact would justify it?')],2)+'</div>','teal'))
    slides.append(section('MASTER / AI','RULE 15 · AI assist + human sign-off','AI in the assurance chain','We are in the AI era, but responsibility did not disappear.',
                          '<div class="row"><div class="wide"><div class="wlab">AI ERA</div><div class="wlead">⚙︎ + ✦ + Human sign-off</div><div class="wtxt">'+escape(data['ai'])+'</div></div>'+card_grid([('AI may prepare','Drafts, summaries, triage, candidate checks.'),('AI must not own','Certification, approval, final risk acceptance.'),('Human sign-off','A named person reviews, accepts, revises, or rejects.')],1)+'</div>','sand'))
    slides.append(section('MASTER / STRESS TEST','RULE 16 · Breaking variable','What change would break your solution?','A robust answer exposes the variable that can reverse it.',
                          card_grid([('People','Staffing, handover, oversight, expertise'),('Time','Deadlines, urgency, maintenance window'),('Evidence','Missing test, ambiguous log, incomplete measurement'),('Boundary','New dependency, wider scope, changed interface')],4)+'<div class="statement">If the verdict never changes, you probably have not named the real variable.</div>','sand'))
    slides.append(section('DISTINGUISH / READINESS','ETEC IT 2025 · Standards-aligned practice','ETEC IT 2025 · Standards-aligned practice','Five course-written practice items aligned to outcome categories.',
                          '<div class="klo"><div class="score"><div class="big">0/5</div><div class="subx">This is practice only.<br>Use misses to decide what to reread.</div></div><div class="stds">'+''.join([f'<div class="std"><b>{escape(k)}</b> — {escape(v)}</div>' for k,v in ETEC])+'</div></div><div class="qa"><div class="q">Which item from today most directly demanded inspectable evidence rather than opinion?</div><div class="ops"><div>A. Problem analysis</div><div>B. Design under constraint</div><div>C. Communication of the verdict</div><div>D. Quality assurance and evidence</div></div></div>','teal'))
    slides.append(section('DISTINGUISH / READINESS','RULE 19 · Course readiness gate','Ready for After-Class?','Read readiness from visible evidence rather than confidence.',
                          '<div class="gate">'+''.join([f'<div class="gq"><b>Gate {i}</b><span>{q}</span></div>' for i,q in enumerate(['The core claim is named clearly.','A condition or boundary is visible.','An inspectable evidence path exists.','A way to be wrong has been named.'],1)])+'</div><div class="statement">Ready means: a claim is named, the evidence path is visible, a way to be wrong exists, and somebody owns the judgment.</div>','green'))
    slides.append(section('DISTINGUISH / SCOPE','SOURCE BOUNDARY · what this hour reached','What we covered — and what comes next','This slide defines the instructional boundary honestly.',
                          '<div class="row"><div class="wide"><div class="wlab">COVERED TODAY</div><div class="wlead">'+escape(data['title'])+' as a professional judgment problem</div><div class="wtxt">You practiced the concept spine, the trade-off, the evidence path, the stress test, and the readiness gate.</div></div><div class="wide"><div class="wlab">WHAT COMES NEXT</div><div class="wlead">Deepen the chapter through After-Class reasoning</div><div class="wtxt">'+escape(data['after'])+' The chapter is larger than the hour. The defect is hiding that fact.</div></div></div>','sand'))
    slides.append(section('DISTINGUISH / REFLECTION','YOUR ROUTE · how your answers shaped the hour','Your learning route this session','This is not a score. It is a reflection map showing how the lecture moved from concept to judgment.',
                          '<div class="route"><div class="map">'+''.join([f'<div class="rk"><div class="tag">R0{i}</div><div>{txt}</div><div class="to">next</div></div>' for i,txt in enumerate(['Crisis framed','Source mapped','Trade-off surfaced','Evidence demanded','Verdict stressed','Readiness checked'],1)])+'</div><div><div class="mini"><div class="stat"><div class="n">20</div><div class="l">Units planned</div></div><div class="stat"><div class="n">1</div><div class="l">Judgment chain</div></div><div class="stat"><div class="n">1</div><div class="l">Readiness gate</div></div><div class="stat"><div class="n">1</div><div class="l">After-Class task</div></div></div><div class="wide" style="margin-top:12px"><div class="wlab">HOW TO READ IT</div><div class="wlead">Support is not a penalty.</div><div class="wtxt">If you needed more explanation in any unit, that simply marks a unit worth rereading before the assignment.</div></div></div></div>','violet'))
    slides.append(section('DISTINGUISH / VERDICT','RULE 20 · Bound the professional decision','What you should leave with','The chapter ends in a bounded professional judgment, not a loose impression.',
                          '<div class="statement">'+escape(data['after'])+'</div><div class="wide"><div class="wlab">TAKEAWAY</div><div class="wlead">A strong engineering answer is inspectable, bounded, and owned.</div><div class="wtxt">That is the bridge from today’s In-Class lecture to the After-Class FBR assignment.</div></div>','green'))
    html=TEMPLATE_HEAD.format(title=f'{data["code"]} · {data["title"]}', rail=''.join('<i></i>' for _ in range(20)), slides=''.join(slides))
    (OUT/data['slug']).write_text(html, encoding='utf-8')
    print('Wrote',data['slug'])
