"""Generate the in-class Python demo ("Live lab · from slide to Python") for Chapters 12-20.

Each lecture's extra slide X-LAB shows a short Python example from the lecture's own story (not the
assignment case): the buggy version, three tests, and the fix. The class predicts which test fails,
then reveals the result. The results are produced here by CPython with the same harness as the
assignments, verified (buggy fails at least one test, fixed passes all), and embedded in
lectures/iscarb/runtime/story-v3.js between generated markers, so the slide works offline.

Sources: curriculum/learning-path/builds/class/chNN.py (sections: helpers, buggy, fixed, tests, show).
Idempotent:  python3 tools/apply_class_builds.py
"""
from __future__ import annotations
import json, re, sys, traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'curriculum/learning-path/builds/class'
STORY = ROOT / 'lectures/iscarb/runtime/story-v3.js'
BEGIN, END = '/* class-builds:begin (generated by tools/apply_class_builds.py) */', '/* class-builds:end */'

META = {
 12: dict(question='The crew sees the nose pushed down. Which single event can cause that on its own, and which of the three tests fail on the current design?',
          map=[(10, 'A fault tree reads logic: OR = any one input is enough; AND = all inputs are needed.', 'OR(...), AND(...)'),
               (17, 'Check every path to the unsafe exit.', 'cut_sets(tree) lists every path'),
               (11, 'Make “shall not” checkable.', 'single_points(tree) == []')],
          bridge='Assignment 3: the same steps for the loading-bay barrier. Build current and revised trees, then test that no single event causes the hazard.'),
 13: dict(question='The page shows each student only their own link. Which test fails, and why is a hidden link not access control?',
          map=[(8, 'A testable claim names the actor, the action, the object and the evidence.', 'each test names a user, a grade and the result'),
               (13, 'Test the boundary with a counterexample, not only the normal case.', 'test_another_student_is_refused'),
               (18, 'An instruction or a hidden link is not an access control.', 'the server checks role and owner')],
          bridge='Assignment 4: the same steps for the project portal. Write can_read and tests that try to cross the boundary.'),
 14: dict(question='After the outage, staff merge the paper records back. Which test fails, and what does the student see the next morning?',
          map=[(5, 'Recovery and reinstatement are different jobs.', 'merge runs at reinstatement'),
               (17, 'A fallback must be reconciled afterwards.', 'merge(central, offline)'),
               (12, 'An emergency mode must record who acted.', 'each record keeps its id')],
          bridge='Assignment 5: the same steps for the transport desk. Write reconcile, apply each change once, and report stale changes as conflicts.'),
 15: dict(question='The vendor’s brochure mentions single sign-on. Which test fails, and what is the difference between a claim and evidence?',
          map=[(8, '“Configurable” is a capability claim; only a demonstrated instance shows fit.', 'brochure ≠ demonstrated'),
               (15, 'Compare reuse routes by the test that would prove them.', 'status returns unknown'),
               (17, 'A wrapper hides the interface, not the assumptions.', 'the unchecked feature stays unknown')],
          bridge='Assignment 6: the same steps for the booking system. Write fit, shortlist and evidence_needed from the supplied facts only.'),
 16: dict(question='The app sends litres; the pump expects millilitres. The types match. Which tests fail?',
          map=[(9, 'A number type is only syntax: state the unit, range and meaning.', 'litres × 1000 = ml'),
               (16, 'Preconditions before the call, postconditions after it.', 'ValueError before, RuntimeError after'),
               (12, 'Ariane: earlier success does not carry over to a new context.', 'test the new range')],
          bridge='Assignment 7: the same steps for the room-booking component. Write reserve_minutes: precondition, conversion, postcondition.'),
 17: dict(question='The reply to a payment is lost and the app retries. Which tests fail, and how much is the customer charged?',
          map=[(7, 'A timeout does not tell you whether the work happened.', 'test_retry_after_lost_reply'),
               (9, 'Keep the uncertainty visible; record the outcome before replying.', 'store["done"][request_id]'),
               (19, 'A retry is a new request unless it carries the same identity.', 'the same request_id')],
          bridge='Assignment 8: the same steps for event registration. Make reserve idempotent, including after a restart.'),
 20: dict(question='The lift feed lost its connection ten minutes ago. Which tests fail, and what does the dashboard tell the duty officer?',
          map=[(13, 'When a feed fails, show what is missing or stale; do not hide it.', 'unavailable / stale, 9 min old'),
               (8, 'Promise what the dashboard controls; label what it only receives.', 'the label shows the age'),
               (15, 'Data feeds need bounded waits and agreed formats.', 'limit=5')],
          bridge='Assignment 9: the same steps for the incident dashboard. Write display_state and headline, and never call a degraded view live.'),
}
ASSIGNMENT = {12: 3, 13: 4, 14: 5, 15: 6, 16: 7, 17: 8, 20: 9}


def sections(text: str) -> dict:
    out, cur = {}, None
    for line in text.splitlines(keepends=True):
        m = re.match(r'# --- (\w+) ---\s*$', line)
        if m: cur = m.group(1); out[cur] = ''; continue
        if cur: out[cur] += line
    return {k: v.strip('\n') + '\n' for k, v in out.items()}


def run(helpers: str, code: str, tests: str, show: str | None) -> dict:
    ns: dict = {'__name__': 'classbuild'}
    exec(helpers, ns); exec(code, ns); exec(tests, ns)
    res = []
    for name in [k for k in tests_order(tests)]:
        try:
            ns[name](); res.append([name, True, ''])
        except AssertionError as e:
            res.append([name, False, 'assertion failed' + (': ' + str(e) if str(e) else '')])
        except Exception as e:
            res.append([name, False, type(e).__name__ + (': ' + str(e) if str(e) else '')])
    out = {'tests': res}
    if show: out['show'] = show.strip() + '  →  ' + repr(eval(show.strip(), ns))
    return out


def tests_order(tests: str) -> list[str]:
    return re.findall(r'^def (test_\w+)\(', tests, re.M)


def build() -> dict:
    data = {}
    for ch in META:
        s = sections((SRC / f'ch{ch}.py').read_text(encoding='utf-8'))
        helpers = s.get('helpers', '')
        if ch == 12: helpers = (ROOT / 'curriculum/learning-path/builds/ch12_helpers.py').read_text(encoding='utf-8')
        b = run(helpers, s['buggy'], s['tests'], s.get('show'))
        f = run(helpers, s['fixed'], s['tests'], s.get('show'))
        if all(ok for _, ok, _ in b['tests']): raise SystemExit(f'Ch{ch}: the buggy version passes every test')
        if not all(ok for _, ok, _ in f['tests']): raise SystemExit(f'Ch{ch}: the fixed version fails {f["tests"]}')
        data[ch] = dict(META[ch], assignment=ASSIGNMENT[ch], helpers=s.get('helpers', '') if ch != 12 else '', buggy=s['buggy'], fixed=s['fixed'], tests=s['tests'],
                        result={'buggy': b, 'fixed': f}, map=[list(r) for r in META[ch]['map']])
    return data


def main() -> int:
    data = build()
    block = BEGIN + '\n(function (S) {\n  if (!S) return;\n  const B = ' + json.dumps({str(k): v for k, v in data.items()}, ensure_ascii=False, indent=1) + ';\n  for (const k in B) if (S.chapters[k]) S.chapters[k].build = B[k];\n})(window.ISCARB_STORY);\n' + END + '\n'
    s = STORY.read_text(encoding='utf-8')
    if BEGIN in s:
        s2 = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n', lambda _: block, s, flags=re.S)
    else:
        s2 = s.rstrip('\n') + '\n' + block
    if s2 != s: STORY.write_text(s2, encoding='utf-8')
    for ch, d in data.items():
        print(f"Ch{ch}: buggy fails {[n for n, ok, _ in d['result']['buggy']['tests'] if not ok]}; fixed passes all")
    return 0


if __name__ == '__main__':
    sys.exit(main())
