// Functional source, reveal and recovery checks. Real visual tests are separate.
const assert=require('node:assert/strict');const {root,read,load,put}=require('./classroom-harness.cjs');
const pub=JSON.parse(read('curriculum/publication.json'));
(async()=>{for(const c of pub.lectures){const x=load(c);try{
 const D=x.api.data;
 for(const s of D.slides){x.api.go(D.slides.indexOf(s));assert(x.d.getElementById('modal').hidden);if(!['TITLE','START','MAP','END'].includes(s.id)){assert(x.d.querySelectorAll('.points li').length>0||x.d.querySelector('.table-main,.two-approaches'),'Concept screen must contain its points or technical comparison table');assert(!x.d.querySelector('#chapter-main .model-answer'));x.api.full(s.id);assert(!x.d.getElementById('modal').hidden);assert.match(x.d.getElementById('modal-title').textContent,/Full explanation/);x.api.closeModal();x.api.answer(s.id);assert(x.d.getElementById('modal-body').textContent.includes(s.answer||'A defensible response'));x.api.closeModal();}}
 x.api.open('QUIZ');x.d.getElementById('quiz-check').click();assert.match(x.d.getElementById('quiz-feedback').textContent,/Choose/);
 for(let i=0;i<5;i++){x.d.querySelector('[data-quiz="'+i+'"]').click();let r=x.d.querySelector('input[name="quiz"][value="'+D.quiz[i].answer+'"]');r.checked=true;r.dispatchEvent(new x.w.Event('change',{bubbles:true}));x.d.getElementById('quiz-check').click();assert.match(x.d.getElementById('quiz-feedback').textContent,/Correct for/);}
 x.api.open('CARD');put(x,'claim','Boundary <script>window.bad=true</script>');assert(!x.w.bad);put(x,'counter','One inspectable observation changes the decision');
 const backup=JSON.parse(JSON.stringify(x.api.pack()));assert.equal(x.api.sanitize(backup).state.fields.claim,backup.state.fields.claim);assert.throws(()=>x.api.sanitize({...backup,chapter:999}));assert.throws(()=>x.api.sanitize({...backup,state:{fields:{claim:42}}}));assert.throws(()=>x.api.sanitize({...backup,state:{fields:JSON.parse('{"__proto__":"x"}')}}));
 const saved=Object.fromEntries(Array.from({length:x.w.localStorage.length},(_,i)=>{let k=x.w.localStorage.key(i);return[k,x.w.localStorage.getItem(k)]}));const y=load(c,{saved});assert.equal(y.api.getState().fields.claim,backup.state.fields.claim);assert.equal(Object.keys(y.api.getState().quiz).length,5);assert.deepEqual(y.errors,[]);y.dom.window.close();
 assert.match(x.api.aiVerdict({0:'yes',1:'no',2:'no',3:'yes'}),/Not permitted/);assert.match(x.api.aiVerdict({0:'yes',1:'no',2:'yes',3:'yes'}),/Conditionally/);assert.match(x.api.aiVerdict({0:'yes',1:'yes',3:'no'}),/Not permitted/);
 if(c.chapter===11){x.api.open('CALCULATOR');assert.match(x.d.getElementById('calc-result').textContent,/0.002 per demand/);assert.match(x.d.getElementById('calc-result').textContent,/99.9%/);x.d.getElementById('calc-events').value='0';x.api.compute();assert.match(x.d.getElementById('calc-result').textContent,/not estimable/);x.d.getElementById('calc-demands').value='';x.api.compute();assert.match(x.d.getElementById('calc-result').textContent,/blank is not zero/);}
 const b=load(c,{blockStorage:true});b.api.open('CARD');assert.match(b.d.querySelector('[data-save-status]').textContent,/unavailable/);put(b,'claim','Export even when storage is unavailable');assert.equal(b.api.pack().state.fields.claim,'Export even when storage is unavailable');assert.deepEqual(b.errors,[]);b.dom.window.close();
 assert.deepEqual(x.errors,[]);console.log('PASS CH'+c.chapter+' · separate explanations/answers, five attempts, escaped text, round-trip/reload, AI gate and storage failure');
 }finally{x.dom.window.close();}}})().catch(e=>{console.error(e);process.exitCode=1});
